"""Database/serialization signatures — sig_db v1.13 Dalga 2 migrasyonu (ADR 0007 A7).

Kaynak: karadul/analyzers/signature_db.py
  - _SQLITE_SIGNATURES         -> sqlite_signatures
  - _DATABASE_EXT_SIGNATURES   -> database_ext_signatures
  - _PROTOBUF_SIGNATURES       -> protobuf_signatures
  - _JSON_SIGNATURES           -> json_signatures
  - _XML_SIGNATURES            -> xml_signatures
  - _SERIALIZATION_SIGNATURES  -> serialization_signatures

Toplam: 579 imza (6 dict).

ADR 0007 Tip A yumusak override on-hazirligi: bu modul orijinal dict
icerikleri ile birebir aynidir (AST literal_eval ile dogrulanir). v1.13
A-DELETE asamasinda signature_db.py inline govdeleri silinip dogrudan
``from sigdb_builtin.database import SIGNATURES`` referansi kullanilacaktir.
Bu adimda signature_db.py'a DOKUNULMAMISTIR; sadece veri ayna modulu
olusturulmustur.

Anahtar isimleri signature_db.py'deki orijinal dict adlariyla uyumludur:
  ``sqlite_signatures``         <-> ``_SQLITE_SIGNATURES``
  ``database_ext_signatures``   <-> ``_DATABASE_EXT_SIGNATURES``
  ``protobuf_signatures``       <-> ``_PROTOBUF_SIGNATURES``
  ``json_signatures``           <-> ``_JSON_SIGNATURES``
  ``xml_signatures``            <-> ``_XML_SIGNATURES``
  ``serialization_signatures``  <-> ``_SERIALIZATION_SIGNATURES``

NOT (protobuf): ``_PROTOBUF_SIGNATURES`` icindeki anahtarlarin bir kismi
namespace'li (``google::protobuf::Message::SerializeToString``) bir kismi
Itanium-mangled (``_ZN6google8protobuf...``) seklindedir. signature_db.py
icindeki ``_PROTOBUF_BASENAME_INDEX`` insasi "::"-li isimlerden son parcayi
basename olarak alir; bu yapi migration sonrasi da korundugu icin index
yeniden insasi sembol kaybi olmadan calisir.

NOT (cakisma): ``_SERIALIZATION_SIGNATURES`` (FlatBuffers/Cap'n Proto/MsgPack)
ve ``_PROTOBUF_SIGNATURES`` "category: serialization" tasiyor; ``serialization``
sigdb_builtin modulu su an placeholder. ADR 0007 A7'de tum 6 dict ``database``
kapsamina alinmistir; ileride yeniden kategorize etme A7-rafinaj veya
A-DELETE sonrasinda ele alinir.
"""
from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# sqlite (144 entry) — SQLite C API: open/close, prepared statements, binding, sonuc kolonlari, blob I/O, WAL, hooks, vtab, encryption (SEE/sqlcipher).
# Kaynak: signature_db.py satir 860-1007.
# ---------------------------------------------------------------------------
_SQLITE_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    "_sqlite3_open": {"lib": "sqlite3", "purpose": "open database", "category": "database"},
    "_sqlite3_open_v2": {"lib": "sqlite3", "purpose": "open database (v2 flags)", "category": "database"},
    "_sqlite3_close": {"lib": "sqlite3", "purpose": "close database", "category": "database"},
    "_sqlite3_close_v2": {"lib": "sqlite3", "purpose": "close database (deferred)", "category": "database"},
    "_sqlite3_exec": {"lib": "sqlite3", "purpose": "execute SQL one-shot", "category": "database"},
    "_sqlite3_prepare_v2": {"lib": "sqlite3", "purpose": "prepare SQL statement", "category": "database"},
    "_sqlite3_prepare_v3": {"lib": "sqlite3", "purpose": "prepare SQL statement (v3)", "category": "database"},
    "_sqlite3_step": {"lib": "sqlite3", "purpose": "step prepared statement", "category": "database"},
    "_sqlite3_finalize": {"lib": "sqlite3", "purpose": "finalize statement", "category": "database"},
    "_sqlite3_reset": {"lib": "sqlite3", "purpose": "reset statement", "category": "database"},
    "_sqlite3_bind_blob": {"lib": "sqlite3", "purpose": "bind blob parameter", "category": "database"},
    "_sqlite3_bind_double": {"lib": "sqlite3", "purpose": "bind double parameter", "category": "database"},
    "_sqlite3_bind_int": {"lib": "sqlite3", "purpose": "bind int parameter", "category": "database"},
    "_sqlite3_bind_int64": {"lib": "sqlite3", "purpose": "bind int64 parameter", "category": "database"},
    "_sqlite3_bind_null": {"lib": "sqlite3", "purpose": "bind null parameter", "category": "database"},
    "_sqlite3_bind_text": {"lib": "sqlite3", "purpose": "bind text parameter", "category": "database"},
    "_sqlite3_bind_text16": {"lib": "sqlite3", "purpose": "bind UTF-16 text", "category": "database"},
    "_sqlite3_bind_parameter_count": {"lib": "sqlite3", "purpose": "parameter count", "category": "database"},
    "_sqlite3_bind_parameter_name": {"lib": "sqlite3", "purpose": "parameter name", "category": "database"},
    "_sqlite3_bind_parameter_index": {"lib": "sqlite3", "purpose": "parameter index", "category": "database"},
    "_sqlite3_column_blob": {"lib": "sqlite3", "purpose": "column blob result", "category": "database"},
    "_sqlite3_column_bytes": {"lib": "sqlite3", "purpose": "column byte count", "category": "database"},
    "_sqlite3_column_count": {"lib": "sqlite3", "purpose": "result column count", "category": "database"},
    "_sqlite3_column_double": {"lib": "sqlite3", "purpose": "column double result", "category": "database"},
    "_sqlite3_column_int": {"lib": "sqlite3", "purpose": "column int result", "category": "database"},
    "_sqlite3_column_int64": {"lib": "sqlite3", "purpose": "column int64 result", "category": "database"},
    "_sqlite3_column_name": {"lib": "sqlite3", "purpose": "column name", "category": "database"},
    "_sqlite3_column_text": {"lib": "sqlite3", "purpose": "column text result", "category": "database"},
    "_sqlite3_column_text16": {"lib": "sqlite3", "purpose": "column UTF-16 result", "category": "database"},
    "_sqlite3_column_type": {"lib": "sqlite3", "purpose": "column type code", "category": "database"},
    "_sqlite3_column_value": {"lib": "sqlite3", "purpose": "column generic value", "category": "database"},
    "_sqlite3_errmsg": {"lib": "sqlite3", "purpose": "error message", "category": "database"},
    "_sqlite3_errcode": {"lib": "sqlite3", "purpose": "error code", "category": "database"},
    "_sqlite3_extended_errcode": {"lib": "sqlite3", "purpose": "extended error code", "category": "database"},
    "_sqlite3_errstr": {"lib": "sqlite3", "purpose": "error string from code", "category": "database"},
    "_sqlite3_changes": {"lib": "sqlite3", "purpose": "changed row count", "category": "database"},
    "_sqlite3_total_changes": {"lib": "sqlite3", "purpose": "total changed rows", "category": "database"},
    "_sqlite3_last_insert_rowid": {"lib": "sqlite3", "purpose": "last insert rowid", "category": "database"},
    "_sqlite3_busy_timeout": {"lib": "sqlite3", "purpose": "busy timeout config", "category": "database"},
    "_sqlite3_busy_handler": {"lib": "sqlite3", "purpose": "busy handler callback", "category": "database"},
    "_sqlite3_db_config": {"lib": "sqlite3", "purpose": "database config", "category": "database"},
    "_sqlite3_db_handle": {"lib": "sqlite3", "purpose": "get db handle from stmt", "category": "database"},
    "_sqlite3_free": {"lib": "sqlite3", "purpose": "free sqlite memory", "category": "database"},
    "_sqlite3_malloc": {"lib": "sqlite3", "purpose": "sqlite memory allocation", "category": "database"},
    "_sqlite3_realloc": {"lib": "sqlite3", "purpose": "sqlite memory realloc", "category": "database"},
    "_sqlite3_mprintf": {"lib": "sqlite3", "purpose": "formatted string (sqlite alloc)", "category": "database"},
    "_sqlite3_snprintf": {"lib": "sqlite3", "purpose": "formatted string (buffer)", "category": "database"},
    "_sqlite3_create_function_v2": {"lib": "sqlite3", "purpose": "register SQL function", "category": "database"},
    "_sqlite3_create_collation_v2": {"lib": "sqlite3", "purpose": "register collation", "category": "database"},
    "_sqlite3_result_blob": {"lib": "sqlite3", "purpose": "SQL function return blob", "category": "database"},
    "_sqlite3_result_double": {"lib": "sqlite3", "purpose": "SQL function return double", "category": "database"},
    "_sqlite3_result_error": {"lib": "sqlite3", "purpose": "SQL function return error", "category": "database"},
    "_sqlite3_result_int": {"lib": "sqlite3", "purpose": "SQL function return int", "category": "database"},
    "_sqlite3_result_int64": {"lib": "sqlite3", "purpose": "SQL function return int64", "category": "database"},
    "_sqlite3_result_null": {"lib": "sqlite3", "purpose": "SQL function return null", "category": "database"},
    "_sqlite3_result_text": {"lib": "sqlite3", "purpose": "SQL function return text", "category": "database"},
    "_sqlite3_value_blob": {"lib": "sqlite3", "purpose": "SQL function arg blob", "category": "database"},
    "_sqlite3_value_bytes": {"lib": "sqlite3", "purpose": "SQL function arg bytes", "category": "database"},
    "_sqlite3_value_double": {"lib": "sqlite3", "purpose": "SQL function arg double", "category": "database"},
    "_sqlite3_value_int": {"lib": "sqlite3", "purpose": "SQL function arg int", "category": "database"},
    "_sqlite3_value_int64": {"lib": "sqlite3", "purpose": "SQL function arg int64", "category": "database"},
    "_sqlite3_value_text": {"lib": "sqlite3", "purpose": "SQL function arg text", "category": "database"},
    "_sqlite3_value_type": {"lib": "sqlite3", "purpose": "SQL function arg type", "category": "database"},
    "_sqlite3_blob_open": {"lib": "sqlite3", "purpose": "blob open for I/O", "category": "database"},
    "_sqlite3_blob_close": {"lib": "sqlite3", "purpose": "blob close", "category": "database"},
    "_sqlite3_blob_read": {"lib": "sqlite3", "purpose": "blob read", "category": "database"},
    "_sqlite3_blob_write": {"lib": "sqlite3", "purpose": "blob write", "category": "database"},
    "_sqlite3_blob_bytes": {"lib": "sqlite3", "purpose": "blob size", "category": "database"},
    "_sqlite3_wal_checkpoint_v2": {"lib": "sqlite3", "purpose": "WAL checkpoint", "category": "database"},
    "_sqlite3_wal_autocheckpoint": {"lib": "sqlite3", "purpose": "WAL auto-checkpoint config", "category": "database"},
    "_sqlite3_backup_init": {"lib": "sqlite3", "purpose": "online backup init", "category": "database"},
    "_sqlite3_backup_step": {"lib": "sqlite3", "purpose": "online backup step", "category": "database"},
    "_sqlite3_backup_finish": {"lib": "sqlite3", "purpose": "online backup finish", "category": "database"},
    "_sqlite3_libversion": {"lib": "sqlite3", "purpose": "sqlite version string", "category": "database"},
    "_sqlite3_libversion_number": {"lib": "sqlite3", "purpose": "sqlite version number", "category": "database"},
    "_sqlite3_threadsafe": {"lib": "sqlite3", "purpose": "thread safety level", "category": "database"},
    "_sqlite3_config": {"lib": "sqlite3", "purpose": "global config", "category": "database"},
    "_sqlite3_initialize": {"lib": "sqlite3", "purpose": "sqlite init", "category": "database"},
    "_sqlite3_shutdown": {"lib": "sqlite3", "purpose": "sqlite shutdown", "category": "database"},
    "_sqlite3_key": {"lib": "sqlite3", "purpose": "database encryption key (SEE/sqlcipher)", "category": "database"},
    "_sqlite3_rekey": {"lib": "sqlite3", "purpose": "change encryption key", "category": "database"},
    "_sqlite3_set_authorizer": {"lib": "sqlite3", "purpose": "SQL authorizer callback", "category": "database"},
    "_sqlite3_trace_v2": {"lib": "sqlite3", "purpose": "SQL trace callback", "category": "database"},
    "_sqlite3_stmt_status": {"lib": "sqlite3", "purpose": "statement status counters", "category": "database"},
    "_sqlite3_table_column_metadata": {"lib": "sqlite3", "purpose": "table column metadata", "category": "database"},
    "_sqlite3_expanded_sql": {"lib": "sqlite3", "purpose": "expanded SQL text", "category": "database"},
    "_sqlite3_normalized_sql": {"lib": "sqlite3", "purpose": "normalized SQL text", "category": "database"},
    "_sqlite3_enable_load_extension": {"lib": "sqlite3", "purpose": "enable extension loading", "category": "database"},
    "_sqlite3_load_extension": {"lib": "sqlite3", "purpose": "load extension", "category": "database"},
    # SQLite genisleme: create_function, wal_checkpoint, vb.
    "_sqlite3_create_function": {"lib": "sqlite3", "purpose": "register SQL function (v1)", "category": "database"},
    "_sqlite3_wal_checkpoint": {"lib": "sqlite3", "purpose": "WAL checkpoint (basic)", "category": "database"},
    "_sqlite3_blob_reopen": {"lib": "sqlite3", "purpose": "reopen blob on new row", "category": "database"},
    "_sqlite3_backup_remaining": {"lib": "sqlite3", "purpose": "online backup remaining pages", "category": "database"},
    "_sqlite3_backup_pagecount": {"lib": "sqlite3", "purpose": "online backup total pages", "category": "database"},
    "_sqlite3_db_filename": {"lib": "sqlite3", "purpose": "get database filename", "category": "database"},
    "_sqlite3_db_readonly": {"lib": "sqlite3", "purpose": "check if database is read-only", "category": "database"},
    "_sqlite3_db_status": {"lib": "sqlite3", "purpose": "database status counters", "category": "database"},
    "_sqlite3_status": {"lib": "sqlite3", "purpose": "global sqlite status", "category": "database"},
    "_sqlite3_status64": {"lib": "sqlite3", "purpose": "global sqlite status (64-bit)", "category": "database"},
    "_sqlite3_memory_used": {"lib": "sqlite3", "purpose": "current memory usage", "category": "database"},
    "_sqlite3_memory_highwater": {"lib": "sqlite3", "purpose": "peak memory usage", "category": "database"},
    "_sqlite3_soft_heap_limit64": {"lib": "sqlite3", "purpose": "set soft heap limit", "category": "database"},
    "_sqlite3_hard_heap_limit64": {"lib": "sqlite3", "purpose": "set hard heap limit", "category": "database"},
    "_sqlite3_compileoption_used": {"lib": "sqlite3", "purpose": "check compile option", "category": "database"},
    "_sqlite3_compileoption_get": {"lib": "sqlite3", "purpose": "get compile option by index", "category": "database"},
    "_sqlite3_complete": {"lib": "sqlite3", "purpose": "check SQL completeness", "category": "database"},
    "_sqlite3_interrupt": {"lib": "sqlite3", "purpose": "interrupt running query", "category": "database"},
    "_sqlite3_progress_handler": {"lib": "sqlite3", "purpose": "register progress callback", "category": "database"},
    "_sqlite3_commit_hook": {"lib": "sqlite3", "purpose": "register commit callback", "category": "database"},
    "_sqlite3_rollback_hook": {"lib": "sqlite3", "purpose": "register rollback callback", "category": "database"},
    "_sqlite3_update_hook": {"lib": "sqlite3", "purpose": "register update callback", "category": "database"},
    "_sqlite3_unlock_notify": {"lib": "sqlite3", "purpose": "register unlock notify callback", "category": "database"},
    "_sqlite3_data_count": {"lib": "sqlite3", "purpose": "result data column count", "category": "database"},
    "_sqlite3_sql": {"lib": "sqlite3", "purpose": "get SQL text from statement", "category": "database"},
    "_sqlite3_clear_bindings": {"lib": "sqlite3", "purpose": "clear all statement bindings", "category": "database"},
    "_sqlite3_bind_blob64": {"lib": "sqlite3", "purpose": "bind blob parameter (64-bit len)", "category": "database"},
    "_sqlite3_bind_text64": {"lib": "sqlite3", "purpose": "bind text parameter (64-bit len)", "category": "database"},
    "_sqlite3_bind_zeroblob": {"lib": "sqlite3", "purpose": "bind zero-filled blob", "category": "database"},
    "_sqlite3_bind_zeroblob64": {"lib": "sqlite3", "purpose": "bind zero-filled blob (64-bit)", "category": "database"},
    "_sqlite3_bind_value": {"lib": "sqlite3", "purpose": "bind generic sqlite3_value", "category": "database"},
    "_sqlite3_bind_pointer": {"lib": "sqlite3", "purpose": "bind pointer value", "category": "database"},
    "_sqlite3_column_bytes16": {"lib": "sqlite3", "purpose": "column UTF-16 byte count", "category": "database"},
    "_sqlite3_column_database_name": {"lib": "sqlite3", "purpose": "column database name", "category": "database"},
    "_sqlite3_column_table_name": {"lib": "sqlite3", "purpose": "column table name", "category": "database"},
    "_sqlite3_column_origin_name": {"lib": "sqlite3", "purpose": "column origin name", "category": "database"},
    "_sqlite3_result_error_code": {"lib": "sqlite3", "purpose": "SQL function return error code", "category": "database"},
    "_sqlite3_result_error_nomem": {"lib": "sqlite3", "purpose": "SQL function return NOMEM error", "category": "database"},
    "_sqlite3_result_error_toobig": {"lib": "sqlite3", "purpose": "SQL function return TOOBIG error", "category": "database"},
    "_sqlite3_result_int64": {"lib": "sqlite3", "purpose": "SQL function return int64", "category": "database"},
    "_sqlite3_result_text16": {"lib": "sqlite3", "purpose": "SQL function return UTF-16 text", "category": "database"},
    "_sqlite3_result_value": {"lib": "sqlite3", "purpose": "SQL function return sqlite3_value", "category": "database"},
    "_sqlite3_result_zeroblob": {"lib": "sqlite3", "purpose": "SQL function return zero blob", "category": "database"},
    "_sqlite3_result_subtype": {"lib": "sqlite3", "purpose": "SQL function return subtype", "category": "database"},
    "_sqlite3_aggregate_context": {"lib": "sqlite3", "purpose": "get aggregate function context", "category": "database"},
    "_sqlite3_user_data": {"lib": "sqlite3", "purpose": "get function user data", "category": "database"},
    "_sqlite3_context_db_handle": {"lib": "sqlite3", "purpose": "get db handle from context", "category": "database"},
    "_sqlite3_create_module_v2": {"lib": "sqlite3", "purpose": "register virtual table module", "category": "database"},
    "_sqlite3_declare_vtab": {"lib": "sqlite3", "purpose": "declare virtual table schema", "category": "database"},
    "_sqlite3_overload_function": {"lib": "sqlite3", "purpose": "overload function for vtab", "category": "database"},
    "_sqlite3_vtab_config": {"lib": "sqlite3", "purpose": "virtual table config", "category": "database"},
    "_sqlite3_vtab_on_conflict": {"lib": "sqlite3", "purpose": "virtual table conflict mode", "category": "database"},
    "_sqlite3_sourceid": {"lib": "sqlite3", "purpose": "sqlite source ID string", "category": "database"},
    "_sqlite3_auto_extension": {"lib": "sqlite3", "purpose": "register auto-load extension", "category": "database"},
    "_sqlite3_cancel_auto_extension": {"lib": "sqlite3", "purpose": "cancel auto-load extension", "category": "database"},
    "_sqlite3_reset_auto_extension": {"lib": "sqlite3", "purpose": "reset all auto-load extensions", "category": "database"},
}


# ---------------------------------------------------------------------------
# database_ext (96 entry) — MySQL (libmysqlclient), PostgreSQL (libpq), Redis (hiredis), LMDB, LevelDB.
# Kaynak: signature_db.py satir 4613-4719.
# ---------------------------------------------------------------------------
_DATABASE_EXT_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # --- MySQL (libmysqlclient / C API) ---
    "mysql_init": {"lib": "libmysqlclient", "purpose": "initialize MySQL handle", "category": "database"},
    "mysql_real_connect": {"lib": "libmysqlclient", "purpose": "connect to MySQL server", "category": "database"},
    "mysql_close": {"lib": "libmysqlclient", "purpose": "close MySQL connection", "category": "database"},
    "mysql_query": {"lib": "libmysqlclient", "purpose": "execute SQL query", "category": "database"},
    "mysql_real_query": {"lib": "libmysqlclient", "purpose": "execute query with length", "category": "database"},
    "mysql_store_result": {"lib": "libmysqlclient", "purpose": "store full result set", "category": "database"},
    "mysql_use_result": {"lib": "libmysqlclient", "purpose": "initiate row-by-row retrieval", "category": "database"},
    "mysql_fetch_row": {"lib": "libmysqlclient", "purpose": "fetch next result row", "category": "database"},
    "mysql_fetch_fields": {"lib": "libmysqlclient", "purpose": "fetch column metadata", "category": "database"},
    "mysql_num_rows": {"lib": "libmysqlclient", "purpose": "get result row count", "category": "database"},
    "mysql_num_fields": {"lib": "libmysqlclient", "purpose": "get result column count", "category": "database"},
    "mysql_free_result": {"lib": "libmysqlclient", "purpose": "free result set", "category": "database"},
    "mysql_error": {"lib": "libmysqlclient", "purpose": "get last error message", "category": "database"},
    "mysql_errno": {"lib": "libmysqlclient", "purpose": "get last error code", "category": "database"},
    "mysql_stmt_init": {"lib": "libmysqlclient", "purpose": "initialize prepared statement", "category": "database"},
    "mysql_stmt_prepare": {"lib": "libmysqlclient", "purpose": "prepare SQL statement", "category": "database"},
    "mysql_stmt_execute": {"lib": "libmysqlclient", "purpose": "execute prepared statement", "category": "database"},
    "mysql_stmt_bind_param": {"lib": "libmysqlclient", "purpose": "bind input parameters", "category": "database"},
    "mysql_stmt_bind_result": {"lib": "libmysqlclient", "purpose": "bind output columns", "category": "database"},
    "mysql_stmt_fetch": {"lib": "libmysqlclient", "purpose": "fetch prepared statement row", "category": "database"},
    "mysql_stmt_close": {"lib": "libmysqlclient", "purpose": "close prepared statement", "category": "database"},
    "mysql_autocommit": {"lib": "libmysqlclient", "purpose": "set autocommit mode", "category": "database"},
    "mysql_commit": {"lib": "libmysqlclient", "purpose": "commit transaction", "category": "database"},
    "mysql_rollback": {"lib": "libmysqlclient", "purpose": "rollback transaction", "category": "database"},
    "mysql_ping": {"lib": "libmysqlclient", "purpose": "ping server / reconnect", "category": "database"},
    "mysql_select_db": {"lib": "libmysqlclient", "purpose": "select database", "category": "database"},
    "mysql_real_escape_string": {"lib": "libmysqlclient", "purpose": "escape string for SQL", "category": "database"},
    "mysql_set_character_set": {"lib": "libmysqlclient", "purpose": "set connection character set", "category": "database"},

    # --- PostgreSQL (libpq) ---
    "PQconnectdb": {"lib": "libpq", "purpose": "connect to PostgreSQL (connection string)", "category": "database"},
    "PQconnectdbParams": {"lib": "libpq", "purpose": "connect with parameter arrays", "category": "database"},
    "PQfinish": {"lib": "libpq", "purpose": "close PostgreSQL connection", "category": "database"},
    "PQstatus": {"lib": "libpq", "purpose": "get connection status", "category": "database"},
    "PQerrorMessage": {"lib": "libpq", "purpose": "get last error message", "category": "database"},
    "PQexec": {"lib": "libpq", "purpose": "execute SQL command", "category": "database"},
    "PQexecParams": {"lib": "libpq", "purpose": "execute parameterized SQL", "category": "database"},
    "PQprepare": {"lib": "libpq", "purpose": "prepare named statement", "category": "database"},
    "PQexecPrepared": {"lib": "libpq", "purpose": "execute prepared statement", "category": "database"},
    "PQresultStatus": {"lib": "libpq", "purpose": "get command result status", "category": "database"},
    "PQntuples": {"lib": "libpq", "purpose": "get number of result rows", "category": "database"},
    "PQnfields": {"lib": "libpq", "purpose": "get number of result columns", "category": "database"},
    "PQgetvalue": {"lib": "libpq", "purpose": "get field value as string", "category": "database"},
    "PQgetisnull": {"lib": "libpq", "purpose": "check if field is NULL", "category": "database"},
    "PQfname": {"lib": "libpq", "purpose": "get column name", "category": "database"},
    "PQftype": {"lib": "libpq", "purpose": "get column type OID", "category": "database"},
    "PQclear": {"lib": "libpq", "purpose": "free result object", "category": "database"},
    "PQescapeStringConn": {"lib": "libpq", "purpose": "escape string for SQL", "category": "database"},
    "PQescapeLiteral": {"lib": "libpq", "purpose": "escape string as SQL literal", "category": "database"},
    "PQsendQuery": {"lib": "libpq", "purpose": "send async query", "category": "database"},
    "PQgetResult": {"lib": "libpq", "purpose": "get async query result", "category": "database"},
    "PQsetnonblocking": {"lib": "libpq", "purpose": "set non-blocking mode", "category": "database"},
    "PQsocket": {"lib": "libpq", "purpose": "get connection socket fd", "category": "database"},
    "PQconsumeInput": {"lib": "libpq", "purpose": "consume input from server", "category": "database"},
    "PQnotifies": {"lib": "libpq", "purpose": "get NOTIFY message", "category": "database"},

    # --- Redis (hiredis) ---
    "redisConnect": {"lib": "hiredis", "purpose": "connect to Redis server", "category": "database"},
    "redisConnectWithTimeout": {"lib": "hiredis", "purpose": "connect to Redis with timeout", "category": "database"},
    "redisFree": {"lib": "hiredis", "purpose": "free Redis connection", "category": "database"},
    "redisCommand": {"lib": "hiredis", "purpose": "execute Redis command", "category": "database"},
    "redisCommandArgv": {"lib": "hiredis", "purpose": "execute Redis command (argv)", "category": "database"},
    "redisAppendCommand": {"lib": "hiredis", "purpose": "append command to pipeline", "category": "database"},
    "redisGetReply": {"lib": "hiredis", "purpose": "get pipelined reply", "category": "database"},
    "freeReplyObject": {"lib": "hiredis", "purpose": "free Redis reply object", "category": "database"},
    "redisAsyncConnect": {"lib": "hiredis", "purpose": "async connect to Redis", "category": "database"},
    "redisAsyncCommand": {"lib": "hiredis", "purpose": "execute async Redis command", "category": "database"},
    "redisAsyncFree": {"lib": "hiredis", "purpose": "free async Redis context", "category": "database"},

    # --- LMDB (Lightning Memory-Mapped DB) ---
    "mdb_env_create": {"lib": "lmdb", "purpose": "create LMDB environment", "category": "database"},
    "mdb_env_open": {"lib": "lmdb", "purpose": "open LMDB environment", "category": "database"},
    "mdb_env_close": {"lib": "lmdb", "purpose": "close LMDB environment", "category": "database"},
    "mdb_txn_begin": {"lib": "lmdb", "purpose": "begin LMDB transaction", "category": "database"},
    "mdb_txn_commit": {"lib": "lmdb", "purpose": "commit LMDB transaction", "category": "database"},
    "mdb_txn_abort": {"lib": "lmdb", "purpose": "abort LMDB transaction", "category": "database"},
    "mdb_dbi_open": {"lib": "lmdb", "purpose": "open LMDB database", "category": "database"},
    "mdb_put": {"lib": "lmdb", "purpose": "put key-value pair", "category": "database"},
    "mdb_get": {"lib": "lmdb", "purpose": "get value by key", "category": "database"},
    "mdb_del": {"lib": "lmdb", "purpose": "delete key-value pair", "category": "database"},
    "mdb_cursor_open": {"lib": "lmdb", "purpose": "open database cursor", "category": "database"},
    "mdb_cursor_get": {"lib": "lmdb", "purpose": "get data at cursor position", "category": "database"},
    "mdb_cursor_put": {"lib": "lmdb", "purpose": "put data at cursor position", "category": "database"},
    "mdb_cursor_del": {"lib": "lmdb", "purpose": "delete at cursor position", "category": "database"},
    "mdb_cursor_close": {"lib": "lmdb", "purpose": "close database cursor", "category": "database"},

    # --- LevelDB ---
    "leveldb_open": {"lib": "leveldb", "purpose": "open LevelDB database", "category": "database"},
    "leveldb_close": {"lib": "leveldb", "purpose": "close LevelDB database", "category": "database"},
    "leveldb_put": {"lib": "leveldb", "purpose": "put key-value pair", "category": "database"},
    "leveldb_get": {"lib": "leveldb", "purpose": "get value by key", "category": "database"},
    "leveldb_delete": {"lib": "leveldb", "purpose": "delete key", "category": "database"},
    "leveldb_write": {"lib": "leveldb", "purpose": "write batch of operations", "category": "database"},
    "leveldb_create_iterator": {"lib": "leveldb", "purpose": "create database iterator", "category": "database"},
    "leveldb_iter_seek_to_first": {"lib": "leveldb", "purpose": "seek iterator to first entry", "category": "database"},
    "leveldb_iter_next": {"lib": "leveldb", "purpose": "advance iterator", "category": "database"},
    "leveldb_iter_key": {"lib": "leveldb", "purpose": "get current iterator key", "category": "database"},
    "leveldb_iter_value": {"lib": "leveldb", "purpose": "get current iterator value", "category": "database"},
    "leveldb_iter_valid": {"lib": "leveldb", "purpose": "check if iterator is valid", "category": "database"},
    "leveldb_iter_destroy": {"lib": "leveldb", "purpose": "destroy iterator", "category": "database"},
    "leveldb_writebatch_create": {"lib": "leveldb", "purpose": "create write batch", "category": "database"},
    "leveldb_writebatch_put": {"lib": "leveldb", "purpose": "add put to batch", "category": "database"},
    "leveldb_writebatch_delete": {"lib": "leveldb", "purpose": "add delete to batch", "category": "database"},
    "leveldb_writebatch_destroy": {"lib": "leveldb", "purpose": "destroy write batch", "category": "database"},
}


# ---------------------------------------------------------------------------
# protobuf (86 entry, 87 literal) — Google Protocol Buffers C++ API. Namespace'li ("google::protobuf::...") ve Itanium-mangled (_ZN6google8protobuf...) isimler birlikte tutulur. Bu yapi _PROTOBUF_BASENAME_INDEX (signature_db.py) icin gereklidir; "::"-li isimlerden basename -> (full, info) index uretilir.
# Kaynak: signature_db.py satir 731-822.
# ---------------------------------------------------------------------------
_PROTOBUF_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # C++ API (mangled names usually, but symbol table may demangle)
    "google::protobuf::MessageLite::SerializeToString": {"lib": "protobuf", "purpose": "serialize message to string", "category": "serialization"},
    "google::protobuf::MessageLite::ParseFromString": {"lib": "protobuf", "purpose": "parse message from string", "category": "serialization"},
    "google::protobuf::MessageLite::SerializeToArray": {"lib": "protobuf", "purpose": "serialize to byte array", "category": "serialization"},
    "google::protobuf::MessageLite::ParseFromArray": {"lib": "protobuf", "purpose": "parse from byte array", "category": "serialization"},
    "google::protobuf::MessageLite::ByteSizeLong": {"lib": "protobuf", "purpose": "compute serialized size", "category": "serialization"},
    "google::protobuf::MessageLite::MergeFromString": {"lib": "protobuf", "purpose": "merge from serialized", "category": "serialization"},
    "google::protobuf::MessageLite::SerializeWithCachedSizesToArray": {"lib": "protobuf", "purpose": "serialize with cached sizes", "category": "serialization"},
    "google::protobuf::Message::DebugString": {"lib": "protobuf", "purpose": "message debug string", "category": "serialization"},
    "google::protobuf::Message::ShortDebugString": {"lib": "protobuf", "purpose": "message short debug", "category": "serialization"},
    "google::protobuf::Message::CopyFrom": {"lib": "protobuf", "purpose": "copy message", "category": "serialization"},
    "google::protobuf::Message::MergeFrom": {"lib": "protobuf", "purpose": "merge message", "category": "serialization"},
    "google::protobuf::Message::Clear": {"lib": "protobuf", "purpose": "clear message fields", "category": "serialization"},
    "google::protobuf::Message::IsInitialized": {"lib": "protobuf", "purpose": "check required fields", "category": "serialization"},
    "google::protobuf::Message::GetDescriptor": {"lib": "protobuf", "purpose": "message descriptor", "category": "serialization"},
    "google::protobuf::Message::GetReflection": {"lib": "protobuf", "purpose": "message reflection", "category": "serialization"},
    "google::protobuf::DescriptorPool::FindFileByName": {"lib": "protobuf", "purpose": "find proto file", "category": "serialization"},
    "google::protobuf::DescriptorPool::FindMessageTypeByName": {"lib": "protobuf", "purpose": "find message type", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteVarint32": {"lib": "protobuf", "purpose": "write varint32", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteVarint64": {"lib": "protobuf", "purpose": "write varint64", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteTag": {"lib": "protobuf", "purpose": "write field tag", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteLittleEndian32": {"lib": "protobuf", "purpose": "write LE 32-bit", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteLittleEndian64": {"lib": "protobuf", "purpose": "write LE 64-bit", "category": "serialization"},
    "google::protobuf::io::CodedOutputStream::WriteString": {"lib": "protobuf", "purpose": "write length-delimited string", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadVarint32": {"lib": "protobuf", "purpose": "read varint32", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadVarint64": {"lib": "protobuf", "purpose": "read varint64", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadTag": {"lib": "protobuf", "purpose": "read field tag", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadLittleEndian32": {"lib": "protobuf", "purpose": "read LE 32-bit", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadLittleEndian64": {"lib": "protobuf", "purpose": "read LE 64-bit", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::ReadString": {"lib": "protobuf", "purpose": "read length-delimited string", "category": "serialization"},
    "google::protobuf::io::CodedInputStream::Skip": {"lib": "protobuf", "purpose": "skip bytes", "category": "serialization"},
    "google::protobuf::io::ZeroCopyOutputStream::Next": {"lib": "protobuf", "purpose": "zero-copy output next", "category": "serialization"},
    "google::protobuf::io::ZeroCopyInputStream::Next": {"lib": "protobuf", "purpose": "zero-copy input next", "category": "serialization"},
    "google::protobuf::Arena::CreateMessage": {"lib": "protobuf", "purpose": "arena-allocated message", "category": "serialization"},
    "google::protobuf::Arena::~Arena": {"lib": "protobuf", "purpose": "arena destruction", "category": "serialization"},
    "google::protobuf::Map": {"lib": "protobuf", "purpose": "protobuf map field", "category": "serialization"},
    "google::protobuf::RepeatedField": {"lib": "protobuf", "purpose": "protobuf repeated field", "category": "serialization"},
    "google::protobuf::RepeatedPtrField": {"lib": "protobuf", "purpose": "protobuf repeated ptr field", "category": "serialization"},
    "google::protobuf::internal::WireFormatLite::WriteBytes": {"lib": "protobuf", "purpose": "wire format write bytes", "category": "serialization"},
    "google::protobuf::internal::WireFormatLite::ReadBytes": {"lib": "protobuf", "purpose": "wire format read bytes", "category": "serialization"},
    "google::protobuf::internal::ArenaStringPtr::Set": {"lib": "protobuf", "purpose": "arena string set", "category": "serialization"},
    "google::protobuf::internal::ArenaStringPtr::Get": {"lib": "protobuf", "purpose": "arena string get", "category": "serialization"},
    # Mangled C++ name versions (as seen in stripped binaries)
    "_ZN6google8protobuf7MessageC1Ev": {"lib": "protobuf", "purpose": "Message default constructor", "category": "serialization"},
    "_ZN6google8protobuf7MessageC2Ev": {"lib": "protobuf", "purpose": "Message base constructor", "category": "serialization"},
    "_ZN6google8protobuf7MessageD0Ev": {"lib": "protobuf", "purpose": "Message deleting destructor", "category": "serialization"},
    "_ZN6google8protobuf7MessageD1Ev": {"lib": "protobuf", "purpose": "Message complete destructor", "category": "serialization"},
    "_ZN6google8protobuf7Message5ClearEv": {"lib": "protobuf", "purpose": "Message::Clear()", "category": "serialization"},
    "_ZN6google8protobuf7Message9MergeFromERKS1_": {"lib": "protobuf", "purpose": "Message::MergeFrom()", "category": "serialization"},
    "_ZN6google8protobuf7Message8CopyFromERKS1_": {"lib": "protobuf", "purpose": "Message::CopyFrom()", "category": "serialization"},
    "_ZN6google8protobuf7Message11ByteSizeLongEv": {"lib": "protobuf", "purpose": "Message::ByteSizeLong()", "category": "serialization"},
    "_ZN6google8protobuf7Message13IsInitializedEv": {"lib": "protobuf", "purpose": "Message::IsInitialized()", "category": "serialization"},
    "_ZN6google8protobuf11MessageLite18SerializeToStringEPNSt": {"lib": "protobuf", "purpose": "MessageLite::SerializeToString()", "category": "serialization"},
    "_ZN6google8protobuf11MessageLite16ParseFromStringERKNSt": {"lib": "protobuf", "purpose": "MessageLite::ParseFromString()", "category": "serialization"},
    "_ZN6google8protobuf11MessageLite17SerializeToArrayEPhi": {"lib": "protobuf", "purpose": "MessageLite::SerializeToArray()", "category": "serialization"},
    "_ZN6google8protobuf11MessageLite14ParseFromArrayEPKvi": {"lib": "protobuf", "purpose": "MessageLite::ParseFromArray()", "category": "serialization"},
    "_ZN6google8protobuf11MessageLite15MergeFromStringERKNSt": {"lib": "protobuf", "purpose": "MessageLite::MergeFromString()", "category": "serialization"},
    "_ZN6google8protobuf10ReflectionC": {"lib": "protobuf", "purpose": "Reflection constructor", "category": "serialization"},
    "_ZN6google8protobuf10Reflection": {"lib": "protobuf", "purpose": "Reflection methods", "category": "serialization"},
    "_ZN6google8protobuf10DescriptorE": {"lib": "protobuf", "purpose": "Descriptor operations", "category": "serialization"},
    "_ZN6google8protobuf14DescriptorPool": {"lib": "protobuf", "purpose": "DescriptorPool operations", "category": "serialization"},
    "_ZN6google8protobuf2io16CodedOutputStream": {"lib": "protobuf", "purpose": "CodedOutputStream operations", "category": "serialization"},
    "_ZN6google8protobuf2io15CodedInputStream": {"lib": "protobuf", "purpose": "CodedInputStream operations", "category": "serialization"},
    "_ZN6google8protobuf2io20ZeroCopyOutputStream": {"lib": "protobuf", "purpose": "ZeroCopyOutputStream operations", "category": "serialization"},
    "_ZN6google8protobuf2io19ZeroCopyInputStream": {"lib": "protobuf", "purpose": "ZeroCopyInputStream operations", "category": "serialization"},
    "_ZN6google8protobuf5Arena13CreateMessageE": {"lib": "protobuf", "purpose": "Arena::CreateMessage()", "category": "serialization"},
    "_ZN6google8protobuf5ArenaD": {"lib": "protobuf", "purpose": "Arena destructor", "category": "serialization"},
    "_ZN6google8protobuf5Arena10CreateMaybeE": {"lib": "protobuf", "purpose": "Arena::CreateMaybe()", "category": "serialization"},
    "_ZN6google8protobuf5Arena17CreateMaybeMessageE": {"lib": "protobuf", "purpose": "Arena::CreateMaybeMessage()", "category": "serialization"},
    "_ZN6google8protobuf8internal14WireFormatLite": {"lib": "protobuf", "purpose": "WireFormatLite operations", "category": "serialization"},
    "_ZN6google8protobuf8internal12MapFieldBase": {"lib": "protobuf", "purpose": "MapFieldBase operations", "category": "serialization"},
    "_ZN6google8protobuf8internal13RepeatedField": {"lib": "protobuf", "purpose": "RepeatedField operations", "category": "serialization"},
    # Additional demangled names for common protobuf symbols
    "google::protobuf::MessageLite::SerializeAsString": {"lib": "protobuf", "purpose": "serialize message as string", "category": "serialization"},
    "google::protobuf::MessageLite::AppendToString": {"lib": "protobuf", "purpose": "append serialized to string", "category": "serialization"},
    "google::protobuf::MessageLite::ParsePartialFromString": {"lib": "protobuf", "purpose": "partial parse from string", "category": "serialization"},
    "google::protobuf::MessageLite::ParsePartialFromArray": {"lib": "protobuf", "purpose": "partial parse from array", "category": "serialization"},
    "google::protobuf::Message::DebugString": {"lib": "protobuf", "purpose": "message debug string", "category": "serialization"},
    "google::protobuf::Message::Utf8DebugString": {"lib": "protobuf", "purpose": "message UTF-8 debug string", "category": "serialization"},
    "google::protobuf::Message::FindInitializationErrors": {"lib": "protobuf", "purpose": "find unset required fields", "category": "serialization"},
    "google::protobuf::Message::InitializationErrorString": {"lib": "protobuf", "purpose": "list unset required fields", "category": "serialization"},
    "google::protobuf::Message::SpaceUsedLong": {"lib": "protobuf", "purpose": "memory usage of message", "category": "serialization"},
    "google::protobuf::Arena::Init": {"lib": "protobuf", "purpose": "arena init", "category": "serialization"},
    "google::protobuf::Arena::Reset": {"lib": "protobuf", "purpose": "arena reset (free all)", "category": "serialization"},
    "google::protobuf::Arena::SpaceUsed": {"lib": "protobuf", "purpose": "arena memory usage", "category": "serialization"},
    "google::protobuf::Arena::SpaceAllocated": {"lib": "protobuf", "purpose": "arena total allocated", "category": "serialization"},
    "google::protobuf::TextFormat::PrintToString": {"lib": "protobuf", "purpose": "text format serialize", "category": "serialization"},
    "google::protobuf::TextFormat::ParseFromString": {"lib": "protobuf", "purpose": "text format parse", "category": "serialization"},
    "google::protobuf::util::JsonStringToMessage": {"lib": "protobuf", "purpose": "JSON to protobuf conversion", "category": "serialization"},
    "google::protobuf::util::MessageToJsonString": {"lib": "protobuf", "purpose": "protobuf to JSON conversion", "category": "serialization"},
}


# ---------------------------------------------------------------------------
# json (116 entry) — cJSON, yyjson, jansson C API'leri.
# Kaynak: signature_db.py satir 1014-1134.
# ---------------------------------------------------------------------------
_JSON_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # --- cJSON ---
    "_cJSON_Parse": {"lib": "cJSON", "purpose": "parse JSON string", "category": "serialization"},
    "_cJSON_ParseWithLength": {"lib": "cJSON", "purpose": "parse JSON with length", "category": "serialization"},
    "_cJSON_Delete": {"lib": "cJSON", "purpose": "delete JSON tree", "category": "serialization"},
    "_cJSON_Print": {"lib": "cJSON", "purpose": "print JSON (formatted)", "category": "serialization"},
    "_cJSON_PrintUnformatted": {"lib": "cJSON", "purpose": "print JSON (compact)", "category": "serialization"},
    "_cJSON_PrintBuffered": {"lib": "cJSON", "purpose": "print JSON to preallocated buffer", "category": "serialization"},
    "_cJSON_CreateObject": {"lib": "cJSON", "purpose": "create JSON object", "category": "serialization"},
    "_cJSON_CreateArray": {"lib": "cJSON", "purpose": "create JSON array", "category": "serialization"},
    "_cJSON_CreateString": {"lib": "cJSON", "purpose": "create JSON string", "category": "serialization"},
    "_cJSON_CreateNumber": {"lib": "cJSON", "purpose": "create JSON number", "category": "serialization"},
    "_cJSON_CreateBool": {"lib": "cJSON", "purpose": "create JSON boolean", "category": "serialization"},
    "_cJSON_CreateNull": {"lib": "cJSON", "purpose": "create JSON null", "category": "serialization"},
    "_cJSON_CreateTrue": {"lib": "cJSON", "purpose": "create JSON true", "category": "serialization"},
    "_cJSON_CreateFalse": {"lib": "cJSON", "purpose": "create JSON false", "category": "serialization"},
    "_cJSON_CreateIntArray": {"lib": "cJSON", "purpose": "create JSON int array", "category": "serialization"},
    "_cJSON_CreateFloatArray": {"lib": "cJSON", "purpose": "create JSON float array", "category": "serialization"},
    "_cJSON_CreateStringArray": {"lib": "cJSON", "purpose": "create JSON string array", "category": "serialization"},
    "_cJSON_AddItemToObject": {"lib": "cJSON", "purpose": "add item to JSON object", "category": "serialization"},
    "_cJSON_AddItemToArray": {"lib": "cJSON", "purpose": "add item to JSON array", "category": "serialization"},
    "_cJSON_AddItemReferenceToObject": {"lib": "cJSON", "purpose": "add reference to JSON object", "category": "serialization"},
    "_cJSON_AddItemReferenceToArray": {"lib": "cJSON", "purpose": "add reference to JSON array", "category": "serialization"},
    "_cJSON_DetachItemFromObject": {"lib": "cJSON", "purpose": "detach item from JSON object", "category": "serialization"},
    "_cJSON_DetachItemFromArray": {"lib": "cJSON", "purpose": "detach item from JSON array", "category": "serialization"},
    "_cJSON_DeleteItemFromObject": {"lib": "cJSON", "purpose": "delete item from JSON object", "category": "serialization"},
    "_cJSON_DeleteItemFromArray": {"lib": "cJSON", "purpose": "delete item from JSON array", "category": "serialization"},
    "_cJSON_GetObjectItem": {"lib": "cJSON", "purpose": "get JSON object member", "category": "serialization"},
    "_cJSON_GetObjectItemCaseSensitive": {"lib": "cJSON", "purpose": "get JSON object member (case-sensitive)", "category": "serialization"},
    "_cJSON_GetArrayItem": {"lib": "cJSON", "purpose": "get JSON array element", "category": "serialization"},
    "_cJSON_GetArraySize": {"lib": "cJSON", "purpose": "get JSON array length", "category": "serialization"},
    "_cJSON_HasObjectItem": {"lib": "cJSON", "purpose": "check JSON object has key", "category": "serialization"},
    "_cJSON_IsObject": {"lib": "cJSON", "purpose": "check if JSON object", "category": "serialization"},
    "_cJSON_IsArray": {"lib": "cJSON", "purpose": "check if JSON array", "category": "serialization"},
    "_cJSON_IsString": {"lib": "cJSON", "purpose": "check if JSON string", "category": "serialization"},
    "_cJSON_IsNumber": {"lib": "cJSON", "purpose": "check if JSON number", "category": "serialization"},
    "_cJSON_IsBool": {"lib": "cJSON", "purpose": "check if JSON boolean", "category": "serialization"},
    "_cJSON_IsNull": {"lib": "cJSON", "purpose": "check if JSON null", "category": "serialization"},
    "_cJSON_IsTrue": {"lib": "cJSON", "purpose": "check if JSON true", "category": "serialization"},
    "_cJSON_IsFalse": {"lib": "cJSON", "purpose": "check if JSON false", "category": "serialization"},
    "_cJSON_IsInvalid": {"lib": "cJSON", "purpose": "check if JSON invalid", "category": "serialization"},
    "_cJSON_Duplicate": {"lib": "cJSON", "purpose": "deep copy JSON tree", "category": "serialization"},
    "_cJSON_Compare": {"lib": "cJSON", "purpose": "compare two JSON trees", "category": "serialization"},
    "_cJSON_ReplaceItemInObject": {"lib": "cJSON", "purpose": "replace item in JSON object", "category": "serialization"},
    "_cJSON_ReplaceItemInArray": {"lib": "cJSON", "purpose": "replace item in JSON array", "category": "serialization"},
    "_cJSON_AddNumberToObject": {"lib": "cJSON", "purpose": "add number to JSON object", "category": "serialization"},
    "_cJSON_AddStringToObject": {"lib": "cJSON", "purpose": "add string to JSON object", "category": "serialization"},
    "_cJSON_AddBoolToObject": {"lib": "cJSON", "purpose": "add bool to JSON object", "category": "serialization"},
    "_cJSON_AddNullToObject": {"lib": "cJSON", "purpose": "add null to JSON object", "category": "serialization"},
    "_cJSON_SetValuestring": {"lib": "cJSON", "purpose": "set JSON string value", "category": "serialization"},
    "_cJSON_SetNumberHelper": {"lib": "cJSON", "purpose": "set JSON number value", "category": "serialization"},
    "_cJSON_Version": {"lib": "cJSON", "purpose": "cJSON version string", "category": "info"},
    "_cJSON_Minify": {"lib": "cJSON", "purpose": "minify JSON string in-place", "category": "serialization"},
    # --- yyjson ---
    "_yyjson_read": {"lib": "yyjson", "purpose": "parse JSON (immutable)", "category": "serialization"},
    "_yyjson_read_opts": {"lib": "yyjson", "purpose": "parse JSON with options", "category": "serialization"},
    "_yyjson_read_file": {"lib": "yyjson", "purpose": "parse JSON from file", "category": "serialization"},
    "_yyjson_write": {"lib": "yyjson", "purpose": "serialize JSON to string", "category": "serialization"},
    "_yyjson_write_opts": {"lib": "yyjson", "purpose": "serialize JSON with options", "category": "serialization"},
    "_yyjson_write_file": {"lib": "yyjson", "purpose": "serialize JSON to file", "category": "serialization"},
    "_yyjson_doc_free": {"lib": "yyjson", "purpose": "free JSON document", "category": "serialization"},
    "_yyjson_doc_get_root": {"lib": "yyjson", "purpose": "get JSON document root", "category": "serialization"},
    "_yyjson_mut_doc_new": {"lib": "yyjson", "purpose": "create mutable JSON document", "category": "serialization"},
    "_yyjson_mut_doc_free": {"lib": "yyjson", "purpose": "free mutable JSON document", "category": "serialization"},
    "_yyjson_mut_write": {"lib": "yyjson", "purpose": "serialize mutable JSON", "category": "serialization"},
    "_yyjson_val_get_type": {"lib": "yyjson", "purpose": "get JSON value type", "category": "serialization"},
    "_yyjson_obj_get": {"lib": "yyjson", "purpose": "get object member by key", "category": "serialization"},
    "_yyjson_arr_get": {"lib": "yyjson", "purpose": "get array element by index", "category": "serialization"},
    "_yyjson_get_str": {"lib": "yyjson", "purpose": "get string value", "category": "serialization"},
    "_yyjson_get_int": {"lib": "yyjson", "purpose": "get integer value", "category": "serialization"},
    "_yyjson_get_real": {"lib": "yyjson", "purpose": "get double value", "category": "serialization"},
    "_yyjson_get_bool": {"lib": "yyjson", "purpose": "get boolean value", "category": "serialization"},
    # --- jansson ---
    "_json_loads": {"lib": "jansson", "purpose": "parse JSON string", "category": "serialization"},
    "_json_loadb": {"lib": "jansson", "purpose": "parse JSON buffer", "category": "serialization"},
    "_json_loadf": {"lib": "jansson", "purpose": "parse JSON from FILE*", "category": "serialization"},
    "_json_load_file": {"lib": "jansson", "purpose": "parse JSON from file path", "category": "serialization"},
    "_json_dumps": {"lib": "jansson", "purpose": "serialize JSON to string", "category": "serialization"},
    "_json_dumpf": {"lib": "jansson", "purpose": "serialize JSON to FILE*", "category": "serialization"},
    "_json_dump_file": {"lib": "jansson", "purpose": "serialize JSON to file path", "category": "serialization"},
    "_json_object": {"lib": "jansson", "purpose": "create JSON object", "category": "serialization"},
    "_json_array": {"lib": "jansson", "purpose": "create JSON array", "category": "serialization"},
    "_json_string": {"lib": "jansson", "purpose": "create JSON string", "category": "serialization"},
    "_json_stringn": {"lib": "jansson", "purpose": "create JSON string (with length)", "category": "serialization"},
    "_json_integer": {"lib": "jansson", "purpose": "create JSON integer", "category": "serialization"},
    "_json_real": {"lib": "jansson", "purpose": "create JSON real", "category": "serialization"},
    "_json_true": {"lib": "jansson", "purpose": "create JSON true", "category": "serialization"},
    "_json_false": {"lib": "jansson", "purpose": "create JSON false", "category": "serialization"},
    "_json_null": {"lib": "jansson", "purpose": "create JSON null", "category": "serialization"},
    "_json_object_get": {"lib": "jansson", "purpose": "get JSON object member", "category": "serialization"},
    "_json_object_set_new": {"lib": "jansson", "purpose": "set JSON object member (steal ref)", "category": "serialization"},
    "_json_object_set": {"lib": "jansson", "purpose": "set JSON object member", "category": "serialization"},
    "_json_object_del": {"lib": "jansson", "purpose": "delete JSON object member", "category": "serialization"},
    "_json_object_size": {"lib": "jansson", "purpose": "get JSON object size", "category": "serialization"},
    "_json_object_iter": {"lib": "jansson", "purpose": "JSON object iterator begin", "category": "serialization"},
    "_json_object_iter_next": {"lib": "jansson", "purpose": "JSON object iterator next", "category": "serialization"},
    "_json_object_iter_key": {"lib": "jansson", "purpose": "JSON object iterator key", "category": "serialization"},
    "_json_object_iter_value": {"lib": "jansson", "purpose": "JSON object iterator value", "category": "serialization"},
    "_json_array_get": {"lib": "jansson", "purpose": "get JSON array element", "category": "serialization"},
    "_json_array_append_new": {"lib": "jansson", "purpose": "append to JSON array (steal ref)", "category": "serialization"},
    "_json_array_append": {"lib": "jansson", "purpose": "append to JSON array", "category": "serialization"},
    "_json_array_size": {"lib": "jansson", "purpose": "get JSON array length", "category": "serialization"},
    "_json_array_insert_new": {"lib": "jansson", "purpose": "insert into JSON array (steal ref)", "category": "serialization"},
    "_json_array_remove": {"lib": "jansson", "purpose": "remove from JSON array", "category": "serialization"},
    "_json_decref": {"lib": "jansson", "purpose": "decrement JSON reference count", "category": "serialization"},
    "_json_incref": {"lib": "jansson", "purpose": "increment JSON reference count", "category": "serialization"},
    "_json_deep_copy": {"lib": "jansson", "purpose": "deep copy JSON value", "category": "serialization"},
    "_json_equal": {"lib": "jansson", "purpose": "compare JSON values", "category": "serialization"},
    "_json_string_value": {"lib": "jansson", "purpose": "get string from JSON string", "category": "serialization"},
    "_json_integer_value": {"lib": "jansson", "purpose": "get int from JSON integer", "category": "serialization"},
    "_json_real_value": {"lib": "jansson", "purpose": "get double from JSON real", "category": "serialization"},
    "_json_number_value": {"lib": "jansson", "purpose": "get number as double", "category": "serialization"},
    "_json_is_object": {"lib": "jansson", "purpose": "check if JSON object", "category": "serialization"},
    "_json_is_array": {"lib": "jansson", "purpose": "check if JSON array", "category": "serialization"},
    "_json_is_string": {"lib": "jansson", "purpose": "check if JSON string", "category": "serialization"},
    "_json_is_integer": {"lib": "jansson", "purpose": "check if JSON integer", "category": "serialization"},
    "_json_is_real": {"lib": "jansson", "purpose": "check if JSON real", "category": "serialization"},
    "_json_is_true": {"lib": "jansson", "purpose": "check if JSON true", "category": "serialization"},
    "_json_is_false": {"lib": "jansson", "purpose": "check if JSON false", "category": "serialization"},
    "_json_is_null": {"lib": "jansson", "purpose": "check if JSON null", "category": "serialization"},
}


# ---------------------------------------------------------------------------
# xml (93 entry) — libxml2 (parsing, tree, XPath, SAX, namespace) + expat C API.
# Kaynak: signature_db.py satir 1141-1246.
# ---------------------------------------------------------------------------
_XML_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # --- libxml2: Parsing ---
    "_xmlReadMemory": {"lib": "libxml2", "purpose": "parse XML from memory", "category": "serialization"},
    "_xmlReadFile": {"lib": "libxml2", "purpose": "parse XML from file", "category": "serialization"},
    "_xmlReadDoc": {"lib": "libxml2", "purpose": "parse XML from string", "category": "serialization"},
    "_xmlReadFd": {"lib": "libxml2", "purpose": "parse XML from fd", "category": "serialization"},
    "_xmlReadIO": {"lib": "libxml2", "purpose": "parse XML from I/O callbacks", "category": "serialization"},
    "_xmlCtxtReadMemory": {"lib": "libxml2", "purpose": "parse XML from memory with context", "category": "serialization"},
    "_xmlCtxtReadFile": {"lib": "libxml2", "purpose": "parse XML from file with context", "category": "serialization"},
    "_xmlParseMemory": {"lib": "libxml2", "purpose": "parse XML from memory (legacy)", "category": "serialization"},
    "_xmlParseFile": {"lib": "libxml2", "purpose": "parse XML from file (legacy)", "category": "serialization"},
    "_xmlParseDoc": {"lib": "libxml2", "purpose": "parse XML from string (legacy)", "category": "serialization"},
    # --- libxml2: Document/tree ---
    "_xmlFreeDoc": {"lib": "libxml2", "purpose": "free XML document", "category": "serialization"},
    "_xmlDocGetRootElement": {"lib": "libxml2", "purpose": "get root element", "category": "serialization"},
    "_xmlDocSetRootElement": {"lib": "libxml2", "purpose": "set root element", "category": "serialization"},
    "_xmlNewDoc": {"lib": "libxml2", "purpose": "create new XML document", "category": "serialization"},
    "_xmlCopyDoc": {"lib": "libxml2", "purpose": "copy XML document", "category": "serialization"},
    # --- libxml2: Nodes ---
    "_xmlNewNode": {"lib": "libxml2", "purpose": "create XML element node", "category": "serialization"},
    "_xmlNewText": {"lib": "libxml2", "purpose": "create XML text node", "category": "serialization"},
    "_xmlNewComment": {"lib": "libxml2", "purpose": "create XML comment node", "category": "serialization"},
    "_xmlNewCDataBlock": {"lib": "libxml2", "purpose": "create XML CDATA node", "category": "serialization"},
    "_xmlNewPI": {"lib": "libxml2", "purpose": "create XML processing instruction", "category": "serialization"},
    "_xmlAddChild": {"lib": "libxml2", "purpose": "add child node", "category": "serialization"},
    "_xmlAddNextSibling": {"lib": "libxml2", "purpose": "add next sibling node", "category": "serialization"},
    "_xmlAddPrevSibling": {"lib": "libxml2", "purpose": "add previous sibling node", "category": "serialization"},
    "_xmlUnlinkNode": {"lib": "libxml2", "purpose": "unlink node from tree", "category": "serialization"},
    "_xmlFreeNode": {"lib": "libxml2", "purpose": "free XML node", "category": "serialization"},
    "_xmlCopyNode": {"lib": "libxml2", "purpose": "copy XML node", "category": "serialization"},
    "_xmlNodeGetContent": {"lib": "libxml2", "purpose": "get node text content", "category": "serialization"},
    "_xmlNodeSetContent": {"lib": "libxml2", "purpose": "set node text content", "category": "serialization"},
    "_xmlNodeListGetString": {"lib": "libxml2", "purpose": "get node list as string", "category": "serialization"},
    # --- libxml2: Attributes ---
    "_xmlGetProp": {"lib": "libxml2", "purpose": "get XML attribute value", "category": "serialization"},
    "_xmlSetProp": {"lib": "libxml2", "purpose": "set XML attribute", "category": "serialization"},
    "_xmlNewProp": {"lib": "libxml2", "purpose": "create XML attribute", "category": "serialization"},
    "_xmlHasProp": {"lib": "libxml2", "purpose": "check XML attribute exists", "category": "serialization"},
    "_xmlRemoveProp": {"lib": "libxml2", "purpose": "remove XML attribute", "category": "serialization"},
    # --- libxml2: Serialization ---
    "_xmlSaveFormatFile": {"lib": "libxml2", "purpose": "save XML to file (formatted)", "category": "serialization"},
    "_xmlSaveFile": {"lib": "libxml2", "purpose": "save XML to file", "category": "serialization"},
    "_xmlDocDumpMemory": {"lib": "libxml2", "purpose": "dump XML doc to memory", "category": "serialization"},
    "_xmlDocDumpFormatMemory": {"lib": "libxml2", "purpose": "dump XML doc to memory (formatted)", "category": "serialization"},
    "_xmlNodeDump": {"lib": "libxml2", "purpose": "dump XML node to buffer", "category": "serialization"},
    "_xmlBufferCreate": {"lib": "libxml2", "purpose": "create XML buffer", "category": "serialization"},
    "_xmlBufferFree": {"lib": "libxml2", "purpose": "free XML buffer", "category": "serialization"},
    "_xmlBufferContent": {"lib": "libxml2", "purpose": "get XML buffer content", "category": "serialization"},
    # --- libxml2: Namespaces ---
    "_xmlNewNs": {"lib": "libxml2", "purpose": "create XML namespace", "category": "serialization"},
    "_xmlSearchNs": {"lib": "libxml2", "purpose": "search XML namespace", "category": "serialization"},
    "_xmlSearchNsByHref": {"lib": "libxml2", "purpose": "search namespace by URI", "category": "serialization"},
    # --- libxml2: XPath ---
    "_xmlXPathNewContext": {"lib": "libxml2", "purpose": "create XPath context", "category": "serialization"},
    "_xmlXPathFreeContext": {"lib": "libxml2", "purpose": "free XPath context", "category": "serialization"},
    "_xmlXPathEvalExpression": {"lib": "libxml2", "purpose": "evaluate XPath expression", "category": "serialization"},
    "_xmlXPathEval": {"lib": "libxml2", "purpose": "evaluate XPath expression (alt)", "category": "serialization"},
    "_xmlXPathFreeObject": {"lib": "libxml2", "purpose": "free XPath result object", "category": "serialization"},
    "_xmlXPathRegisterNs": {"lib": "libxml2", "purpose": "register XPath namespace", "category": "serialization"},
    "_xmlXPathCompile": {"lib": "libxml2", "purpose": "compile XPath expression", "category": "serialization"},
    "_xmlXPathCompiledEval": {"lib": "libxml2", "purpose": "evaluate compiled XPath", "category": "serialization"},
    "_xmlXPathFreeCompExpr": {"lib": "libxml2", "purpose": "free compiled XPath", "category": "serialization"},
    # --- libxml2: SAX/Push parser ---
    "_xmlCreatePushParserCtxt": {"lib": "libxml2", "purpose": "create push parser context", "category": "serialization"},
    "_xmlParseChunk": {"lib": "libxml2", "purpose": "parse XML chunk (push)", "category": "serialization"},
    "_xmlFreeParserCtxt": {"lib": "libxml2", "purpose": "free parser context", "category": "serialization"},
    # --- libxml2: Cleanup/init ---
    "_xmlCleanupParser": {"lib": "libxml2", "purpose": "cleanup global parser state", "category": "serialization"},
    "_xmlInitParser": {"lib": "libxml2", "purpose": "init parser subsystem", "category": "serialization"},
    "_xmlMemoryDump": {"lib": "libxml2", "purpose": "dump memory debug info", "category": "serialization"},
    "_xmlFree": {"lib": "libxml2", "purpose": "free libxml2 memory", "category": "serialization"},
    # --- libxml2: Error ---
    "_xmlGetLastError": {"lib": "libxml2", "purpose": "get last XML error", "category": "serialization"},
    "_xmlResetLastError": {"lib": "libxml2", "purpose": "reset last XML error", "category": "serialization"},
    "_xmlSetStructuredErrorFunc": {"lib": "libxml2", "purpose": "set structured error handler", "category": "serialization"},
    # --- expat ---
    "_XML_ParserCreate": {"lib": "expat", "purpose": "create XML parser", "category": "serialization"},
    "_XML_ParserCreateNS": {"lib": "expat", "purpose": "create XML parser with namespace", "category": "serialization"},
    "_XML_ParserCreate_MM": {"lib": "expat", "purpose": "create XML parser (custom mem)", "category": "serialization"},
    "_XML_ParserFree": {"lib": "expat", "purpose": "free XML parser", "category": "serialization"},
    "_XML_ParserReset": {"lib": "expat", "purpose": "reset XML parser", "category": "serialization"},
    "_XML_Parse": {"lib": "expat", "purpose": "parse XML buffer", "category": "serialization"},
    "_XML_ParseBuffer": {"lib": "expat", "purpose": "parse XML from internal buffer", "category": "serialization"},
    "_XML_GetBuffer": {"lib": "expat", "purpose": "get internal parse buffer", "category": "serialization"},
    "_XML_SetElementHandler": {"lib": "expat", "purpose": "set element start/end handlers", "category": "serialization"},
    "_XML_SetCharacterDataHandler": {"lib": "expat", "purpose": "set character data handler", "category": "serialization"},
    "_XML_SetStartElementHandler": {"lib": "expat", "purpose": "set element start handler", "category": "serialization"},
    "_XML_SetEndElementHandler": {"lib": "expat", "purpose": "set element end handler", "category": "serialization"},
    "_XML_SetCommentHandler": {"lib": "expat", "purpose": "set comment handler", "category": "serialization"},
    "_XML_SetCdataSectionHandler": {"lib": "expat", "purpose": "set CDATA section handler", "category": "serialization"},
    "_XML_SetProcessingInstructionHandler": {"lib": "expat", "purpose": "set PI handler", "category": "serialization"},
    "_XML_SetDefaultHandler": {"lib": "expat", "purpose": "set default handler", "category": "serialization"},
    "_XML_SetUserData": {"lib": "expat", "purpose": "set user data pointer", "category": "serialization"},
    "_XML_GetErrorCode": {"lib": "expat", "purpose": "get parse error code", "category": "serialization"},
    "_XML_ErrorString": {"lib": "expat", "purpose": "get error description", "category": "serialization"},
    "_XML_GetCurrentLineNumber": {"lib": "expat", "purpose": "get current parse line", "category": "serialization"},
    "_XML_GetCurrentColumnNumber": {"lib": "expat", "purpose": "get current parse column", "category": "serialization"},
    "_XML_GetCurrentByteIndex": {"lib": "expat", "purpose": "get current byte offset", "category": "serialization"},
    "_XML_ExpatVersion": {"lib": "expat", "purpose": "expat version string", "category": "info"},
    "_XML_ExpatVersionInfo": {"lib": "expat", "purpose": "expat version struct", "category": "info"},
    "_XML_SetNamespaceDeclHandler": {"lib": "expat", "purpose": "set namespace declaration handler", "category": "serialization"},
    "_XML_SetExternalEntityRefHandler": {"lib": "expat", "purpose": "set external entity handler", "category": "serialization"},
    "_XML_StopParser": {"lib": "expat", "purpose": "stop parsing", "category": "serialization"},
    "_XML_ResumeParser": {"lib": "expat", "purpose": "resume parsing", "category": "serialization"},
    "_XML_GetParsingStatus": {"lib": "expat", "purpose": "get parser status", "category": "serialization"},
}


# ---------------------------------------------------------------------------
# serialization (44 entry) — FlatBuffers (mangled), Cap'n Proto (mangled), MessagePack C API.
# Kaynak: signature_db.py satir 2829-2877.
# ---------------------------------------------------------------------------
_SERIALIZATION_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # FlatBuffers
    "__ZN11flatbuffers17FlatBufferBuilder": {"lib": "flatbuffers", "purpose": "flatbuffers::FlatBufferBuilder (partial mangled)", "category": "serialization"},
    "__ZN11flatbuffers8Verifier": {"lib": "flatbuffers", "purpose": "flatbuffers::Verifier (partial mangled)", "category": "serialization"},
    "__ZN11flatbuffers7GetRoot": {"lib": "flatbuffers", "purpose": "flatbuffers::GetRoot (partial mangled)", "category": "serialization"},
    "__ZN11flatbuffers12CreateString": {"lib": "flatbuffers", "purpose": "flatbuffers::CreateString (partial mangled)", "category": "serialization"},
    "__ZN11flatbuffers12CreateVector": {"lib": "flatbuffers", "purpose": "flatbuffers::CreateVector (partial mangled)", "category": "serialization"},
    "__ZN11flatbuffers": {"lib": "flatbuffers", "purpose": "flatbuffers:: namespace (partial mangled prefix)", "category": "serialization"},
    # Cap'n Proto
    "__ZN5capnp14MessageBuilder": {"lib": "capnproto", "purpose": "capnp::MessageBuilder (partial mangled)", "category": "serialization"},
    "__ZN5capnp13MessageReader": {"lib": "capnproto", "purpose": "capnp::MessageReader (partial mangled)", "category": "serialization"},
    "__ZN5capnp19MallocMessageBuilder": {"lib": "capnproto", "purpose": "capnp::MallocMessageBuilder (partial mangled)", "category": "serialization"},
    "__ZN5capnp20StreamFdMessageReader": {"lib": "capnproto", "purpose": "capnp::StreamFdMessageReader (partial mangled)", "category": "serialization"},
    "__ZN5capnp17PackedMessageReader": {"lib": "capnproto", "purpose": "capnp::PackedMessageReader (partial mangled)", "category": "serialization"},
    "__ZN5capnp11writeMessage": {"lib": "capnproto", "purpose": "capnp::writeMessage (partial mangled)", "category": "serialization"},
    "__ZN5capnp": {"lib": "capnproto", "purpose": "capnp:: namespace (partial mangled prefix)", "category": "serialization"},
    # MessagePack (C API)
    "_msgpack_pack_int": {"lib": "msgpack", "purpose": "pack integer value", "category": "serialization"},
    "_msgpack_pack_int8": {"lib": "msgpack", "purpose": "pack int8 value", "category": "serialization"},
    "_msgpack_pack_int16": {"lib": "msgpack", "purpose": "pack int16 value", "category": "serialization"},
    "_msgpack_pack_int32": {"lib": "msgpack", "purpose": "pack int32 value", "category": "serialization"},
    "_msgpack_pack_int64": {"lib": "msgpack", "purpose": "pack int64 value", "category": "serialization"},
    "_msgpack_pack_uint8": {"lib": "msgpack", "purpose": "pack uint8 value", "category": "serialization"},
    "_msgpack_pack_uint16": {"lib": "msgpack", "purpose": "pack uint16 value", "category": "serialization"},
    "_msgpack_pack_uint32": {"lib": "msgpack", "purpose": "pack uint32 value", "category": "serialization"},
    "_msgpack_pack_uint64": {"lib": "msgpack", "purpose": "pack uint64 value", "category": "serialization"},
    "_msgpack_pack_float": {"lib": "msgpack", "purpose": "pack float value", "category": "serialization"},
    "_msgpack_pack_double": {"lib": "msgpack", "purpose": "pack double value", "category": "serialization"},
    "_msgpack_pack_str": {"lib": "msgpack", "purpose": "pack string header", "category": "serialization"},
    "_msgpack_pack_str_body": {"lib": "msgpack", "purpose": "pack string body", "category": "serialization"},
    "_msgpack_pack_bin": {"lib": "msgpack", "purpose": "pack binary header", "category": "serialization"},
    "_msgpack_pack_bin_body": {"lib": "msgpack", "purpose": "pack binary body", "category": "serialization"},
    "_msgpack_pack_array": {"lib": "msgpack", "purpose": "pack array header", "category": "serialization"},
    "_msgpack_pack_map": {"lib": "msgpack", "purpose": "pack map header", "category": "serialization"},
    "_msgpack_pack_nil": {"lib": "msgpack", "purpose": "pack nil value", "category": "serialization"},
    "_msgpack_pack_true": {"lib": "msgpack", "purpose": "pack true value", "category": "serialization"},
    "_msgpack_pack_false": {"lib": "msgpack", "purpose": "pack false value", "category": "serialization"},
    "_msgpack_unpack": {"lib": "msgpack", "purpose": "unpack message", "category": "serialization"},
    "_msgpack_unpack_next": {"lib": "msgpack", "purpose": "unpack next object", "category": "serialization"},
    "_msgpack_unpacked_init": {"lib": "msgpack", "purpose": "init unpacked object", "category": "serialization"},
    "_msgpack_unpacked_destroy": {"lib": "msgpack", "purpose": "destroy unpacked object", "category": "serialization"},
    "_msgpack_sbuffer_init": {"lib": "msgpack", "purpose": "init simple buffer", "category": "serialization"},
    "_msgpack_sbuffer_destroy": {"lib": "msgpack", "purpose": "destroy simple buffer", "category": "serialization"},
    "_msgpack_packer_init": {"lib": "msgpack", "purpose": "init packer", "category": "serialization"},
    "_msgpack_packer_new": {"lib": "msgpack", "purpose": "create new packer", "category": "serialization"},
    "_msgpack_packer_free": {"lib": "msgpack", "purpose": "free packer", "category": "serialization"},
    "_msgpack_zone_init": {"lib": "msgpack", "purpose": "init memory zone", "category": "serialization"},
    "_msgpack_zone_destroy": {"lib": "msgpack", "purpose": "destroy memory zone", "category": "serialization"},
}


# ---------------------------------------------------------------------------
# Dispatcher hook — sigdb_builtin.get_category("database") bu dict'i alir.
# Anahtar isimleri signature_db.py'deki orijinal dict adlariyla uyumludur
# (ornek: "sqlite_signatures" <-> _SQLITE_SIGNATURES).
# ---------------------------------------------------------------------------
SIGNATURES: dict[str, Any] = {
    "sqlite_signatures": _SQLITE_SIGNATURES_DATA,
    "database_ext_signatures": _DATABASE_EXT_SIGNATURES_DATA,
    "protobuf_signatures": _PROTOBUF_SIGNATURES_DATA,
    "json_signatures": _JSON_SIGNATURES_DATA,
    "xml_signatures": _XML_SIGNATURES_DATA,
    "serialization_signatures": _SERIALIZATION_SIGNATURES_DATA,
}


__all__ = ["SIGNATURES"]
