"""Game/ML/anti-analysis/mega-batch signatures — sig_db Faz 9 migrasyonu.
Kaynak: karadul/analyzers/signature_db.py
  - _ML_COMPUTE_SIGNATURES         (74 entry, satir 5281-5365)
    -> CUDA + cuBLAS + cuDNN + ONNX Runtime + OpenCV
  - _GAME_ENGINE_SIGNATURES        (73 entry, satir 5373-5460)
    -> Unreal + Godot + Box2D + Bullet + GLFW + GLAD/GLEW + ImGui
  - _ANTI_ANALYSIS_SIGNATURES      (14 entry, satir 4963-4993)
    -> anti-debug, anti-VM, anti-tamper, packer, obfuscation
  - _MEGA_BATCH_1_SIGNATURES       (329 entry, satir 5596-5940)
    -> Windows CRT + C++ STL/algorithm/memory/thread/io/fs/exception/
       runtime + libm math (KARMA icerik, top-level subkey altinda korundu)
  - _MEGA_BATCH_2_SIGNATURES       (260 entry, satir 5948-6220)
    -> Objective-C runtime + NSObject/Foundation + Swift + Swift
       concurrency (KARMA icerik, top-level subkey altinda korundu)

Toplam: 750 signature.

ADR 0007 A10 (v1.13 Dalga 2) — game_ml grubu. Bu modul *sadece tasima*
yapar; signature_db.py inline literal'leri korunur (Tip A override veya
A-DELETE, ileri faz). Mega batch'lerin karma kategori icerikleri orijinal
dict ismiyle ayni subkey altinda muhafaza edildi (re-categorize Faz 9
kapsami disindadir).

Anahtar isimleri signature_db.py orijinal dict adlariyla uyumludur:
  ``ml_compute_signatures``        <-> ``_ML_COMPUTE_SIGNATURES``
  ``game_engine_signatures``       <-> ``_GAME_ENGINE_SIGNATURES``
  ``anti_analysis_signatures``     <-> ``_ANTI_ANALYSIS_SIGNATURES``
  ``mega_batch_1_signatures``      <-> ``_MEGA_BATCH_1_SIGNATURES``
  ``mega_batch_2_signatures``      <-> ``_MEGA_BATCH_2_SIGNATURES``
"""
from __future__ import annotations

from typing import Any


# -------------------------------------------------------------------------
# ml_compute (74 entry) — CUDA, cuBLAS, cuDNN, ONNX Runtime, OpenCV.
# Kaynak: signature_db.py satir 5281-5365.
# -------------------------------------------------------------------------
_ML_COMPUTE_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    'cudaMalloc': {"lib": 'cuda', "purpose": 'allocate GPU device memory', "category": 'gpu_compute'},
    'cudaFree': {"lib": 'cuda', "purpose": 'free GPU device memory', "category": 'gpu_compute'},
    'cudaMemcpy': {"lib": 'cuda', "purpose": 'copy data between host and device', "category": 'gpu_compute'},
    'cudaMemcpyAsync': {"lib": 'cuda', "purpose": 'async copy between host and device', "category": 'gpu_compute'},
    'cudaMemset': {"lib": 'cuda', "purpose": 'set GPU memory to value', "category": 'gpu_compute'},
    'cudaSetDevice': {"lib": 'cuda', "purpose": 'set active GPU device', "category": 'gpu_compute'},
    'cudaGetDevice': {"lib": 'cuda', "purpose": 'get active GPU device', "category": 'gpu_compute'},
    'cudaGetDeviceCount': {"lib": 'cuda', "purpose": 'get number of CUDA devices', "category": 'gpu_compute'},
    'cudaGetDeviceProperties': {"lib": 'cuda', "purpose": 'get GPU device properties', "category": 'gpu_compute'},
    'cudaDeviceSynchronize': {"lib": 'cuda', "purpose": 'wait for all GPU operations', "category": 'gpu_compute'},
    'cudaStreamCreate': {"lib": 'cuda', "purpose": 'create CUDA stream', "category": 'gpu_compute'},
    'cudaStreamDestroy': {"lib": 'cuda', "purpose": 'destroy CUDA stream', "category": 'gpu_compute'},
    'cudaStreamSynchronize': {"lib": 'cuda', "purpose": 'synchronize CUDA stream', "category": 'gpu_compute'},
    'cudaEventCreate': {"lib": 'cuda', "purpose": 'create CUDA event', "category": 'gpu_compute'},
    'cudaEventRecord': {"lib": 'cuda', "purpose": 'record event in stream', "category": 'gpu_compute'},
    'cudaEventSynchronize': {"lib": 'cuda', "purpose": 'wait for CUDA event', "category": 'gpu_compute'},
    'cudaEventElapsedTime': {"lib": 'cuda', "purpose": 'compute elapsed time between events', "category": 'gpu_compute'},
    'cudaEventDestroy': {"lib": 'cuda', "purpose": 'destroy CUDA event', "category": 'gpu_compute'},
    'cudaLaunchKernel': {"lib": 'cuda', "purpose": 'launch CUDA kernel', "category": 'gpu_compute'},
    'cudaMallocManaged': {"lib": 'cuda', "purpose": 'allocate unified memory', "category": 'gpu_compute'},
    'cudaMemPrefetchAsync': {"lib": 'cuda', "purpose": 'prefetch unified memory', "category": 'gpu_compute'},
    'cudaHostAlloc': {"lib": 'cuda', "purpose": 'allocate pinned host memory', "category": 'gpu_compute'},
    'cudaFreeHost': {"lib": 'cuda', "purpose": 'free pinned host memory', "category": 'gpu_compute'},
    'cudaGetLastError': {"lib": 'cuda', "purpose": 'get last CUDA error', "category": 'gpu_compute'},
    'cudaPeekAtLastError': {"lib": 'cuda', "purpose": 'peek at last CUDA error', "category": 'gpu_compute'},
    'cudaGetErrorString': {"lib": 'cuda', "purpose": 'get CUDA error description', "category": 'gpu_compute'},
    'cublasCreate': {"lib": 'cublas', "purpose": 'create cuBLAS handle', "category": 'gpu_compute'},
    'cublasDestroy': {"lib": 'cublas', "purpose": 'destroy cuBLAS handle', "category": 'gpu_compute'},
    'cublasSgemm': {"lib": 'cublas', "purpose": 'single-precision matrix multiply (GPU)', "category": 'gpu_compute'},
    'cublasDgemm': {"lib": 'cublas', "purpose": 'double-precision matrix multiply (GPU)', "category": 'gpu_compute'},
    'cublasHgemm': {"lib": 'cublas', "purpose": 'half-precision matrix multiply (GPU)', "category": 'gpu_compute'},
    'cublasSgemv': {"lib": 'cublas', "purpose": 'single-precision matrix-vector multiply', "category": 'gpu_compute'},
    'cublasSetStream': {"lib": 'cublas', "purpose": 'set cuBLAS CUDA stream', "category": 'gpu_compute'},
    'cudnnCreate': {"lib": 'cudnn', "purpose": 'create cuDNN handle', "category": 'gpu_compute'},
    'cudnnDestroy': {"lib": 'cudnn', "purpose": 'destroy cuDNN handle', "category": 'gpu_compute'},
    'cudnnConvolutionForward': {"lib": 'cudnn', "purpose": 'cuDNN convolution forward pass', "category": 'gpu_compute'},
    'cudnnConvolutionBackwardData': {"lib": 'cudnn', "purpose": 'cuDNN convolution backward data', "category": 'gpu_compute'},
    'cudnnConvolutionBackwardFilter': {"lib": 'cudnn', "purpose": 'cuDNN convolution backward filter', "category": 'gpu_compute'},
    'cudnnBatchNormalizationForwardTraining': {"lib": 'cudnn', "purpose": 'cuDNN batch normalization forward', "category": 'gpu_compute'},
    'cudnnActivationForward': {"lib": 'cudnn', "purpose": 'cuDNN activation function forward', "category": 'gpu_compute'},
    'cudnnPoolingForward': {"lib": 'cudnn', "purpose": 'cuDNN pooling forward', "category": 'gpu_compute'},
    'cudnnSoftmaxForward': {"lib": 'cudnn', "purpose": 'cuDNN softmax forward', "category": 'gpu_compute'},
    'cudnnSetTensorNdDescriptor': {"lib": 'cudnn', "purpose": 'set cuDNN tensor descriptor', "category": 'gpu_compute'},
    'cudnnGetConvolutionForwardAlgorithm': {"lib": 'cudnn', "purpose": 'find best convolution algorithm', "category": 'gpu_compute'},
    'OrtCreateEnv': {"lib": 'onnxruntime', "purpose": 'create ONNX Runtime environment', "category": 'ml_inference'},
    'OrtCreateSession': {"lib": 'onnxruntime', "purpose": 'create inference session', "category": 'ml_inference'},
    'OrtCreateSessionOptions': {"lib": 'onnxruntime', "purpose": 'create session options', "category": 'ml_inference'},
    'OrtSessionGetInputCount': {"lib": 'onnxruntime', "purpose": 'get number of model inputs', "category": 'ml_inference'},
    'OrtSessionGetOutputCount': {"lib": 'onnxruntime', "purpose": 'get number of model outputs', "category": 'ml_inference'},
    'OrtRun': {"lib": 'onnxruntime', "purpose": 'run inference', "category": 'ml_inference'},
    'OrtCreateTensorWithDataAsOrtValue': {"lib": 'onnxruntime', "purpose": 'create input tensor', "category": 'ml_inference'},
    'OrtGetTensorData': {"lib": 'onnxruntime', "purpose": 'get output tensor data', "category": 'ml_inference'},
    'OrtReleaseEnv': {"lib": 'onnxruntime', "purpose": 'release environment', "category": 'ml_inference'},
    'OrtReleaseSession': {"lib": 'onnxruntime', "purpose": 'release inference session', "category": 'ml_inference'},
    'cv::imread': {"lib": 'opencv', "purpose": 'read image file', "category": 'cv'},
    'cv::imwrite': {"lib": 'opencv', "purpose": 'write image file', "category": 'cv'},
    'cv::imshow': {"lib": 'opencv', "purpose": 'display image in window', "category": 'cv'},
    'cv::waitKey': {"lib": 'opencv', "purpose": 'wait for key press in window', "category": 'cv'},
    'cv::cvtColor': {"lib": 'opencv', "purpose": 'convert color space', "category": 'cv'},
    'cv::resize': {"lib": 'opencv', "purpose": 'resize image', "category": 'cv'},
    'cv::GaussianBlur': {"lib": 'opencv', "purpose": 'Gaussian blur filter', "category": 'cv'},
    'cv::Canny': {"lib": 'opencv', "purpose": 'Canny edge detection', "category": 'cv'},
    'cv::threshold': {"lib": 'opencv', "purpose": 'binary threshold', "category": 'cv'},
    'cv::findContours': {"lib": 'opencv', "purpose": 'find contours in binary image', "category": 'cv'},
    'cv::drawContours': {"lib": 'opencv', "purpose": 'draw contours on image', "category": 'cv'},
    'cv::rectangle': {"lib": 'opencv', "purpose": 'draw rectangle on image', "category": 'cv'},
    'cv::circle': {"lib": 'opencv', "purpose": 'draw circle on image', "category": 'cv'},
    'cv::putText': {"lib": 'opencv', "purpose": 'draw text on image', "category": 'cv'},
    'cv::VideoCapture::VideoCapture': {"lib": 'opencv', "purpose": 'create video capture', "category": 'cv'},
    'cv::VideoCapture::read': {"lib": 'opencv', "purpose": 'read video frame', "category": 'cv'},
    'cv::VideoWriter::VideoWriter': {"lib": 'opencv', "purpose": 'create video writer', "category": 'cv'},
    'cv::Mat::Mat': {"lib": 'opencv', "purpose": 'create OpenCV matrix', "category": 'cv'},
    'cv::Mat::clone': {"lib": 'opencv', "purpose": 'clone OpenCV matrix', "category": 'cv'},
    'cv::Mat::copyTo': {"lib": 'opencv', "purpose": 'copy matrix to another', "category": 'cv'},
}


# -------------------------------------------------------------------------
# game_engine (73 entry) — Unreal, Godot, Box2D, Bullet, GLFW, GLAD/GLEW, ImGui.
# Kaynak: signature_db.py satir 5373-5460.
# -------------------------------------------------------------------------
_GAME_ENGINE_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    'UObject::ProcessEvent': {"lib": 'unreal', "purpose": 'Unreal process Blueprint event', "category": 'game_engine'},
    'FMemory::Malloc': {"lib": 'unreal', "purpose": 'Unreal memory allocation', "category": 'game_engine'},
    'FMemory::Free': {"lib": 'unreal', "purpose": 'Unreal memory free', "category": 'game_engine'},
    'FMemory::Realloc': {"lib": 'unreal', "purpose": 'Unreal memory reallocation', "category": 'game_engine'},
    'FString::Printf': {"lib": 'unreal', "purpose": 'Unreal formatted string', "category": 'game_engine'},
    'FName::Init': {"lib": 'unreal', "purpose": 'Unreal name initialization', "category": 'game_engine'},
    'UWorld::Tick': {"lib": 'unreal', "purpose": 'Unreal world tick update', "category": 'game_engine'},
    'AActor::BeginPlay': {"lib": 'unreal', "purpose": 'Unreal actor begin play', "category": 'game_engine'},
    'AActor::Tick': {"lib": 'unreal', "purpose": 'Unreal actor tick', "category": 'game_engine'},
    'UGameplayStatics::SpawnActor': {"lib": 'unreal', "purpose": 'Unreal spawn actor', "category": 'game_engine'},
    'GEngine': {"lib": 'unreal', "purpose": 'Unreal global engine pointer', "category": 'game_engine'},
    'godot_gdnative_init': {"lib": 'godot', "purpose": 'Godot GDNative init', "category": 'game_engine'},
    'godot_gdnative_terminate': {"lib": 'godot', "purpose": 'Godot GDNative terminate', "category": 'game_engine'},
    'godot_nativescript_init': {"lib": 'godot', "purpose": 'Godot NativeScript init', "category": 'game_engine'},
    'godot_variant_new_string': {"lib": 'godot', "purpose": 'create Godot variant from string', "category": 'game_engine'},
    'godot_variant_destroy': {"lib": 'godot', "purpose": 'destroy Godot variant', "category": 'game_engine'},
    'godot_string_new': {"lib": 'godot', "purpose": 'create new Godot string', "category": 'game_engine'},
    'godot_string_destroy': {"lib": 'godot', "purpose": 'destroy Godot string', "category": 'game_engine'},
    'godot_method_bind_get_method': {"lib": 'godot', "purpose": 'get Godot method binding', "category": 'game_engine'},
    'godot_method_bind_call': {"lib": 'godot', "purpose": 'call Godot method', "category": 'game_engine'},
    'b2World::Step': {"lib": 'box2d', "purpose": 'Box2D physics step', "category": 'physics'},
    'b2World::CreateBody': {"lib": 'box2d', "purpose": 'create Box2D rigid body', "category": 'physics'},
    'b2World::DestroyBody': {"lib": 'box2d', "purpose": 'destroy Box2D rigid body', "category": 'physics'},
    'b2Body::CreateFixture': {"lib": 'box2d', "purpose": 'create Box2D fixture', "category": 'physics'},
    'b2Body::DestroyFixture': {"lib": 'box2d', "purpose": 'destroy Box2D fixture', "category": 'physics'},
    'b2Body::SetTransform': {"lib": 'box2d', "purpose": 'set Box2D body position/angle', "category": 'physics'},
    'b2Body::GetPosition': {"lib": 'box2d', "purpose": 'get Box2D body position', "category": 'physics'},
    'b2Body::ApplyForce': {"lib": 'box2d', "purpose": 'apply force to Box2D body', "category": 'physics'},
    'b2Body::ApplyLinearImpulse': {"lib": 'box2d', "purpose": 'apply impulse to Box2D body', "category": 'physics'},
    'b2World::CreateJoint': {"lib": 'box2d', "purpose": 'create Box2D joint', "category": 'physics'},
    'b2World::DestroyJoint': {"lib": 'box2d', "purpose": 'destroy Box2D joint', "category": 'physics'},
    'b2World::SetContactListener': {"lib": 'box2d', "purpose": 'set Box2D contact callback', "category": 'physics'},
    'btDiscreteDynamicsWorld::stepSimulation': {"lib": 'bullet', "purpose": 'Bullet physics step', "category": 'physics'},
    'btCollisionDispatcher::btCollisionDispatcher': {"lib": 'bullet', "purpose": 'Bullet collision dispatcher', "category": 'physics'},
    'btDbvtBroadphase::btDbvtBroadphase': {"lib": 'bullet', "purpose": 'Bullet broadphase', "category": 'physics'},
    'btSequentialImpulseConstraintSolver::btSequentialImpulseConstraintSolver': {"lib": 'bullet', "purpose": 'Bullet constraint solver', "category": 'physics'},
    'btRigidBody::btRigidBody': {"lib": 'bullet', "purpose": 'create Bullet rigid body', "category": 'physics'},
    'btDiscreteDynamicsWorld::addRigidBody': {"lib": 'bullet', "purpose": 'add rigid body to Bullet world', "category": 'physics'},
    'btDiscreteDynamicsWorld::removeRigidBody': {"lib": 'bullet', "purpose": 'remove rigid body from Bullet world', "category": 'physics'},
    'btRigidBody::applyCentralForce': {"lib": 'bullet', "purpose": 'apply force to Bullet body', "category": 'physics'},
    'btRigidBody::applyCentralImpulse': {"lib": 'bullet', "purpose": 'apply impulse to Bullet body', "category": 'physics'},
    'glfwInit': {"lib": 'glfw', "purpose": 'initialize GLFW', "category": 'windowing'},
    'glfwTerminate': {"lib": 'glfw', "purpose": 'terminate GLFW', "category": 'windowing'},
    'glfwCreateWindow': {"lib": 'glfw', "purpose": 'create GLFW window', "category": 'windowing'},
    'glfwDestroyWindow': {"lib": 'glfw', "purpose": 'destroy GLFW window', "category": 'windowing'},
    'glfwMakeContextCurrent': {"lib": 'glfw', "purpose": 'make OpenGL context current', "category": 'windowing'},
    'glfwSwapBuffers': {"lib": 'glfw', "purpose": 'swap front/back buffers', "category": 'windowing'},
    'glfwPollEvents': {"lib": 'glfw', "purpose": 'poll for window events', "category": 'windowing'},
    'glfwWaitEvents': {"lib": 'glfw', "purpose": 'wait for window events', "category": 'windowing'},
    'glfwSetKeyCallback': {"lib": 'glfw', "purpose": 'set keyboard callback', "category": 'windowing'},
    'glfwSetMouseButtonCallback': {"lib": 'glfw', "purpose": 'set mouse button callback', "category": 'windowing'},
    'glfwSetCursorPosCallback': {"lib": 'glfw', "purpose": 'set cursor position callback', "category": 'windowing'},
    'glfwSetFramebufferSizeCallback': {"lib": 'glfw', "purpose": 'set framebuffer resize callback', "category": 'windowing'},
    'glfwWindowShouldClose': {"lib": 'glfw', "purpose": 'check if window should close', "category": 'windowing'},
    'glfwGetTime': {"lib": 'glfw', "purpose": 'get GLFW time', "category": 'windowing'},
    'glfwSetWindowTitle': {"lib": 'glfw', "purpose": 'set window title', "category": 'windowing'},
    'glfwGetWindowSize': {"lib": 'glfw', "purpose": 'get window size', "category": 'windowing'},
    'glfwSetInputMode': {"lib": 'glfw', "purpose": 'set input mode (cursor, etc)', "category": 'windowing'},
    'gladLoadGLLoader': {"lib": 'glad', "purpose": 'load OpenGL function pointers', "category": 'graphics'},
    'glewInit': {"lib": 'glew', "purpose": 'initialize GLEW (OpenGL extension loader)', "category": 'graphics'},
    'ImGui::Begin': {"lib": 'imgui', "purpose": 'begin ImGui window', "category": 'gui'},
    'ImGui::End': {"lib": 'imgui', "purpose": 'end ImGui window', "category": 'gui'},
    'ImGui::Text': {"lib": 'imgui', "purpose": 'display ImGui text', "category": 'gui'},
    'ImGui::Button': {"lib": 'imgui', "purpose": 'ImGui button widget', "category": 'gui'},
    'ImGui::InputText': {"lib": 'imgui', "purpose": 'ImGui text input', "category": 'gui'},
    'ImGui::SliderFloat': {"lib": 'imgui', "purpose": 'ImGui float slider', "category": 'gui'},
    'ImGui::Checkbox': {"lib": 'imgui', "purpose": 'ImGui checkbox', "category": 'gui'},
    'ImGui::TreeNode': {"lib": 'imgui', "purpose": 'ImGui tree node', "category": 'gui'},
    'ImGui::Render': {"lib": 'imgui', "purpose": 'render ImGui frame', "category": 'gui'},
    'ImGui::NewFrame': {"lib": 'imgui', "purpose": 'start new ImGui frame', "category": 'gui'},
    'ImGui::CreateContext': {"lib": 'imgui', "purpose": 'create ImGui context', "category": 'gui'},
    'ImGui::DestroyContext': {"lib": 'imgui', "purpose": 'destroy ImGui context', "category": 'gui'},
    'ImGui::GetIO': {"lib": 'imgui', "purpose": 'get ImGui IO structure', "category": 'gui'},
}


# -------------------------------------------------------------------------
# anti_analysis (14 entry) — anti-debug, anti-VM, anti-tamper, packer, obfuscation.
# Kaynak: signature_db.py satir 4963-4993.
# -------------------------------------------------------------------------
_ANTI_ANALYSIS_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    'ptrace_PTRACE_TRACEME': {"lib": 'libc', "purpose": 'self-trace to detect debugger', "category": 'anti_debug'},
    '__debugbreak': {"lib": 'compiler', "purpose": 'compiler intrinsic breakpoint', "category": 'anti_debug'},
    'sysctl_kern_proc': {"lib": 'libc', "purpose": 'query process info (anti-debug check)', "category": 'anti_debug'},
    'AmIBeingDebugged': {"lib": 'custom', "purpose": 'custom debugger detection function', "category": 'anti_debug'},
    'CheckRemoteDebuggerPresent': {"lib": 'kernel32', "purpose": 'check if remote debugger attached', "category": 'anti_debug'},
    'NtQueryInformationProcess_ProcessDebugPort': {"lib": 'ntdll', "purpose": 'query debug port (anti-debug)', "category": 'anti_debug'},
    'NtSetInformationThread_ThreadHideFromDebugger': {"lib": 'ntdll', "purpose": 'hide thread from debugger', "category": 'anti_debug'},
    'cpuid_hypervisor_detect': {"lib": 'custom', "purpose": 'CPUID hypervisor bit check (VM detection)', "category": 'anti_vm'},
    'rdtsc_timing_check': {"lib": 'custom', "purpose": 'RDTSC timing-based debugger detection', "category": 'anti_debug'},
    'CRC32_self_check': {"lib": 'custom', "purpose": 'CRC32 self-integrity verification', "category": 'anti_tamper'},
    'UPX_unpack': {"lib": 'upx', "purpose": 'UPX packer runtime unpacker', "category": 'packer'},
    'ollvm_flattening': {"lib": 'ollvm', "purpose": 'OLLVM control flow flattening marker', "category": 'obfuscation'},
    'themida_entry': {"lib": 'themida', "purpose": 'Themida protector entry', "category": 'packer'},
    'vmprotect_entry': {"lib": 'vmprotect', "purpose": 'VMProtect virtualized entry', "category": 'packer'},
}


# -------------------------------------------------------------------------
# mega_batch_1 (329 entry, KARMA) — Win CRT + C++ STL/algo/mem/thread/io/fs/
# exception/runtime + libm math. Kaynak: signature_db.py satir 5596-5940.
# NOT: Karma kategoriler (win_crt/cpp_*/math) tek dict'te tutulmustur; re-
# categorize islemi A-DELETE veya sonraki rafinaj fazlarinda ele alinir.
# -------------------------------------------------------------------------
_MEGA_BATCH_1_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    '_open': {"lib": 'msvcrt', "purpose": 'open file (MSVC CRT)', "category": 'win_crt'},
    '_close': {"lib": 'msvcrt', "purpose": 'close file descriptor (MSVC CRT)', "category": 'win_crt'},
    '_read': {"lib": 'msvcrt', "purpose": 'read from file descriptor (MSVC CRT)', "category": 'win_crt'},
    '_write': {"lib": 'msvcrt', "purpose": 'write to file descriptor (MSVC CRT)', "category": 'win_crt'},
    '_lseek': {"lib": 'msvcrt', "purpose": 'seek file position (MSVC CRT)', "category": 'win_crt'},
    '_stat': {"lib": 'msvcrt', "purpose": 'get file status (MSVC CRT)', "category": 'win_crt'},
    '_fstat': {"lib": 'msvcrt', "purpose": 'get file status by fd (MSVC CRT)', "category": 'win_crt'},
    '_access': {"lib": 'msvcrt', "purpose": 'check file access (MSVC CRT)', "category": 'win_crt'},
    '_mkdir': {"lib": 'msvcrt', "purpose": 'create directory (MSVC CRT)', "category": 'win_crt'},
    '_rmdir': {"lib": 'msvcrt', "purpose": 'remove directory (MSVC CRT)', "category": 'win_crt'},
    '_unlink': {"lib": 'msvcrt', "purpose": 'delete file (MSVC CRT)', "category": 'win_crt'},
    '_getcwd': {"lib": 'msvcrt', "purpose": 'get current directory (MSVC CRT)', "category": 'win_crt'},
    '_chdir': {"lib": 'msvcrt', "purpose": 'change directory (MSVC CRT)', "category": 'win_crt'},
    '_dup': {"lib": 'msvcrt', "purpose": 'duplicate fd (MSVC CRT)', "category": 'win_crt'},
    '_dup2': {"lib": 'msvcrt', "purpose": 'duplicate fd to specific number (MSVC CRT)', "category": 'win_crt'},
    '_pipe': {"lib": 'msvcrt', "purpose": 'create pipe (MSVC CRT)', "category": 'win_crt'},
    '_popen': {"lib": 'msvcrt', "purpose": 'open pipe to process (MSVC CRT)', "category": 'win_crt'},
    '_pclose': {"lib": 'msvcrt', "purpose": 'close process pipe (MSVC CRT)', "category": 'win_crt'},
    '_findfirst': {"lib": 'msvcrt', "purpose": 'find first file (MSVC CRT)', "category": 'win_crt'},
    '_findnext': {"lib": 'msvcrt', "purpose": 'find next file (MSVC CRT)', "category": 'win_crt'},
    '_findclose': {"lib": 'msvcrt', "purpose": 'close find handle (MSVC CRT)', "category": 'win_crt'},
    '_getpid': {"lib": 'msvcrt', "purpose": 'get process ID (MSVC CRT)', "category": 'win_crt'},
    '_beginthreadex': {"lib": 'msvcrt', "purpose": 'create thread (CRT-safe)', "category": 'win_crt'},
    '_endthreadex': {"lib": 'msvcrt', "purpose": 'terminate thread (CRT-safe)', "category": 'win_crt'},
    '_beginthread': {"lib": 'msvcrt', "purpose": 'create thread (legacy)', "category": 'win_crt'},
    '_endthread': {"lib": 'msvcrt', "purpose": 'end thread (legacy)', "category": 'win_crt'},
    '_set_se_translator': {"lib": 'msvcrt', "purpose": 'set SEH to C++ exception translator', "category": 'win_crt'},
    '_set_invalid_parameter_handler': {"lib": 'msvcrt', "purpose": 'set invalid parameter handler', "category": 'win_crt'},
    '_CrtDbgReport': {"lib": 'msvcrt', "purpose": 'CRT debug report', "category": 'win_crt'},
    '_CrtSetReportMode': {"lib": 'msvcrt', "purpose": 'set CRT report mode', "category": 'win_crt'},
    '_CrtSetDbgFlag': {"lib": 'msvcrt', "purpose": 'set CRT debug flag', "category": 'win_crt'},
    '_CrtDumpMemoryLeaks': {"lib": 'msvcrt', "purpose": 'dump memory leaks', "category": 'win_crt'},
    '_msize': {"lib": 'msvcrt', "purpose": 'get heap allocation size', "category": 'win_crt'},
    '_aligned_malloc': {"lib": 'msvcrt', "purpose": 'aligned memory allocation', "category": 'win_crt'},
    '_aligned_free': {"lib": 'msvcrt', "purpose": 'free aligned allocation', "category": 'win_crt'},
    '_aligned_realloc': {"lib": 'msvcrt', "purpose": 'reallocate aligned memory', "category": 'win_crt'},
    '_malloca': {"lib": 'msvcrt', "purpose": 'stack or heap allocation', "category": 'win_crt'},
    '_freea': {"lib": 'msvcrt', "purpose": 'free stack/heap allocation', "category": 'win_crt'},
    '_strdup': {"lib": 'msvcrt', "purpose": 'duplicate string (MSVC)', "category": 'win_crt'},
    '_wcsdup': {"lib": 'msvcrt', "purpose": 'duplicate wide string (MSVC)', "category": 'win_crt'},
    '_stricmp': {"lib": 'msvcrt', "purpose": 'case-insensitive compare (MSVC)', "category": 'win_crt'},
    '_strnicmp': {"lib": 'msvcrt', "purpose": 'case-insensitive compare n chars (MSVC)', "category": 'win_crt'},
    '_strlwr': {"lib": 'msvcrt', "purpose": 'convert string to lowercase (MSVC)', "category": 'win_crt'},
    '_strupr': {"lib": 'msvcrt', "purpose": 'convert string to uppercase (MSVC)', "category": 'win_crt'},
    '_itoa': {"lib": 'msvcrt', "purpose": 'integer to string (MSVC)', "category": 'win_crt'},
    '_ltoa': {"lib": 'msvcrt', "purpose": 'long to string (MSVC)', "category": 'win_crt'},
    '_i64toa': {"lib": 'msvcrt', "purpose": 'int64 to string (MSVC)', "category": 'win_crt'},
    '_atoi64': {"lib": 'msvcrt', "purpose": 'string to int64 (MSVC)', "category": 'win_crt'},
    '_wtoi': {"lib": 'msvcrt', "purpose": 'wide string to int (MSVC)', "category": 'win_crt'},
    '_wtof': {"lib": 'msvcrt', "purpose": 'wide string to float (MSVC)', "category": 'win_crt'},
    '_snprintf': {"lib": 'msvcrt', "purpose": 'bounded sprintf (MSVC)', "category": 'win_crt'},
    '_vsnprintf': {"lib": 'msvcrt', "purpose": 'bounded vsprintf (MSVC)', "category": 'win_crt'},
    '_snwprintf': {"lib": 'msvcrt', "purpose": 'bounded swprintf (MSVC)', "category": 'win_crt'},
    'sprintf_s': {"lib": 'msvcrt', "purpose": 'safe sprintf (CRT secure)', "category": 'win_crt'},
    'strcpy_s': {"lib": 'msvcrt', "purpose": 'safe strcpy (CRT secure)', "category": 'win_crt'},
    'strncpy_s': {"lib": 'msvcrt', "purpose": 'safe strncpy (CRT secure)', "category": 'win_crt'},
    'strcat_s': {"lib": 'msvcrt', "purpose": 'safe strcat (CRT secure)', "category": 'win_crt'},
    'wcscpy_s': {"lib": 'msvcrt', "purpose": 'safe wcscpy (CRT secure)', "category": 'win_crt'},
    'wcscat_s': {"lib": 'msvcrt', "purpose": 'safe wcscat (CRT secure)', "category": 'win_crt'},
    'memcpy_s': {"lib": 'msvcrt', "purpose": 'safe memcpy (CRT secure)', "category": 'win_crt'},
    'memmove_s': {"lib": 'msvcrt', "purpose": 'safe memmove (CRT secure)', "category": 'win_crt'},
    '_wfopen': {"lib": 'msvcrt', "purpose": 'open file (wide path, MSVC)', "category": 'win_crt'},
    'fopen_s': {"lib": 'msvcrt', "purpose": 'safe fopen (CRT secure)', "category": 'win_crt'},
    '_wfopen_s': {"lib": 'msvcrt', "purpose": 'safe fopen wide (CRT secure)', "category": 'win_crt'},
    'wprintf': {"lib": 'msvcrt', "purpose": 'wide formatted output to stdout', "category": 'win_crt'},
    'wcslen': {"lib": 'msvcrt', "purpose": 'wide string length', "category": 'win_crt'},
    'wcscmp': {"lib": 'msvcrt', "purpose": 'compare wide strings', "category": 'win_crt'},
    'wcsncmp': {"lib": 'msvcrt', "purpose": 'compare wide strings with limit', "category": 'win_crt'},
    'wcscpy': {"lib": 'msvcrt', "purpose": 'copy wide string', "category": 'win_crt'},
    'wcscat': {"lib": 'msvcrt', "purpose": 'concatenate wide strings', "category": 'win_crt'},
    'wcsstr': {"lib": 'msvcrt', "purpose": 'find wide substring', "category": 'win_crt'},
    'wcschr': {"lib": 'msvcrt', "purpose": 'find wide char in string', "category": 'win_crt'},
    'wcsrchr': {"lib": 'msvcrt', "purpose": 'find last wide char in string', "category": 'win_crt'},
    'wcstol': {"lib": 'msvcrt', "purpose": 'wide string to long', "category": 'win_crt'},
    'wcstod': {"lib": 'msvcrt', "purpose": 'wide string to double', "category": 'win_crt'},
    '_wcsicmp': {"lib": 'msvcrt', "purpose": 'case-insensitive wide compare', "category": 'win_crt'},
    '_wcsnicmp': {"lib": 'msvcrt', "purpose": 'case-insensitive wide compare n chars', "category": 'win_crt'},
    'std::string::string': {"lib": 'libc++', "purpose": 'std::string constructor', "category": 'cpp_stl'},
    'std::string::~string': {"lib": 'libc++', "purpose": 'std::string destructor', "category": 'cpp_stl'},
    'std::string::append': {"lib": 'libc++', "purpose": 'append to string', "category": 'cpp_stl'},
    'std::string::assign': {"lib": 'libc++', "purpose": 'assign string content', "category": 'cpp_stl'},
    'std::string::c_str': {"lib": 'libc++', "purpose": 'get C string', "category": 'cpp_stl'},
    'std::string::data': {"lib": 'libc++', "purpose": 'get string data', "category": 'cpp_stl'},
    'std::string::size': {"lib": 'libc++', "purpose": 'get string size', "category": 'cpp_stl'},
    'std::string::empty': {"lib": 'libc++', "purpose": 'check if string empty', "category": 'cpp_stl'},
    'std::string::find': {"lib": 'libc++', "purpose": 'find substring', "category": 'cpp_stl'},
    'std::string::substr': {"lib": 'libc++', "purpose": 'get substring', "category": 'cpp_stl'},
    'std::string::compare': {"lib": 'libc++', "purpose": 'compare strings', "category": 'cpp_stl'},
    'std::string::reserve': {"lib": 'libc++', "purpose": 'reserve string capacity', "category": 'cpp_stl'},
    'std::string::resize': {"lib": 'libc++', "purpose": 'resize string', "category": 'cpp_stl'},
    'std::string::clear': {"lib": 'libc++', "purpose": 'clear string content', "category": 'cpp_stl'},
    'std::string::push_back': {"lib": 'libc++', "purpose": 'append character', "category": 'cpp_stl'},
    'std::string::erase': {"lib": 'libc++', "purpose": 'erase characters', "category": 'cpp_stl'},
    'std::string::insert': {"lib": 'libc++', "purpose": 'insert characters', "category": 'cpp_stl'},
    'std::string::replace': {"lib": 'libc++', "purpose": 'replace portion', "category": 'cpp_stl'},
    'std::vector::push_back': {"lib": 'libc++', "purpose": 'add element to vector end', "category": 'cpp_stl'},
    'std::vector::emplace_back': {"lib": 'libc++', "purpose": 'construct element at vector end', "category": 'cpp_stl'},
    'std::vector::pop_back': {"lib": 'libc++', "purpose": 'remove last vector element', "category": 'cpp_stl'},
    'std::vector::reserve': {"lib": 'libc++', "purpose": 'reserve vector capacity', "category": 'cpp_stl'},
    'std::vector::resize': {"lib": 'libc++', "purpose": 'resize vector', "category": 'cpp_stl'},
    'std::vector::clear': {"lib": 'libc++', "purpose": 'clear vector', "category": 'cpp_stl'},
    'std::vector::erase': {"lib": 'libc++', "purpose": 'erase vector elements', "category": 'cpp_stl'},
    'std::vector::insert': {"lib": 'libc++', "purpose": 'insert vector elements', "category": 'cpp_stl'},
    'std::vector::size': {"lib": 'libc++', "purpose": 'get vector size', "category": 'cpp_stl'},
    'std::vector::empty': {"lib": 'libc++', "purpose": 'check if vector empty', "category": 'cpp_stl'},
    'std::vector::begin': {"lib": 'libc++', "purpose": 'get vector begin iterator', "category": 'cpp_stl'},
    'std::vector::end': {"lib": 'libc++', "purpose": 'get vector end iterator', "category": 'cpp_stl'},
    'std::vector::data': {"lib": 'libc++', "purpose": 'get vector data pointer', "category": 'cpp_stl'},
    'std::map::find': {"lib": 'libc++', "purpose": 'find element in map', "category": 'cpp_stl'},
    'std::map::insert': {"lib": 'libc++', "purpose": 'insert into map', "category": 'cpp_stl'},
    'std::map::erase': {"lib": 'libc++', "purpose": 'erase from map', "category": 'cpp_stl'},
    'std::map::count': {"lib": 'libc++', "purpose": 'count map elements', "category": 'cpp_stl'},
    'std::map::size': {"lib": 'libc++', "purpose": 'get map size', "category": 'cpp_stl'},
    'std::map::empty': {"lib": 'libc++', "purpose": 'check if map empty', "category": 'cpp_stl'},
    'std::map::begin': {"lib": 'libc++', "purpose": 'get map begin iterator', "category": 'cpp_stl'},
    'std::map::end': {"lib": 'libc++', "purpose": 'get map end iterator', "category": 'cpp_stl'},
    'std::map::operator[]': {"lib": 'libc++', "purpose": 'map subscript access', "category": 'cpp_stl'},
    'std::unordered_map::find': {"lib": 'libc++', "purpose": 'find in unordered_map', "category": 'cpp_stl'},
    'std::unordered_map::insert': {"lib": 'libc++', "purpose": 'insert into unordered_map', "category": 'cpp_stl'},
    'std::unordered_map::erase': {"lib": 'libc++', "purpose": 'erase from unordered_map', "category": 'cpp_stl'},
    'std::unordered_map::count': {"lib": 'libc++', "purpose": 'count unordered_map elements', "category": 'cpp_stl'},
    'std::unordered_map::size': {"lib": 'libc++', "purpose": 'get unordered_map size', "category": 'cpp_stl'},
    'std::unordered_map::empty': {"lib": 'libc++', "purpose": 'check if unordered_map empty', "category": 'cpp_stl'},
    'std::unordered_map::operator[]': {"lib": 'libc++', "purpose": 'unordered_map subscript access', "category": 'cpp_stl'},
    'std::set::insert': {"lib": 'libc++', "purpose": 'insert into set', "category": 'cpp_stl'},
    'std::set::erase': {"lib": 'libc++', "purpose": 'erase from set', "category": 'cpp_stl'},
    'std::set::find': {"lib": 'libc++', "purpose": 'find in set', "category": 'cpp_stl'},
    'std::set::count': {"lib": 'libc++', "purpose": 'count set elements', "category": 'cpp_stl'},
    'std::set::size': {"lib": 'libc++', "purpose": 'get set size', "category": 'cpp_stl'},
    'std::unordered_set::insert': {"lib": 'libc++', "purpose": 'insert into unordered_set', "category": 'cpp_stl'},
    'std::unordered_set::erase': {"lib": 'libc++', "purpose": 'erase from unordered_set', "category": 'cpp_stl'},
    'std::unordered_set::find': {"lib": 'libc++', "purpose": 'find in unordered_set', "category": 'cpp_stl'},
    'std::list::push_back': {"lib": 'libc++', "purpose": 'add to list end', "category": 'cpp_stl'},
    'std::list::push_front': {"lib": 'libc++', "purpose": 'add to list front', "category": 'cpp_stl'},
    'std::list::pop_back': {"lib": 'libc++', "purpose": 'remove from list end', "category": 'cpp_stl'},
    'std::list::pop_front': {"lib": 'libc++', "purpose": 'remove from list front', "category": 'cpp_stl'},
    'std::list::erase': {"lib": 'libc++', "purpose": 'erase list element', "category": 'cpp_stl'},
    'std::list::insert': {"lib": 'libc++', "purpose": 'insert into list', "category": 'cpp_stl'},
    'std::list::size': {"lib": 'libc++', "purpose": 'get list size', "category": 'cpp_stl'},
    'std::list::empty': {"lib": 'libc++', "purpose": 'check if list empty', "category": 'cpp_stl'},
    'std::list::sort': {"lib": 'libc++', "purpose": 'sort list elements', "category": 'cpp_stl'},
    'std::deque::push_back': {"lib": 'libc++', "purpose": 'add to deque end', "category": 'cpp_stl'},
    'std::deque::push_front': {"lib": 'libc++', "purpose": 'add to deque front', "category": 'cpp_stl'},
    'std::deque::pop_back': {"lib": 'libc++', "purpose": 'remove from deque end', "category": 'cpp_stl'},
    'std::deque::pop_front': {"lib": 'libc++', "purpose": 'remove from deque front', "category": 'cpp_stl'},
    'std::deque::size': {"lib": 'libc++', "purpose": 'get deque size', "category": 'cpp_stl'},
    'std::queue::push': {"lib": 'libc++', "purpose": 'push to queue', "category": 'cpp_stl'},
    'std::queue::pop': {"lib": 'libc++', "purpose": 'pop from queue', "category": 'cpp_stl'},
    'std::queue::front': {"lib": 'libc++', "purpose": 'get queue front element', "category": 'cpp_stl'},
    'std::queue::empty': {"lib": 'libc++', "purpose": 'check if queue empty', "category": 'cpp_stl'},
    'std::stack::push': {"lib": 'libc++', "purpose": 'push to stack', "category": 'cpp_stl'},
    'std::stack::pop': {"lib": 'libc++', "purpose": 'pop from stack', "category": 'cpp_stl'},
    'std::stack::top': {"lib": 'libc++', "purpose": 'get stack top element', "category": 'cpp_stl'},
    'std::stack::empty': {"lib": 'libc++', "purpose": 'check if stack empty', "category": 'cpp_stl'},
    'std::priority_queue::push': {"lib": 'libc++', "purpose": 'push to priority queue', "category": 'cpp_stl'},
    'std::priority_queue::pop': {"lib": 'libc++', "purpose": 'pop from priority queue', "category": 'cpp_stl'},
    'std::priority_queue::top': {"lib": 'libc++', "purpose": 'get priority queue top', "category": 'cpp_stl'},
    'std::sort': {"lib": 'libc++', "purpose": 'sort range', "category": 'cpp_algorithm'},
    'std::stable_sort': {"lib": 'libc++', "purpose": 'stable sort range', "category": 'cpp_algorithm'},
    'std::partial_sort': {"lib": 'libc++', "purpose": 'partial sort range', "category": 'cpp_algorithm'},
    'std::nth_element': {"lib": 'libc++', "purpose": 'nth element partition', "category": 'cpp_algorithm'},
    'std::binary_search': {"lib": 'libc++', "purpose": 'binary search in sorted range', "category": 'cpp_algorithm'},
    'std::lower_bound': {"lib": 'libc++', "purpose": 'lower bound in sorted range', "category": 'cpp_algorithm'},
    'std::upper_bound': {"lib": 'libc++', "purpose": 'upper bound in sorted range', "category": 'cpp_algorithm'},
    'std::find': {"lib": 'libc++', "purpose": 'find element in range', "category": 'cpp_algorithm'},
    'std::find_if': {"lib": 'libc++', "purpose": 'find element by predicate', "category": 'cpp_algorithm'},
    'std::count': {"lib": 'libc++', "purpose": 'count elements', "category": 'cpp_algorithm'},
    'std::count_if': {"lib": 'libc++', "purpose": 'count elements by predicate', "category": 'cpp_algorithm'},
    'std::copy': {"lib": 'libc++', "purpose": 'copy range', "category": 'cpp_algorithm'},
    'std::move': {"lib": 'libc++', "purpose": 'move range (or cast to rvalue)', "category": 'cpp_algorithm'},
    'std::fill': {"lib": 'libc++', "purpose": 'fill range with value', "category": 'cpp_algorithm'},
    'std::transform': {"lib": 'libc++', "purpose": 'transform range', "category": 'cpp_algorithm'},
    'std::accumulate': {"lib": 'libc++', "purpose": 'accumulate range', "category": 'cpp_algorithm'},
    'std::for_each': {"lib": 'libc++', "purpose": 'apply function to range', "category": 'cpp_algorithm'},
    'std::remove_if': {"lib": 'libc++', "purpose": 'remove elements by predicate', "category": 'cpp_algorithm'},
    'std::unique': {"lib": 'libc++', "purpose": 'remove consecutive duplicates', "category": 'cpp_algorithm'},
    'std::reverse': {"lib": 'libc++', "purpose": 'reverse range', "category": 'cpp_algorithm'},
    'std::min_element': {"lib": 'libc++', "purpose": 'find minimum element', "category": 'cpp_algorithm'},
    'std::max_element': {"lib": 'libc++', "purpose": 'find maximum element', "category": 'cpp_algorithm'},
    'std::swap': {"lib": 'libc++', "purpose": 'swap two values', "category": 'cpp_algorithm'},
    'std::make_shared': {"lib": 'libc++', "purpose": 'create shared_ptr', "category": 'cpp_memory'},
    'std::make_unique': {"lib": 'libc++', "purpose": 'create unique_ptr', "category": 'cpp_memory'},
    'std::shared_ptr::shared_ptr': {"lib": 'libc++', "purpose": 'shared_ptr constructor', "category": 'cpp_memory'},
    'std::shared_ptr::reset': {"lib": 'libc++', "purpose": 'reset shared_ptr', "category": 'cpp_memory'},
    'std::shared_ptr::get': {"lib": 'libc++', "purpose": 'get shared_ptr raw pointer', "category": 'cpp_memory'},
    'std::shared_ptr::use_count': {"lib": 'libc++', "purpose": 'get shared_ptr reference count', "category": 'cpp_memory'},
    'std::unique_ptr::unique_ptr': {"lib": 'libc++', "purpose": 'unique_ptr constructor', "category": 'cpp_memory'},
    'std::unique_ptr::reset': {"lib": 'libc++', "purpose": 'reset unique_ptr', "category": 'cpp_memory'},
    'std::unique_ptr::release': {"lib": 'libc++', "purpose": 'release unique_ptr ownership', "category": 'cpp_memory'},
    'std::unique_ptr::get': {"lib": 'libc++', "purpose": 'get unique_ptr raw pointer', "category": 'cpp_memory'},
    'std::weak_ptr::lock': {"lib": 'libc++', "purpose": 'lock weak_ptr to shared_ptr', "category": 'cpp_memory'},
    'std::weak_ptr::expired': {"lib": 'libc++', "purpose": 'check if weak_ptr expired', "category": 'cpp_memory'},
    'std::mutex::lock': {"lib": 'libc++', "purpose": 'lock std::mutex', "category": 'cpp_thread'},
    'std::mutex::unlock': {"lib": 'libc++', "purpose": 'unlock std::mutex', "category": 'cpp_thread'},
    'std::mutex::try_lock': {"lib": 'libc++', "purpose": 'try lock std::mutex', "category": 'cpp_thread'},
    'std::recursive_mutex::lock': {"lib": 'libc++', "purpose": 'lock recursive mutex', "category": 'cpp_thread'},
    'std::recursive_mutex::unlock': {"lib": 'libc++', "purpose": 'unlock recursive mutex', "category": 'cpp_thread'},
    'std::condition_variable::wait': {"lib": 'libc++', "purpose": 'wait on condition variable', "category": 'cpp_thread'},
    'std::condition_variable::notify_one': {"lib": 'libc++', "purpose": 'notify one waiter', "category": 'cpp_thread'},
    'std::condition_variable::notify_all': {"lib": 'libc++', "purpose": 'notify all waiters', "category": 'cpp_thread'},
    'std::thread::thread': {"lib": 'libc++', "purpose": 'std::thread constructor', "category": 'cpp_thread'},
    'std::thread::join': {"lib": 'libc++', "purpose": 'join std::thread', "category": 'cpp_thread'},
    'std::thread::detach': {"lib": 'libc++', "purpose": 'detach std::thread', "category": 'cpp_thread'},
    'std::async': {"lib": 'libc++', "purpose": 'launch async task', "category": 'cpp_thread'},
    'std::future::get': {"lib": 'libc++', "purpose": 'get future result', "category": 'cpp_thread'},
    'std::future::wait': {"lib": 'libc++', "purpose": 'wait for future result', "category": 'cpp_thread'},
    'std::promise::set_value': {"lib": 'libc++', "purpose": 'set promise value', "category": 'cpp_thread'},
    'std::promise::set_exception': {"lib": 'libc++', "purpose": 'set promise exception', "category": 'cpp_thread'},
    'std::fstream::open': {"lib": 'libc++', "purpose": 'open file stream', "category": 'cpp_io'},
    'std::fstream::close': {"lib": 'libc++', "purpose": 'close file stream', "category": 'cpp_io'},
    'std::ifstream::open': {"lib": 'libc++', "purpose": 'open input file stream', "category": 'cpp_io'},
    'std::ofstream::open': {"lib": 'libc++', "purpose": 'open output file stream', "category": 'cpp_io'},
    'std::stringstream::str': {"lib": 'libc++', "purpose": 'get/set stringstream string', "category": 'cpp_io'},
    'std::getline': {"lib": 'libc++', "purpose": 'read line from stream', "category": 'cpp_io'},
    'std::stoi': {"lib": 'libc++', "purpose": 'string to int', "category": 'cpp_stl'},
    'std::stol': {"lib": 'libc++', "purpose": 'string to long', "category": 'cpp_stl'},
    'std::stoll': {"lib": 'libc++', "purpose": 'string to long long', "category": 'cpp_stl'},
    'std::stof': {"lib": 'libc++', "purpose": 'string to float', "category": 'cpp_stl'},
    'std::stod': {"lib": 'libc++', "purpose": 'string to double', "category": 'cpp_stl'},
    'std::to_string': {"lib": 'libc++', "purpose": 'number to string', "category": 'cpp_stl'},
    'std::regex_search': {"lib": 'libc++', "purpose": 'search for regex match', "category": 'cpp_stl'},
    'std::regex_match': {"lib": 'libc++', "purpose": 'test full regex match', "category": 'cpp_stl'},
    'std::regex_replace': {"lib": 'libc++', "purpose": 'regex replace', "category": 'cpp_stl'},
    'std::filesystem::exists': {"lib": 'libc++', "purpose": 'check if path exists (C++17)', "category": 'cpp_fs'},
    'std::filesystem::create_directory': {"lib": 'libc++', "purpose": 'create directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::create_directories': {"lib": 'libc++', "purpose": 'create directory tree (C++17)', "category": 'cpp_fs'},
    'std::filesystem::remove': {"lib": 'libc++', "purpose": 'remove file/directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::remove_all': {"lib": 'libc++', "purpose": 'remove recursively (C++17)', "category": 'cpp_fs'},
    'std::filesystem::rename': {"lib": 'libc++', "purpose": 'rename file/directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::copy': {"lib": 'libc++', "purpose": 'copy file (C++17)', "category": 'cpp_fs'},
    'std::filesystem::copy_file': {"lib": 'libc++', "purpose": 'copy regular file (C++17)', "category": 'cpp_fs'},
    'std::filesystem::file_size': {"lib": 'libc++', "purpose": 'get file size (C++17)', "category": 'cpp_fs'},
    'std::filesystem::current_path': {"lib": 'libc++', "purpose": 'get/set current directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::is_regular_file': {"lib": 'libc++', "purpose": 'check if regular file (C++17)', "category": 'cpp_fs'},
    'std::filesystem::is_directory': {"lib": 'libc++', "purpose": 'check if directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::directory_iterator': {"lib": 'libc++', "purpose": 'iterate directory (C++17)', "category": 'cpp_fs'},
    'std::filesystem::recursive_directory_iterator': {"lib": 'libc++', "purpose": 'iterate directory tree (C++17)', "category": 'cpp_fs'},
    'std::filesystem::path::extension': {"lib": 'libc++', "purpose": 'get path extension (C++17)', "category": 'cpp_fs'},
    'std::filesystem::path::stem': {"lib": 'libc++', "purpose": 'get path stem (C++17)', "category": 'cpp_fs'},
    'std::filesystem::path::parent_path': {"lib": 'libc++', "purpose": 'get parent path (C++17)', "category": 'cpp_fs'},
    'std::filesystem::path::filename': {"lib": 'libc++', "purpose": 'get filename component (C++17)', "category": 'cpp_fs'},
    'std::filesystem::absolute': {"lib": 'libc++', "purpose": 'get absolute path (C++17)', "category": 'cpp_fs'},
    'std::filesystem::canonical': {"lib": 'libc++', "purpose": 'get canonical path (C++17)', "category": 'cpp_fs'},
    'std::filesystem::temp_directory_path': {"lib": 'libc++', "purpose": 'get temp directory (C++17)', "category": 'cpp_fs'},
    '__cxa_throw': {"lib": 'libc++abi', "purpose": 'throw C++ exception', "category": 'cpp_exception'},
    '__cxa_begin_catch': {"lib": 'libc++abi', "purpose": 'begin C++ catch block', "category": 'cpp_exception'},
    '__cxa_end_catch': {"lib": 'libc++abi', "purpose": 'end C++ catch block', "category": 'cpp_exception'},
    '__cxa_rethrow': {"lib": 'libc++abi', "purpose": 'rethrow current C++ exception', "category": 'cpp_exception'},
    '__cxa_allocate_exception': {"lib": 'libc++abi', "purpose": 'allocate exception object', "category": 'cpp_exception'},
    '__cxa_free_exception': {"lib": 'libc++abi', "purpose": 'free exception object', "category": 'cpp_exception'},
    '__cxa_get_exception_ptr': {"lib": 'libc++abi', "purpose": 'get exception pointer', "category": 'cpp_exception'},
    '__cxa_current_exception_type': {"lib": 'libc++abi', "purpose": 'get current exception type info', "category": 'cpp_exception'},
    '__gxx_personality_v0': {"lib": 'libc++abi', "purpose": 'GCC/Clang exception personality function', "category": 'cpp_exception'},
    '__cxa_guard_acquire': {"lib": 'libc++abi', "purpose": 'acquire static init guard', "category": 'cpp_runtime'},
    '__cxa_guard_release': {"lib": 'libc++abi', "purpose": 'release static init guard', "category": 'cpp_runtime'},
    '__cxa_guard_abort': {"lib": 'libc++abi', "purpose": 'abort static initialization', "category": 'cpp_runtime'},
    '__cxa_atexit': {"lib": 'libc++abi', "purpose": 'register destructor for static/global', "category": 'cpp_runtime'},
    '__cxa_finalize': {"lib": 'libc++abi', "purpose": 'call registered destructors at exit', "category": 'cpp_runtime'},
    '__cxa_demangle': {"lib": 'libc++abi', "purpose": 'demangle C++ symbol name', "category": 'cpp_runtime'},
    '__cxa_pure_virtual': {"lib": 'libc++abi', "purpose": 'pure virtual function call handler', "category": 'cpp_runtime'},
    '__cxa_deleted_virtual': {"lib": 'libc++abi', "purpose": 'deleted virtual function call handler', "category": 'cpp_runtime'},
    'operator new': {"lib": 'libc++', "purpose": 'C++ global operator new', "category": 'cpp_memory'},
    'operator new[]': {"lib": 'libc++', "purpose": 'C++ global operator new[]', "category": 'cpp_memory'},
    'operator delete': {"lib": 'libc++', "purpose": 'C++ global operator delete', "category": 'cpp_memory'},
    'operator delete[]': {"lib": 'libc++', "purpose": 'C++ global operator delete[]', "category": 'cpp_memory'},
    'sin': {"lib": 'libm', "purpose": 'sine', "category": 'math'},
    'cos': {"lib": 'libm', "purpose": 'cosine', "category": 'math'},
    'tan': {"lib": 'libm', "purpose": 'tangent', "category": 'math'},
    'asin': {"lib": 'libm', "purpose": 'arc sine', "category": 'math'},
    'acos': {"lib": 'libm', "purpose": 'arc cosine', "category": 'math'},
    'atan': {"lib": 'libm', "purpose": 'arc tangent', "category": 'math'},
    'atan2': {"lib": 'libm', "purpose": 'arc tangent of y/x', "category": 'math'},
    'sinh': {"lib": 'libm', "purpose": 'hyperbolic sine', "category": 'math'},
    'cosh': {"lib": 'libm', "purpose": 'hyperbolic cosine', "category": 'math'},
    'tanh': {"lib": 'libm', "purpose": 'hyperbolic tangent', "category": 'math'},
    'asinh': {"lib": 'libm', "purpose": 'inverse hyperbolic sine', "category": 'math'},
    'acosh': {"lib": 'libm', "purpose": 'inverse hyperbolic cosine', "category": 'math'},
    'atanh': {"lib": 'libm', "purpose": 'inverse hyperbolic tangent', "category": 'math'},
    'exp': {"lib": 'libm', "purpose": 'exponential (e^x)', "category": 'math'},
    'exp2': {"lib": 'libm', "purpose": 'base-2 exponential (2^x)', "category": 'math'},
    'expm1': {"lib": 'libm', "purpose": 'e^x - 1 (precise for small x)', "category": 'math'},
    'log': {"lib": 'libm', "purpose": 'natural logarithm', "category": 'math'},
    'log2': {"lib": 'libm', "purpose": 'base-2 logarithm', "category": 'math'},
    'log10': {"lib": 'libm', "purpose": 'base-10 logarithm', "category": 'math'},
    'log1p': {"lib": 'libm', "purpose": 'log(1+x) (precise for small x)', "category": 'math'},
    'pow': {"lib": 'libm', "purpose": 'raise to power', "category": 'math'},
    'sqrt': {"lib": 'libm', "purpose": 'square root', "category": 'math'},
    'cbrt': {"lib": 'libm', "purpose": 'cube root', "category": 'math'},
    'hypot': {"lib": 'libm', "purpose": 'hypotenuse (sqrt(x^2+y^2))', "category": 'math'},
    'fabs': {"lib": 'libm', "purpose": 'absolute value (float)', "category": 'math'},
    'fabsf': {"lib": 'libm', "purpose": 'absolute value (float32)', "category": 'math'},
    'ceil': {"lib": 'libm', "purpose": 'ceiling (round up)', "category": 'math'},
    'ceilf': {"lib": 'libm', "purpose": 'ceiling float32', "category": 'math'},
    'floor': {"lib": 'libm', "purpose": 'floor (round down)', "category": 'math'},
    'floorf': {"lib": 'libm', "purpose": 'floor float32', "category": 'math'},
    'round': {"lib": 'libm', "purpose": 'round to nearest integer', "category": 'math'},
    'roundf': {"lib": 'libm', "purpose": 'round float32', "category": 'math'},
    'trunc': {"lib": 'libm', "purpose": 'truncate toward zero', "category": 'math'},
    'truncf': {"lib": 'libm', "purpose": 'truncate float32', "category": 'math'},
    'fmod': {"lib": 'libm', "purpose": 'floating-point modulo', "category": 'math'},
    'fmodf': {"lib": 'libm', "purpose": 'floating-point modulo float32', "category": 'math'},
    'remainder': {"lib": 'libm', "purpose": 'IEEE remainder', "category": 'math'},
    'fmin': {"lib": 'libm', "purpose": 'minimum of two floats', "category": 'math'},
    'fmax': {"lib": 'libm', "purpose": 'maximum of two floats', "category": 'math'},
    'fminf': {"lib": 'libm', "purpose": 'minimum float32', "category": 'math'},
    'fmaxf': {"lib": 'libm', "purpose": 'maximum float32', "category": 'math'},
    'copysign': {"lib": 'libm', "purpose": 'copy sign of float', "category": 'math'},
    'isnan': {"lib": 'libm', "purpose": 'check if NaN', "category": 'math'},
    'isinf': {"lib": 'libm', "purpose": 'check if infinity', "category": 'math'},
    'isfinite': {"lib": 'libm', "purpose": 'check if finite', "category": 'math'},
    'nan': {"lib": 'libm', "purpose": 'generate quiet NaN', "category": 'math'},
    'frexp': {"lib": 'libm', "purpose": 'extract exponent and mantissa', "category": 'math'},
    'ldexp': {"lib": 'libm', "purpose": 'multiply by power of 2', "category": 'math'},
    'modf': {"lib": 'libm', "purpose": 'split into integer and fractional parts', "category": 'math'},
    'nextafter': {"lib": 'libm', "purpose": 'next representable float', "category": 'math'},
    'scalbn': {"lib": 'libm', "purpose": 'scale by power of radix', "category": 'math'},
    'lgamma': {"lib": 'libm', "purpose": 'log-gamma function', "category": 'math'},
    'tgamma': {"lib": 'libm', "purpose": 'gamma function', "category": 'math'},
    'erf': {"lib": 'libm', "purpose": 'error function', "category": 'math'},
    'erfc': {"lib": 'libm', "purpose": 'complementary error function', "category": 'math'},
    'j0': {"lib": 'libm', "purpose": 'Bessel function J0', "category": 'math'},
    'j1': {"lib": 'libm', "purpose": 'Bessel function J1', "category": 'math'},
    'sinf': {"lib": 'libm', "purpose": 'sine float32', "category": 'math'},
    'cosf': {"lib": 'libm', "purpose": 'cosine float32', "category": 'math'},
    'tanf': {"lib": 'libm', "purpose": 'tangent float32', "category": 'math'},
    'sqrtf': {"lib": 'libm', "purpose": 'square root float32', "category": 'math'},
    'powf': {"lib": 'libm', "purpose": 'power float32', "category": 'math'},
    'logf': {"lib": 'libm', "purpose": 'natural log float32', "category": 'math'},
    'expf': {"lib": 'libm', "purpose": 'exponential float32', "category": 'math'},
}


# -------------------------------------------------------------------------
# mega_batch_2 (260 entry, KARMA) — Objective-C runtime + NSObject/Foundation
# + Swift + Swift concurrency. Kaynak: signature_db.py satir 5948-6220.
# NOT: Karma kategoriler (objc_runtime/foundation/swift*) tek dict'te;
# re-categorize islemi sonraki fazlara ait.
# -------------------------------------------------------------------------
_MEGA_BATCH_2_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    '_objc_msgSend': {"lib": 'libobjc', "purpose": 'send ObjC message (primary dispatch)', "category": 'objc_runtime'},
    '_objc_msgSendSuper': {"lib": 'libobjc', "purpose": 'send ObjC message to super', "category": 'objc_runtime'},
    '_objc_msgSendSuper2': {"lib": 'libobjc', "purpose": 'send ObjC message to super (v2)', "category": 'objc_runtime'},
    '_objc_msgSend_stret': {"lib": 'libobjc', "purpose": 'send ObjC message returning struct', "category": 'objc_runtime'},
    '_objc_msgSend_fpret': {"lib": 'libobjc', "purpose": 'send ObjC message returning float', "category": 'objc_runtime'},
    '_objc_retain': {"lib": 'libobjc', "purpose": 'ARC retain object', "category": 'objc_runtime'},
    '_objc_release': {"lib": 'libobjc', "purpose": 'ARC release object', "category": 'objc_runtime'},
    '_objc_autorelease': {"lib": 'libobjc', "purpose": 'ARC autorelease object', "category": 'objc_runtime'},
    '_objc_autoreleaseReturnValue': {"lib": 'libobjc', "purpose": 'ARC autorelease return value', "category": 'objc_runtime'},
    '_objc_retainAutoreleasedReturnValue': {"lib": 'libobjc', "purpose": 'ARC retain autoreleased return', "category": 'objc_runtime'},
    '_objc_retainAutoreleaseReturnValue': {"lib": 'libobjc', "purpose": 'ARC retain+autorelease return', "category": 'objc_runtime'},
    '_objc_storeStrong': {"lib": 'libobjc', "purpose": 'ARC store strong reference', "category": 'objc_runtime'},
    '_objc_storeWeak': {"lib": 'libobjc', "purpose": 'ARC store weak reference', "category": 'objc_runtime'},
    '_objc_loadWeakRetained': {"lib": 'libobjc', "purpose": 'ARC load and retain weak ref', "category": 'objc_runtime'},
    '_objc_destroyWeak': {"lib": 'libobjc', "purpose": 'ARC destroy weak reference', "category": 'objc_runtime'},
    '_objc_initWeak': {"lib": 'libobjc', "purpose": 'ARC initialize weak reference', "category": 'objc_runtime'},
    '_objc_moveWeak': {"lib": 'libobjc', "purpose": 'ARC move weak reference', "category": 'objc_runtime'},
    '_objc_copyWeak': {"lib": 'libobjc', "purpose": 'ARC copy weak reference', "category": 'objc_runtime'},
    '_objc_autoreleasePoolPush': {"lib": 'libobjc', "purpose": 'push autorelease pool', "category": 'objc_runtime'},
    '_objc_autoreleasePoolPop': {"lib": 'libobjc', "purpose": 'pop autorelease pool', "category": 'objc_runtime'},
    '_objc_alloc': {"lib": 'libobjc', "purpose": 'allocate ObjC object', "category": 'objc_runtime'},
    '_objc_alloc_init': {"lib": 'libobjc', "purpose": 'alloc + init ObjC object', "category": 'objc_runtime'},
    '_objc_allocWithZone': {"lib": 'libobjc', "purpose": 'allocate in memory zone', "category": 'objc_runtime'},
    '_objc_opt_new': {"lib": 'libobjc', "purpose": 'optimized +new', "category": 'objc_runtime'},
    '_objc_opt_self': {"lib": 'libobjc', "purpose": 'optimized +self', "category": 'objc_runtime'},
    '_objc_opt_class': {"lib": 'libobjc', "purpose": 'optimized +class', "category": 'objc_runtime'},
    '_objc_opt_isKindOfClass': {"lib": 'libobjc', "purpose": 'optimized -isKindOfClass:', "category": 'objc_runtime'},
    '_objc_opt_respondsToSelector': {"lib": 'libobjc', "purpose": 'optimized -respondsToSelector:', "category": 'objc_runtime'},
    '_objc_getClass': {"lib": 'libobjc', "purpose": 'get ObjC class by name', "category": 'objc_runtime'},
    '_objc_getMetaClass': {"lib": 'libobjc', "purpose": 'get ObjC metaclass by name', "category": 'objc_runtime'},
    '_objc_lookUpClass': {"lib": 'libobjc', "purpose": 'lookup ObjC class (nil if not found)', "category": 'objc_runtime'},
    '_class_getName': {"lib": 'libobjc', "purpose": 'get ObjC class name', "category": 'objc_runtime'},
    '_class_getSuperclass': {"lib": 'libobjc', "purpose": 'get ObjC superclass', "category": 'objc_runtime'},
    '_class_getInstanceMethod': {"lib": 'libobjc', "purpose": 'get instance method', "category": 'objc_runtime'},
    '_class_getClassMethod': {"lib": 'libobjc', "purpose": 'get class method', "category": 'objc_runtime'},
    '_class_addMethod': {"lib": 'libobjc', "purpose": 'add method to class', "category": 'objc_runtime'},
    '_class_replaceMethod': {"lib": 'libobjc', "purpose": 'replace method implementation', "category": 'objc_runtime'},
    '_class_getInstanceSize': {"lib": 'libobjc', "purpose": 'get instance size', "category": 'objc_runtime'},
    '_class_getProperty': {"lib": 'libobjc', "purpose": 'get class property', "category": 'objc_runtime'},
    '_class_copyPropertyList': {"lib": 'libobjc', "purpose": 'copy property list', "category": 'objc_runtime'},
    '_class_copyMethodList': {"lib": 'libobjc', "purpose": 'copy method list', "category": 'objc_runtime'},
    '_class_copyIvarList': {"lib": 'libobjc', "purpose": 'copy ivar list', "category": 'objc_runtime'},
    '_class_conformsToProtocol': {"lib": 'libobjc', "purpose": 'check protocol conformance', "category": 'objc_runtime'},
    '_class_isMetaClass': {"lib": 'libobjc', "purpose": 'check if metaclass', "category": 'objc_runtime'},
    '_object_getClass': {"lib": 'libobjc', "purpose": "get object's class", "category": 'objc_runtime'},
    '_object_setClass': {"lib": 'libobjc', "purpose": "set object's class (isa swizzle)", "category": 'objc_runtime'},
    '_object_getClassName': {"lib": 'libobjc', "purpose": "get object's class name", "category": 'objc_runtime'},
    '_object_getIvar': {"lib": 'libobjc', "purpose": 'get ivar value', "category": 'objc_runtime'},
    '_object_setIvar': {"lib": 'libobjc', "purpose": 'set ivar value', "category": 'objc_runtime'},
    '_sel_getName': {"lib": 'libobjc', "purpose": 'get selector name string', "category": 'objc_runtime'},
    '_sel_registerName': {"lib": 'libobjc', "purpose": 'register selector name', "category": 'objc_runtime'},
    '_sel_getUid': {"lib": 'libobjc', "purpose": 'get selector UID', "category": 'objc_runtime'},
    '_method_getName': {"lib": 'libobjc', "purpose": 'get method selector', "category": 'objc_runtime'},
    '_method_getImplementation': {"lib": 'libobjc', "purpose": 'get method IMP pointer', "category": 'objc_runtime'},
    '_method_setImplementation': {"lib": 'libobjc', "purpose": 'set method IMP (method swizzling)', "category": 'objc_runtime'},
    '_method_exchangeImplementations': {"lib": 'libobjc', "purpose": 'swap two method IMPs', "category": 'objc_runtime'},
    '_method_getTypeEncoding': {"lib": 'libobjc', "purpose": 'get method type encoding', "category": 'objc_runtime'},
    '_ivar_getName': {"lib": 'libobjc', "purpose": 'get ivar name', "category": 'objc_runtime'},
    '_ivar_getOffset': {"lib": 'libobjc', "purpose": 'get ivar offset', "category": 'objc_runtime'},
    '_ivar_getTypeEncoding': {"lib": 'libobjc', "purpose": 'get ivar type encoding', "category": 'objc_runtime'},
    '_protocol_getName': {"lib": 'libobjc', "purpose": 'get protocol name', "category": 'objc_runtime'},
    '_protocol_conformsToProtocol': {"lib": 'libobjc', "purpose": 'check protocol inheritance', "category": 'objc_runtime'},
    '_protocol_copyMethodDescriptionList': {"lib": 'libobjc', "purpose": 'copy protocol method list', "category": 'objc_runtime'},
    '_objc_setAssociatedObject': {"lib": 'libobjc', "purpose": 'set associated object (runtime attach)', "category": 'objc_runtime'},
    '_objc_getAssociatedObject': {"lib": 'libobjc', "purpose": 'get associated object', "category": 'objc_runtime'},
    '_objc_removeAssociatedObjects': {"lib": 'libobjc', "purpose": 'remove all associated objects', "category": 'objc_runtime'},
    '_objc_constructInstance': {"lib": 'libobjc', "purpose": 'construct instance at memory', "category": 'objc_runtime'},
    '_objc_destructInstance': {"lib": 'libobjc', "purpose": 'destruct instance without free', "category": 'objc_runtime'},
    '_objc_enumerationMutation': {"lib": 'libobjc', "purpose": 'fast enumeration mutation handler', "category": 'objc_runtime'},
    '_objc_exception_throw': {"lib": 'libobjc', "purpose": 'throw ObjC exception', "category": 'objc_runtime'},
    '_objc_exception_rethrow': {"lib": 'libobjc', "purpose": 'rethrow ObjC exception', "category": 'objc_runtime'},
    '_objc_begin_catch': {"lib": 'libobjc', "purpose": 'begin ObjC catch block', "category": 'objc_runtime'},
    '_objc_end_catch': {"lib": 'libobjc', "purpose": 'end ObjC catch block', "category": 'objc_runtime'},
    '_objc_terminate': {"lib": 'libobjc', "purpose": 'ObjC terminate handler', "category": 'objc_runtime'},
    '_objc_sync_enter': {"lib": 'libobjc', "purpose": '@synchronized enter', "category": 'objc_runtime'},
    '_objc_sync_exit': {"lib": 'libobjc', "purpose": '@synchronized exit', "category": 'objc_runtime'},
    '_NSLog': {"lib": 'Foundation', "purpose": 'Foundation formatted logging', "category": 'foundation'},
    '_NSLogv': {"lib": 'Foundation', "purpose": 'Foundation formatted logging (va_list)', "category": 'foundation'},
    '_NSStringFromClass': {"lib": 'Foundation', "purpose": 'class name to NSString', "category": 'foundation'},
    '_NSClassFromString': {"lib": 'Foundation', "purpose": 'NSString to class', "category": 'foundation'},
    '_NSSelectorFromString': {"lib": 'Foundation', "purpose": 'NSString to SEL', "category": 'foundation'},
    '_NSStringFromSelector': {"lib": 'Foundation', "purpose": 'SEL to NSString', "category": 'foundation'},
    '_NSHomeDirectory': {"lib": 'Foundation', "purpose": 'get user home directory', "category": 'foundation'},
    '_NSTemporaryDirectory': {"lib": 'Foundation', "purpose": 'get temp directory', "category": 'foundation'},
    '_NSSearchPathForDirectoriesInDomains': {"lib": 'Foundation', "purpose": 'search system directories', "category": 'foundation'},
    '_NSUserName': {"lib": 'Foundation', "purpose": 'get current user name', "category": 'foundation'},
    '_NSFullUserName': {"lib": 'Foundation', "purpose": 'get full user name', "category": 'foundation'},
    '-[NSObject init]': {"lib": 'Foundation', "purpose": 'NSObject init', "category": 'foundation'},
    '-[NSObject dealloc]': {"lib": 'Foundation', "purpose": 'NSObject dealloc', "category": 'foundation'},
    '-[NSObject copy]': {"lib": 'Foundation', "purpose": 'NSObject copy', "category": 'foundation'},
    '-[NSObject mutableCopy]': {"lib": 'Foundation', "purpose": 'NSObject mutable copy', "category": 'foundation'},
    '-[NSObject respondsToSelector:]': {"lib": 'Foundation', "purpose": 'check method availability', "category": 'foundation'},
    '-[NSObject performSelector:]': {"lib": 'Foundation', "purpose": 'perform selector dynamically', "category": 'foundation'},
    '-[NSObject isKindOfClass:]': {"lib": 'Foundation', "purpose": 'check class type', "category": 'foundation'},
    '-[NSObject description]': {"lib": 'Foundation', "purpose": 'get object description', "category": 'foundation'},
    '+[NSString stringWithFormat:]': {"lib": 'Foundation', "purpose": 'create formatted NSString', "category": 'foundation'},
    '+[NSString stringWithUTF8String:]': {"lib": 'Foundation', "purpose": 'create NSString from UTF-8', "category": 'foundation'},
    '+[NSString stringWithContentsOfFile:encoding:error:]': {"lib": 'Foundation', "purpose": 'read file to NSString', "category": 'foundation'},
    '-[NSString UTF8String]': {"lib": 'Foundation', "purpose": 'get UTF-8 C string', "category": 'foundation'},
    '-[NSString length]': {"lib": 'Foundation', "purpose": 'get string length', "category": 'foundation'},
    '-[NSString isEqualToString:]': {"lib": 'Foundation', "purpose": 'compare strings', "category": 'foundation'},
    '-[NSString containsString:]': {"lib": 'Foundation', "purpose": 'check substring', "category": 'foundation'},
    '-[NSString hasPrefix:]': {"lib": 'Foundation', "purpose": 'check string prefix', "category": 'foundation'},
    '-[NSString hasSuffix:]': {"lib": 'Foundation', "purpose": 'check string suffix', "category": 'foundation'},
    '-[NSString stringByAppendingString:]': {"lib": 'Foundation', "purpose": 'append string', "category": 'foundation'},
    '-[NSString stringByAppendingPathComponent:]': {"lib": 'Foundation', "purpose": 'append path component', "category": 'foundation'},
    '-[NSString substringWithRange:]': {"lib": 'Foundation', "purpose": 'get substring by range', "category": 'foundation'},
    '-[NSString componentsSeparatedByString:]': {"lib": 'Foundation', "purpose": 'split string', "category": 'foundation'},
    '-[NSString lowercaseString]': {"lib": 'Foundation', "purpose": 'lowercase string', "category": 'foundation'},
    '-[NSString uppercaseString]': {"lib": 'Foundation', "purpose": 'uppercase string', "category": 'foundation'},
    '-[NSString dataUsingEncoding:]': {"lib": 'Foundation', "purpose": 'convert string to data', "category": 'foundation'},
    '-[NSString writeToFile:atomically:encoding:error:]': {"lib": 'Foundation', "purpose": 'write string to file', "category": 'foundation'},
    '+[NSMutableString stringWithCapacity:]': {"lib": 'Foundation', "purpose": 'create mutable string', "category": 'foundation'},
    '-[NSMutableString appendString:]': {"lib": 'Foundation', "purpose": 'append to mutable string', "category": 'foundation'},
    '-[NSMutableString appendFormat:]': {"lib": 'Foundation', "purpose": 'append formatted string', "category": 'foundation'},
    '+[NSArray arrayWithObjects:count:]': {"lib": 'Foundation', "purpose": 'create array from C array', "category": 'foundation'},
    '-[NSArray count]': {"lib": 'Foundation', "purpose": 'get array count', "category": 'foundation'},
    '-[NSArray objectAtIndex:]': {"lib": 'Foundation', "purpose": 'get array element', "category": 'foundation'},
    '-[NSArray objectAtIndexedSubscript:]': {"lib": 'Foundation', "purpose": 'array subscript access', "category": 'foundation'},
    '-[NSArray containsObject:]': {"lib": 'Foundation', "purpose": 'check if array contains', "category": 'foundation'},
    '-[NSArray enumerateObjectsUsingBlock:]': {"lib": 'Foundation', "purpose": 'enumerate array with block', "category": 'foundation'},
    '-[NSArray filteredArrayUsingPredicate:]': {"lib": 'Foundation', "purpose": 'filter array', "category": 'foundation'},
    '-[NSArray sortedArrayUsingComparator:]': {"lib": 'Foundation', "purpose": 'sort array', "category": 'foundation'},
    '-[NSMutableArray addObject:]': {"lib": 'Foundation', "purpose": 'add to mutable array', "category": 'foundation'},
    '-[NSMutableArray removeObjectAtIndex:]': {"lib": 'Foundation', "purpose": 'remove from mutable array', "category": 'foundation'},
    '-[NSMutableArray insertObject:atIndex:]': {"lib": 'Foundation', "purpose": 'insert into mutable array', "category": 'foundation'},
    '-[NSMutableArray removeAllObjects]': {"lib": 'Foundation', "purpose": 'clear mutable array', "category": 'foundation'},
    '+[NSDictionary dictionaryWithObjects:forKeys:count:]': {"lib": 'Foundation', "purpose": 'create dictionary', "category": 'foundation'},
    '-[NSDictionary objectForKey:]': {"lib": 'Foundation', "purpose": 'get dict value by key', "category": 'foundation'},
    '-[NSDictionary objectForKeyedSubscript:]': {"lib": 'Foundation', "purpose": 'dict subscript access', "category": 'foundation'},
    '-[NSDictionary count]': {"lib": 'Foundation', "purpose": 'get dict count', "category": 'foundation'},
    '-[NSDictionary allKeys]': {"lib": 'Foundation', "purpose": 'get all dict keys', "category": 'foundation'},
    '-[NSDictionary allValues]': {"lib": 'Foundation', "purpose": 'get all dict values', "category": 'foundation'},
    '-[NSDictionary enumerateKeysAndObjectsUsingBlock:]': {"lib": 'Foundation', "purpose": 'enumerate dict', "category": 'foundation'},
    '-[NSMutableDictionary setObject:forKey:]': {"lib": 'Foundation', "purpose": 'set dict value', "category": 'foundation'},
    '-[NSMutableDictionary removeObjectForKey:]': {"lib": 'Foundation', "purpose": 'remove dict value', "category": 'foundation'},
    '-[NSMutableDictionary removeAllObjects]': {"lib": 'Foundation', "purpose": 'clear dict', "category": 'foundation'},
    '+[NSData dataWithBytes:length:]': {"lib": 'Foundation', "purpose": 'create NSData from bytes', "category": 'foundation'},
    '+[NSData dataWithContentsOfFile:]': {"lib": 'Foundation', "purpose": 'read file to NSData', "category": 'foundation'},
    '+[NSData dataWithContentsOfURL:]': {"lib": 'Foundation', "purpose": 'read URL to NSData', "category": 'foundation'},
    '-[NSData bytes]': {"lib": 'Foundation', "purpose": 'get NSData byte pointer', "category": 'foundation'},
    '-[NSData length]': {"lib": 'Foundation', "purpose": 'get NSData length', "category": 'foundation'},
    '-[NSData writeToFile:atomically:]': {"lib": 'Foundation', "purpose": 'write NSData to file', "category": 'foundation'},
    '-[NSData subdataWithRange:]': {"lib": 'Foundation', "purpose": 'get NSData subrange', "category": 'foundation'},
    '+[NSFileManager defaultManager]': {"lib": 'Foundation', "purpose": 'get shared file manager', "category": 'foundation'},
    '-[NSFileManager fileExistsAtPath:]': {"lib": 'Foundation', "purpose": 'check if file exists', "category": 'foundation'},
    '-[NSFileManager createDirectoryAtPath:withIntermediateDirectories:attributes:error:]': {"lib": 'Foundation', "purpose": 'create directory', "category": 'foundation'},
    '-[NSFileManager removeItemAtPath:error:]': {"lib": 'Foundation', "purpose": 'remove file/directory', "category": 'foundation'},
    '-[NSFileManager copyItemAtPath:toPath:error:]': {"lib": 'Foundation', "purpose": 'copy file/directory', "category": 'foundation'},
    '-[NSFileManager moveItemAtPath:toPath:error:]': {"lib": 'Foundation', "purpose": 'move file/directory', "category": 'foundation'},
    '-[NSFileManager contentsOfDirectoryAtPath:error:]': {"lib": 'Foundation', "purpose": 'list directory', "category": 'foundation'},
    '-[NSFileManager attributesOfItemAtPath:error:]': {"lib": 'Foundation', "purpose": 'get file attributes', "category": 'foundation'},
    '+[NSJSONSerialization JSONObjectWithData:options:error:]': {"lib": 'Foundation', "purpose": 'parse JSON data', "category": 'foundation'},
    '+[NSJSONSerialization dataWithJSONObject:options:error:]': {"lib": 'Foundation', "purpose": 'serialize to JSON', "category": 'foundation'},
    '+[NSPropertyListSerialization propertyListWithData:options:format:error:]': {"lib": 'Foundation', "purpose": 'parse property list', "category": 'foundation'},
    '+[NSURLSession sharedSession]': {"lib": 'Foundation', "purpose": 'get shared URL session', "category": 'foundation'},
    '+[NSURLSession sessionWithConfiguration:]': {"lib": 'Foundation', "purpose": 'create URL session', "category": 'foundation'},
    '-[NSURLSession dataTaskWithRequest:completionHandler:]': {"lib": 'Foundation', "purpose": 'create data task', "category": 'foundation'},
    '-[NSURLSession downloadTaskWithRequest:completionHandler:]': {"lib": 'Foundation', "purpose": 'create download task', "category": 'foundation'},
    '-[NSURLSession uploadTaskWithRequest:fromData:completionHandler:]': {"lib": 'Foundation', "purpose": 'create upload task', "category": 'foundation'},
    '+[NSURLRequest requestWithURL:]': {"lib": 'Foundation', "purpose": 'create URL request', "category": 'foundation'},
    '+[NSNotificationCenter defaultCenter]': {"lib": 'Foundation', "purpose": 'get default notification center', "category": 'foundation'},
    '-[NSNotificationCenter addObserver:selector:name:object:]': {"lib": 'Foundation', "purpose": 'add notification observer', "category": 'foundation'},
    '-[NSNotificationCenter removeObserver:]': {"lib": 'Foundation', "purpose": 'remove notification observer', "category": 'foundation'},
    '-[NSNotificationCenter postNotificationName:object:]': {"lib": 'Foundation', "purpose": 'post notification', "category": 'foundation'},
    '-[NSUserDefaults objectForKey:]': {"lib": 'Foundation', "purpose": 'read user defaults value', "category": 'foundation'},
    '-[NSUserDefaults setObject:forKey:]': {"lib": 'Foundation', "purpose": 'write user defaults value', "category": 'foundation'},
    '-[NSUserDefaults synchronize]': {"lib": 'Foundation', "purpose": 'sync user defaults to disk', "category": 'foundation'},
    '+[NSUserDefaults standardUserDefaults]': {"lib": 'Foundation', "purpose": 'get standard user defaults', "category": 'foundation'},
    '+[NSDate date]': {"lib": 'Foundation', "purpose": 'create current date', "category": 'foundation'},
    '+[NSDate dateWithTimeIntervalSince1970:]': {"lib": 'Foundation', "purpose": 'create date from epoch', "category": 'foundation'},
    '-[NSDate timeIntervalSince1970]': {"lib": 'Foundation', "purpose": 'get epoch timestamp', "category": 'foundation'},
    '-[NSDate timeIntervalSinceDate:]': {"lib": 'Foundation', "purpose": 'time interval between dates', "category": 'foundation'},
    '+[NSDateFormatter new]': {"lib": 'Foundation', "purpose": 'create date formatter', "category": 'foundation'},
    '+[NSUUID UUID]': {"lib": 'Foundation', "purpose": 'generate UUID', "category": 'foundation'},
    '-[NSUUID UUIDString]': {"lib": 'Foundation', "purpose": 'get UUID string representation', "category": 'foundation'},
    '-[NSError localizedDescription]': {"lib": 'Foundation', "purpose": 'get error description', "category": 'foundation'},
    '-[NSError domain]': {"lib": 'Foundation', "purpose": 'get error domain', "category": 'foundation'},
    '-[NSError code]': {"lib": 'Foundation', "purpose": 'get error code', "category": 'foundation'},
    '+[NSError errorWithDomain:code:userInfo:]': {"lib": 'Foundation', "purpose": 'create NSError', "category": 'foundation'},
    '+[NSBundle mainBundle]': {"lib": 'Foundation', "purpose": 'get main app bundle', "category": 'foundation'},
    '-[NSBundle pathForResource:ofType:]': {"lib": 'Foundation', "purpose": 'get bundle resource path', "category": 'foundation'},
    '-[NSBundle bundleIdentifier]': {"lib": 'Foundation', "purpose": 'get bundle ID', "category": 'foundation'},
    '+[NSProcessInfo processInfo]': {"lib": 'Foundation', "purpose": 'get process info singleton', "category": 'foundation'},
    '-[NSProcessInfo processName]': {"lib": 'Foundation', "purpose": 'get process name', "category": 'foundation'},
    '-[NSProcessInfo arguments]': {"lib": 'Foundation', "purpose": 'get command line arguments', "category": 'foundation'},
    '-[NSProcessInfo environment]': {"lib": 'Foundation', "purpose": 'get environment dict', "category": 'foundation'},
    '-[NSProcessInfo operatingSystemVersion]': {"lib": 'Foundation', "purpose": 'get OS version', "category": 'foundation'},
    '-[NSProcessInfo physicalMemory]': {"lib": 'Foundation', "purpose": 'get physical memory bytes', "category": 'foundation'},
    '-[NSProcessInfo processorCount]': {"lib": 'Foundation', "purpose": 'get CPU count', "category": 'foundation'},
    '+[NSThread currentThread]': {"lib": 'Foundation', "purpose": 'get current thread', "category": 'foundation'},
    '+[NSThread isMainThread]': {"lib": 'Foundation', "purpose": 'check if main thread', "category": 'foundation'},
    '-[NSThread start]': {"lib": 'Foundation', "purpose": 'start NSThread', "category": 'foundation'},
    '-[NSThread cancel]': {"lib": 'Foundation', "purpose": 'cancel NSThread', "category": 'foundation'},
    '+[NSThread sleepForTimeInterval:]': {"lib": 'Foundation', "purpose": 'sleep thread', "category": 'foundation'},
    '-[NSLock lock]': {"lib": 'Foundation', "purpose": 'acquire NSLock', "category": 'foundation'},
    '-[NSLock unlock]': {"lib": 'Foundation', "purpose": 'release NSLock', "category": 'foundation'},
    '-[NSRecursiveLock lock]': {"lib": 'Foundation', "purpose": 'acquire recursive NSLock', "category": 'foundation'},
    '-[NSRecursiveLock unlock]': {"lib": 'Foundation', "purpose": 'release recursive NSLock', "category": 'foundation'},
    '-[NSCondition wait]': {"lib": 'Foundation', "purpose": 'wait on NSCondition', "category": 'foundation'},
    '-[NSCondition signal]': {"lib": 'Foundation', "purpose": 'signal NSCondition', "category": 'foundation'},
    '-[NSCondition broadcast]': {"lib": 'Foundation', "purpose": 'broadcast NSCondition', "category": 'foundation'},
    '+[NSOperationQueue mainQueue]': {"lib": 'Foundation', "purpose": 'get main operation queue', "category": 'foundation'},
    '-[NSOperationQueue addOperationWithBlock:]': {"lib": 'Foundation', "purpose": 'add block operation', "category": 'foundation'},
    '-[NSOperationQueue waitUntilAllOperationsAreFinished]': {"lib": 'Foundation', "purpose": 'wait for all operations', "category": 'foundation'},
    '-[NSTimer scheduledTimerWithTimeInterval:repeats:block:]': {"lib": 'Foundation', "purpose": 'schedule timer', "category": 'foundation'},
    '-[NSTimer invalidate]': {"lib": 'Foundation', "purpose": 'invalidate timer', "category": 'foundation'},
    '+[NSRegularExpression regularExpressionWithPattern:options:error:]': {"lib": 'Foundation', "purpose": 'create regex', "category": 'foundation'},
    '-[NSRegularExpression matchesInString:options:range:]': {"lib": 'Foundation', "purpose": 'find regex matches', "category": 'foundation'},
    '-[NSRegularExpression firstMatchInString:options:range:]': {"lib": 'Foundation', "purpose": 'find first regex match', "category": 'foundation'},
    '_swift_allocObject': {"lib": 'swift_runtime', "purpose": 'allocate Swift object', "category": 'swift'},
    '_swift_deallocObject': {"lib": 'swift_runtime', "purpose": 'deallocate Swift object', "category": 'swift'},
    '_swift_retain': {"lib": 'swift_runtime', "purpose": 'Swift ARC retain', "category": 'swift'},
    '_swift_release': {"lib": 'swift_runtime', "purpose": 'Swift ARC release', "category": 'swift'},
    '_swift_retain_n': {"lib": 'swift_runtime', "purpose": 'Swift retain n times', "category": 'swift'},
    '_swift_release_n': {"lib": 'swift_runtime', "purpose": 'Swift release n times', "category": 'swift'},
    '_swift_unownedRetain': {"lib": 'swift_runtime', "purpose": 'Swift unowned retain', "category": 'swift'},
    '_swift_unownedRelease': {"lib": 'swift_runtime', "purpose": 'Swift unowned release', "category": 'swift'},
    '_swift_weakLoadStrong': {"lib": 'swift_runtime', "purpose": 'load strong ref from weak', "category": 'swift'},
    '_swift_weakAssign': {"lib": 'swift_runtime', "purpose": 'assign weak reference', "category": 'swift'},
    '_swift_weakInit': {"lib": 'swift_runtime', "purpose": 'initialize weak reference', "category": 'swift'},
    '_swift_weakDestroy': {"lib": 'swift_runtime', "purpose": 'destroy weak reference', "category": 'swift'},
    '_swift_isUniquelyReferenced': {"lib": 'swift_runtime', "purpose": 'check unique reference (COW)', "category": 'swift'},
    '_swift_getTypeByMangledNameInContext': {"lib": 'swift_runtime', "purpose": 'resolve type by mangled name', "category": 'swift'},
    '_swift_getExistentialTypeMetadata': {"lib": 'swift_runtime', "purpose": 'get protocol type metadata', "category": 'swift'},
    '_swift_dynamicCast': {"lib": 'swift_runtime', "purpose": 'Swift dynamic cast (as?/as!)', "category": 'swift'},
    '_swift_dynamicCastClass': {"lib": 'swift_runtime', "purpose": 'Swift class dynamic cast', "category": 'swift'},
    '_swift_dynamicCastObjCClass': {"lib": 'swift_runtime', "purpose": 'Swift ObjC class dynamic cast', "category": 'swift'},
    '_swift_conformsToProtocol': {"lib": 'swift_runtime', "purpose": 'check Swift protocol conformance', "category": 'swift'},
    '_swift_allocBox': {"lib": 'swift_runtime', "purpose": 'allocate Swift box (heap closure capture)', "category": 'swift'},
    '_swift_deallocBox': {"lib": 'swift_runtime', "purpose": 'deallocate Swift box', "category": 'swift'},
    '_swift_makeBoxUnique': {"lib": 'swift_runtime', "purpose": 'make box unique (COW)', "category": 'swift'},
    '_swift_projectBox': {"lib": 'swift_runtime', "purpose": 'project value from box', "category": 'swift'},
    '_swift_bridgeObjectRetain': {"lib": 'swift_runtime', "purpose": 'retain bridged ObjC object', "category": 'swift'},
    '_swift_bridgeObjectRelease': {"lib": 'swift_runtime', "purpose": 'release bridged ObjC object', "category": 'swift'},
    '_swift_errorRetain': {"lib": 'swift_runtime', "purpose": 'retain Swift Error', "category": 'swift'},
    '_swift_errorRelease': {"lib": 'swift_runtime', "purpose": 'release Swift Error', "category": 'swift'},
    '_swift_willThrow': {"lib": 'swift_runtime', "purpose": 'Swift will throw error (for debugger)', "category": 'swift'},
    '_swift_getObjCClassMetadata': {"lib": 'swift_runtime', "purpose": 'get ObjC interop metadata', "category": 'swift'},
    '_swift_lookUpClassMethod': {"lib": 'swift_runtime', "purpose": 'look up class method vtable entry', "category": 'swift'},
    '_swift_allocateGenericClassMetadata': {"lib": 'swift_runtime', "purpose": 'allocate generic class metadata', "category": 'swift'},
    '_swift_allocateGenericValueMetadata': {"lib": 'swift_runtime', "purpose": 'allocate generic value metadata', "category": 'swift'},
    '_swift_initClassMetadata2': {"lib": 'swift_runtime', "purpose": 'initialize class metadata', "category": 'swift'},
    '_swift_initStructMetadata': {"lib": 'swift_runtime', "purpose": 'initialize struct metadata', "category": 'swift'},
    '_swift_initEnumMetadataSingleCase': {"lib": 'swift_runtime', "purpose": 'init single-case enum metadata', "category": 'swift'},
    '_swift_initEnumMetadataMultiPayload': {"lib": 'swift_runtime', "purpose": 'init multi-payload enum metadata', "category": 'swift'},
    '_swift_getAssociatedTypeWitness': {"lib": 'swift_runtime', "purpose": 'get associated type from witness', "category": 'swift'},
    '_swift_getWitnessTable': {"lib": 'swift_runtime', "purpose": 'get protocol witness table', "category": 'swift'},
    '_swift_once': {"lib": 'swift_runtime', "purpose": 'Swift one-time initialization', "category": 'swift'},
    '_swift_beginAccess': {"lib": 'swift_runtime', "purpose": 'begin exclusivity access check', "category": 'swift'},
    '_swift_endAccess': {"lib": 'swift_runtime', "purpose": 'end exclusivity access check', "category": 'swift'},
    '_swift_task_create': {"lib": 'swift_runtime', "purpose": 'create Swift concurrency task', "category": 'swift_concurrency'},
    '_swift_task_switch': {"lib": 'swift_runtime', "purpose": 'switch Swift task (async/await)', "category": 'swift_concurrency'},
    '_swift_task_future_wait': {"lib": 'swift_runtime', "purpose": 'await Swift task future', "category": 'swift_concurrency'},
    '_swift_taskGroup_create': {"lib": 'swift_runtime', "purpose": 'create Swift task group', "category": 'swift_concurrency'},
    '_swift_taskGroup_addPending': {"lib": 'swift_runtime', "purpose": 'add pending task to group', "category": 'swift_concurrency'},
    '_swift_taskGroup_wait': {"lib": 'swift_runtime', "purpose": 'await task group completion', "category": 'swift_concurrency'},
    '_swift_asyncLet_begin': {"lib": 'swift_runtime', "purpose": 'begin async let binding', "category": 'swift_concurrency'},
    '_swift_asyncLet_end': {"lib": 'swift_runtime', "purpose": 'end async let binding', "category": 'swift_concurrency'},
    '_swift_continuation_resume': {"lib": 'swift_runtime', "purpose": 'resume continuation (withCheckedContinuation)', "category": 'swift_concurrency'},
}


# -------------------------------------------------------------------------
# Dispatcher hook — sigdb_builtin.get_category('game_ml') bu dict'i alir.
# Anahtar isimleri signature_db.py'deki orijinal dict adlariyla uyumludur.
# -------------------------------------------------------------------------
SIGNATURES: dict[str, Any] = {
    "ml_compute_signatures": _ML_COMPUTE_SIGNATURES_DATA,
    "game_engine_signatures": _GAME_ENGINE_SIGNATURES_DATA,
    "anti_analysis_signatures": _ANTI_ANALYSIS_SIGNATURES_DATA,
    "mega_batch_1_signatures": _MEGA_BATCH_1_SIGNATURES_DATA,
    "mega_batch_2_signatures": _MEGA_BATCH_2_SIGNATURES_DATA,
}


__all__ = ["SIGNATURES"]
