"""Windows GUI / security / graphics category signatures — sig_db Faz 7D dalgasi.

Bu modul Windows PE binary analizinde yaygin olan uc buyuk sistem DLL'i icin
YENI kapsama saglar. Kaynak: MSDN Windows API reference (offline bilgi; online
fetch YAPILMAMISTIR). pe_runtime.py pattern'i birebir takip edilir.

  1. ``user32_signatures``    — GUI core (pencere, mesaj loop, menu, kontrol,
                                dialog, timer, caret, clipboard, hook).
                                Hedef kapsama: ~150 entry.
  2. ``advapi32_signatures``  — Registry, service control, token/privilege,
                                legacy CryptoAPI, event logging, security.
                                Hedef kapsama: ~95 entry.
  3. ``gdi32_signatures``     — Graphics Device Interface: DC, pen, brush,
                                font, text, bitmap, path, region, metafile.
                                Hedef kapsama: ~70 entry.

Toplam: ~315 entry. YENI coverage — legacy'de ufak bir alt kumesi vardir:
  - ``_WIN32_USER32_GDI32_SIGNATURES`` (25 entry) — user32+gdi32 overlap
  - ``_WIN32_ADVAPI32_SIGNATURES``     (20 entry) — advapi32 overlap

Overlap entry'leri ayni ``lib`` / ``purpose`` / ``category`` tasir
(idempotent update); ``dict.update`` siralamasi farkli degil — bu modul
legacy'yi override EDER, ayni veriyi + genisletme dondurur.

Legacy dict'ler SILINMEDI; rollback icin override yontemi kullanilir
(crypto/compression/network/pe_runtime ile ayni desen).
"""
from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# user32.dll — Windows GUI subsystem core API.
# Pencere, mesaj loop, menu, dialog, input, caret, clipboard, hook vb.
# ---------------------------------------------------------------------------
_USER32_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # ---- Window management (create / destroy / show / move) ----
    "CreateWindowExA": {"lib": "user32", "purpose": "create overlapped/popup/child window (ANSI)", "category": "win_gui"},
    "CreateWindowExW": {"lib": "user32", "purpose": "create overlapped/popup/child window (Unicode)", "category": "win_gui"},
    "DestroyWindow": {"lib": "user32", "purpose": "destroy a window", "category": "win_gui"},
    "ShowWindow": {"lib": "user32", "purpose": "set window show state", "category": "win_gui"},
    "ShowWindowAsync": {"lib": "user32", "purpose": "set window show state asynchronously", "category": "win_gui"},
    "UpdateWindow": {"lib": "user32", "purpose": "send WM_PAINT if update region non-empty", "category": "win_gui"},
    "MoveWindow": {"lib": "user32", "purpose": "change window position and size", "category": "win_gui"},
    "SetWindowPos": {"lib": "user32", "purpose": "change size/position/Z-order of window", "category": "win_gui"},
    "GetWindowRect": {"lib": "user32", "purpose": "get window bounding rectangle (screen)", "category": "win_gui"},
    "GetClientRect": {"lib": "user32", "purpose": "get window client area rectangle", "category": "win_gui"},
    "AdjustWindowRect": {"lib": "user32", "purpose": "compute window rect from client rect", "category": "win_gui"},
    "AdjustWindowRectEx": {"lib": "user32", "purpose": "compute window rect with extended style", "category": "win_gui"},
    "ClientToScreen": {"lib": "user32", "purpose": "convert client coords to screen coords", "category": "win_gui"},
    "ScreenToClient": {"lib": "user32", "purpose": "convert screen coords to client coords", "category": "win_gui"},
    "MapWindowPoints": {"lib": "user32", "purpose": "map points between window coord spaces", "category": "win_gui"},
    "IsWindow": {"lib": "user32", "purpose": "check if handle is valid window", "category": "win_gui"},
    "IsWindowVisible": {"lib": "user32", "purpose": "check if window is visible", "category": "win_gui"},
    "IsWindowEnabled": {"lib": "user32", "purpose": "check if window accepts input", "category": "win_gui"},
    "IsWindowUnicode": {"lib": "user32", "purpose": "check if window is Unicode-subclassed", "category": "win_gui"},
    "IsIconic": {"lib": "user32", "purpose": "check if window is minimized", "category": "win_gui"},
    "IsZoomed": {"lib": "user32", "purpose": "check if window is maximized", "category": "win_gui"},
    "EnableWindow": {"lib": "user32", "purpose": "enable/disable mouse+keyboard input for window", "category": "win_gui"},
    "SetActiveWindow": {"lib": "user32", "purpose": "activate a top-level window", "category": "win_gui"},
    "GetActiveWindow": {"lib": "user32", "purpose": "get active window in calling thread", "category": "win_gui"},
    "SetForegroundWindow": {"lib": "user32", "purpose": "bring window to foreground", "category": "win_gui"},
    "GetForegroundWindow": {"lib": "user32", "purpose": "get handle to foreground window", "category": "win_gui"},
    "BringWindowToTop": {"lib": "user32", "purpose": "bring window to top of Z-order", "category": "win_gui"},
    "SetWindowTextA": {"lib": "user32", "purpose": "set window title/control text (ANSI)", "category": "win_gui"},
    "SetWindowTextW": {"lib": "user32", "purpose": "set window title/control text (Unicode)", "category": "win_gui"},
    "GetWindowTextA": {"lib": "user32", "purpose": "copy window title/control text (ANSI)", "category": "win_gui"},
    "GetWindowTextW": {"lib": "user32", "purpose": "copy window title/control text (Unicode)", "category": "win_gui"},
    "GetWindowTextLengthA": {"lib": "user32", "purpose": "length of window text (ANSI, chars)", "category": "win_gui"},
    "GetWindowTextLengthW": {"lib": "user32", "purpose": "length of window text (Unicode, chars)", "category": "win_gui"},
    "GetWindowLongA": {"lib": "user32", "purpose": "get 32-bit window attribute (ANSI)", "category": "win_gui"},
    "GetWindowLongW": {"lib": "user32", "purpose": "get 32-bit window attribute (Unicode)", "category": "win_gui"},
    "SetWindowLongA": {"lib": "user32", "purpose": "set 32-bit window attribute (ANSI)", "category": "win_gui"},
    "SetWindowLongW": {"lib": "user32", "purpose": "set 32-bit window attribute (Unicode)", "category": "win_gui"},
    "GetWindowLongPtrA": {"lib": "user32", "purpose": "get pointer-sized window attribute (ANSI)", "category": "win_gui"},
    "GetWindowLongPtrW": {"lib": "user32", "purpose": "get pointer-sized window attribute (Unicode)", "category": "win_gui"},
    "SetWindowLongPtrA": {"lib": "user32", "purpose": "set pointer-sized window attribute (ANSI)", "category": "win_gui"},
    "SetWindowLongPtrW": {"lib": "user32", "purpose": "set pointer-sized window attribute (Unicode)", "category": "win_gui"},
    "GetParent": {"lib": "user32", "purpose": "get parent window handle", "category": "win_gui"},
    "SetParent": {"lib": "user32", "purpose": "change parent window of child", "category": "win_gui"},
    "FindWindowA": {"lib": "user32", "purpose": "find top-level window by class/name (ANSI)", "category": "win_gui"},
    "FindWindowW": {"lib": "user32", "purpose": "find top-level window by class/name (Unicode)", "category": "win_gui"},
    "FindWindowExA": {"lib": "user32", "purpose": "find child window by class/name (ANSI)", "category": "win_gui"},
    "FindWindowExW": {"lib": "user32", "purpose": "find child window by class/name (Unicode)", "category": "win_gui"},
    "EnumWindows": {"lib": "user32", "purpose": "enumerate all top-level windows", "category": "win_gui"},
    "EnumChildWindows": {"lib": "user32", "purpose": "enumerate child windows", "category": "win_gui"},
    "EnumThreadWindows": {"lib": "user32", "purpose": "enumerate windows owned by thread", "category": "win_gui"},
    "GetDesktopWindow": {"lib": "user32", "purpose": "get handle to desktop window", "category": "win_gui"},
    "GetShellWindow": {"lib": "user32", "purpose": "get handle to shell's desktop window", "category": "win_gui"},
    "CloseWindow": {"lib": "user32", "purpose": "minimize (not destroy) a window", "category": "win_gui"},
    "AnimateWindow": {"lib": "user32", "purpose": "animate window show/hide", "category": "win_gui"},

    # ---- Message loop ----
    "GetMessageA": {"lib": "user32", "purpose": "retrieve message from queue (ANSI)", "category": "win_msg"},
    "GetMessageW": {"lib": "user32", "purpose": "retrieve message from queue (Unicode)", "category": "win_msg"},
    "PeekMessageA": {"lib": "user32", "purpose": "check message queue without blocking (ANSI)", "category": "win_msg"},
    "PeekMessageW": {"lib": "user32", "purpose": "check message queue without blocking (Unicode)", "category": "win_msg"},
    "TranslateMessage": {"lib": "user32", "purpose": "translate virtual-key messages to character messages", "category": "win_msg"},
    "TranslateAcceleratorA": {"lib": "user32", "purpose": "process accelerator key (ANSI)", "category": "win_msg"},
    "TranslateAcceleratorW": {"lib": "user32", "purpose": "process accelerator key (Unicode)", "category": "win_msg"},
    "DispatchMessageA": {"lib": "user32", "purpose": "dispatch message to window procedure (ANSI)", "category": "win_msg"},
    "DispatchMessageW": {"lib": "user32", "purpose": "dispatch message to window procedure (Unicode)", "category": "win_msg"},
    "PostMessageA": {"lib": "user32", "purpose": "post message to thread message queue (ANSI)", "category": "win_msg"},
    "PostMessageW": {"lib": "user32", "purpose": "post message to thread message queue (Unicode)", "category": "win_msg"},
    "SendMessageA": {"lib": "user32", "purpose": "send message directly to window procedure (ANSI)", "category": "win_msg"},
    "SendMessageW": {"lib": "user32", "purpose": "send message directly to window procedure (Unicode)", "category": "win_msg"},
    "SendMessageTimeoutA": {"lib": "user32", "purpose": "send message with timeout (ANSI)", "category": "win_msg"},
    "SendMessageTimeoutW": {"lib": "user32", "purpose": "send message with timeout (Unicode)", "category": "win_msg"},
    "SendNotifyMessageA": {"lib": "user32", "purpose": "send notify-style message (ANSI)", "category": "win_msg"},
    "SendNotifyMessageW": {"lib": "user32", "purpose": "send notify-style message (Unicode)", "category": "win_msg"},
    "PostThreadMessageA": {"lib": "user32", "purpose": "post message to specific thread (ANSI)", "category": "win_msg"},
    "PostThreadMessageW": {"lib": "user32", "purpose": "post message to specific thread (Unicode)", "category": "win_msg"},
    "PostQuitMessage": {"lib": "user32", "purpose": "post WM_QUIT to message queue", "category": "win_msg"},
    "ReplyMessage": {"lib": "user32", "purpose": "reply to incoming SendMessage", "category": "win_msg"},
    "InSendMessage": {"lib": "user32", "purpose": "check if handling SendMessage call", "category": "win_msg"},
    "InSendMessageEx": {"lib": "user32", "purpose": "extended SendMessage state query", "category": "win_msg"},
    "GetMessagePos": {"lib": "user32", "purpose": "cursor position when last message retrieved", "category": "win_msg"},
    "GetMessageTime": {"lib": "user32", "purpose": "time when last message was retrieved", "category": "win_msg"},
    "WaitMessage": {"lib": "user32", "purpose": "block thread until new message arrives", "category": "win_msg"},
    "MsgWaitForMultipleObjects": {"lib": "user32", "purpose": "wait for objects or input message", "category": "win_msg"},
    "MsgWaitForMultipleObjectsEx": {"lib": "user32", "purpose": "extended wait for objects or message", "category": "win_msg"},

    # ---- Window class / procedure ----
    "DefWindowProcA": {"lib": "user32", "purpose": "default window procedure (ANSI)", "category": "win_gui"},
    "DefWindowProcW": {"lib": "user32", "purpose": "default window procedure (Unicode)", "category": "win_gui"},
    "CallWindowProcA": {"lib": "user32", "purpose": "call window procedure (ANSI)", "category": "win_gui"},
    "CallWindowProcW": {"lib": "user32", "purpose": "call window procedure (Unicode)", "category": "win_gui"},
    "RegisterClassA": {"lib": "user32", "purpose": "register window class (ANSI)", "category": "win_gui"},
    "RegisterClassW": {"lib": "user32", "purpose": "register window class (Unicode)", "category": "win_gui"},
    "RegisterClassExA": {"lib": "user32", "purpose": "register window class (ANSI)", "category": "win_gui"},
    "RegisterClassExW": {"lib": "user32", "purpose": "register window class (Unicode)", "category": "win_gui"},
    "UnregisterClassA": {"lib": "user32", "purpose": "unregister window class (ANSI)", "category": "win_gui"},
    "UnregisterClassW": {"lib": "user32", "purpose": "unregister window class (Unicode)", "category": "win_gui"},
    "GetClassNameA": {"lib": "user32", "purpose": "get window class name (ANSI)", "category": "win_gui"},
    "GetClassNameW": {"lib": "user32", "purpose": "get window class name (Unicode)", "category": "win_gui"},
    "GetClassInfoA": {"lib": "user32", "purpose": "get class info (ANSI)", "category": "win_gui"},
    "GetClassInfoW": {"lib": "user32", "purpose": "get class info (Unicode)", "category": "win_gui"},
    "GetClassInfoExA": {"lib": "user32", "purpose": "get extended class info (ANSI)", "category": "win_gui"},
    "GetClassInfoExW": {"lib": "user32", "purpose": "get extended class info (Unicode)", "category": "win_gui"},
    "GetClassLongA": {"lib": "user32", "purpose": "get 32-bit class attribute (ANSI)", "category": "win_gui"},
    "GetClassLongW": {"lib": "user32", "purpose": "get 32-bit class attribute (Unicode)", "category": "win_gui"},
    "SetClassLongA": {"lib": "user32", "purpose": "set 32-bit class attribute (ANSI)", "category": "win_gui"},
    "SetClassLongW": {"lib": "user32", "purpose": "set 32-bit class attribute (Unicode)", "category": "win_gui"},
    "GetClassLongPtrA": {"lib": "user32", "purpose": "get pointer-sized class attribute (ANSI)", "category": "win_gui"},
    "GetClassLongPtrW": {"lib": "user32", "purpose": "get pointer-sized class attribute (Unicode)", "category": "win_gui"},

    # ---- Dialog boxes ----
    "MessageBoxA": {"lib": "user32", "purpose": "display modal dialog box (ANSI)", "category": "win_gui"},
    "MessageBoxW": {"lib": "user32", "purpose": "display modal dialog box (Unicode)", "category": "win_gui"},
    "MessageBoxExA": {"lib": "user32", "purpose": "extended message box (ANSI)", "category": "win_gui"},
    "MessageBoxExW": {"lib": "user32", "purpose": "extended message box (Unicode)", "category": "win_gui"},
    "DialogBoxParamA": {"lib": "user32", "purpose": "create modal dialog from template (ANSI)", "category": "win_gui"},
    "DialogBoxParamW": {"lib": "user32", "purpose": "create modal dialog from template (Unicode)", "category": "win_gui"},
    "DialogBoxIndirectParamA": {"lib": "user32", "purpose": "create modal dialog from memory template (ANSI)", "category": "win_gui"},
    "DialogBoxIndirectParamW": {"lib": "user32", "purpose": "create modal dialog from memory template (Unicode)", "category": "win_gui"},
    "CreateDialogParamA": {"lib": "user32", "purpose": "create modeless dialog (ANSI)", "category": "win_gui"},
    "CreateDialogParamW": {"lib": "user32", "purpose": "create modeless dialog (Unicode)", "category": "win_gui"},
    "EndDialog": {"lib": "user32", "purpose": "destroy modal dialog and return result", "category": "win_gui"},
    "GetDlgItem": {"lib": "user32", "purpose": "get handle to dialog control", "category": "win_gui"},
    "GetDlgItemInt": {"lib": "user32", "purpose": "read integer from dialog control", "category": "win_gui"},
    "SetDlgItemInt": {"lib": "user32", "purpose": "set dialog control to integer value", "category": "win_gui"},
    "GetDlgItemTextA": {"lib": "user32", "purpose": "get dialog control text (ANSI)", "category": "win_gui"},
    "GetDlgItemTextW": {"lib": "user32", "purpose": "get dialog control text (Unicode)", "category": "win_gui"},
    "SetDlgItemTextA": {"lib": "user32", "purpose": "set dialog control text (ANSI)", "category": "win_gui"},
    "SetDlgItemTextW": {"lib": "user32", "purpose": "set dialog control text (Unicode)", "category": "win_gui"},
    "SendDlgItemMessageA": {"lib": "user32", "purpose": "send message to dialog control (ANSI)", "category": "win_gui"},
    "SendDlgItemMessageW": {"lib": "user32", "purpose": "send message to dialog control (Unicode)", "category": "win_gui"},
    "IsDialogMessageA": {"lib": "user32", "purpose": "process dialog keyboard message (ANSI)", "category": "win_gui"},
    "IsDialogMessageW": {"lib": "user32", "purpose": "process dialog keyboard message (Unicode)", "category": "win_gui"},
    "CheckDlgButton": {"lib": "user32", "purpose": "check/uncheck dialog button", "category": "win_gui"},
    "IsDlgButtonChecked": {"lib": "user32", "purpose": "query dialog button check state", "category": "win_gui"},
    "CheckRadioButton": {"lib": "user32", "purpose": "check radio button in group", "category": "win_gui"},

    # ---- Painting + DC (via user32) ----
    "GetDC": {"lib": "user32", "purpose": "get device context for window client area", "category": "win_gdi"},
    "GetWindowDC": {"lib": "user32", "purpose": "get device context for entire window", "category": "win_gdi"},
    "GetDCEx": {"lib": "user32", "purpose": "get extended device context", "category": "win_gdi"},
    "ReleaseDC": {"lib": "user32", "purpose": "release device context", "category": "win_gdi"},
    "BeginPaint": {"lib": "user32", "purpose": "prepare window for painting", "category": "win_gdi"},
    "EndPaint": {"lib": "user32", "purpose": "mark end of painting in window", "category": "win_gdi"},
    "InvalidateRect": {"lib": "user32", "purpose": "add rectangle to update region", "category": "win_gui"},
    "InvalidateRgn": {"lib": "user32", "purpose": "add region to update region", "category": "win_gui"},
    "ValidateRect": {"lib": "user32", "purpose": "remove rectangle from update region", "category": "win_gui"},
    "ValidateRgn": {"lib": "user32", "purpose": "remove region from update region", "category": "win_gui"},
    "GetUpdateRect": {"lib": "user32", "purpose": "query update rectangle", "category": "win_gui"},
    "GetUpdateRgn": {"lib": "user32", "purpose": "query update region", "category": "win_gui"},
    "RedrawWindow": {"lib": "user32", "purpose": "redraw window region with flags", "category": "win_gui"},
    "FillRect": {"lib": "user32", "purpose": "fill rectangle with brush", "category": "win_gdi"},
    "FrameRect": {"lib": "user32", "purpose": "draw rectangle frame with brush", "category": "win_gdi"},
    "InvertRect": {"lib": "user32", "purpose": "invert rectangle colors", "category": "win_gdi"},
    "DrawFocusRect": {"lib": "user32", "purpose": "draw focus rectangle", "category": "win_gdi"},
    "DrawTextA": {"lib": "user32", "purpose": "draw formatted text (ANSI)", "category": "win_gdi"},
    "DrawTextW": {"lib": "user32", "purpose": "draw formatted text (Unicode)", "category": "win_gdi"},
    "DrawTextExA": {"lib": "user32", "purpose": "draw formatted text extended (ANSI)", "category": "win_gdi"},
    "DrawTextExW": {"lib": "user32", "purpose": "draw formatted text extended (Unicode)", "category": "win_gdi"},
    "TabbedTextOutA": {"lib": "user32", "purpose": "draw tabbed text (ANSI)", "category": "win_gdi"},
    "TabbedTextOutW": {"lib": "user32", "purpose": "draw tabbed text (Unicode)", "category": "win_gdi"},

    # ---- Icon / cursor / bitmap resources ----
    "LoadIconA": {"lib": "user32", "purpose": "load icon resource (ANSI)", "category": "win_gui"},
    "LoadIconW": {"lib": "user32", "purpose": "load icon resource (Unicode)", "category": "win_gui"},
    "LoadCursorA": {"lib": "user32", "purpose": "load cursor resource (ANSI)", "category": "win_gui"},
    "LoadCursorW": {"lib": "user32", "purpose": "load cursor resource (Unicode)", "category": "win_gui"},
    "LoadBitmapA": {"lib": "user32", "purpose": "load bitmap resource (ANSI)", "category": "win_gui"},
    "LoadBitmapW": {"lib": "user32", "purpose": "load bitmap resource (Unicode)", "category": "win_gui"},
    "LoadImageA": {"lib": "user32", "purpose": "load icon/cursor/bitmap generic (ANSI)", "category": "win_gui"},
    "LoadImageW": {"lib": "user32", "purpose": "load icon/cursor/bitmap generic (Unicode)", "category": "win_gui"},
    "LoadStringA": {"lib": "user32", "purpose": "load string from resource (ANSI)", "category": "win_gui"},
    "LoadStringW": {"lib": "user32", "purpose": "load string from resource (Unicode)", "category": "win_gui"},
    "LoadAcceleratorsA": {"lib": "user32", "purpose": "load accelerator table (ANSI)", "category": "win_gui"},
    "LoadAcceleratorsW": {"lib": "user32", "purpose": "load accelerator table (Unicode)", "category": "win_gui"},
    "SetCursor": {"lib": "user32", "purpose": "set mouse cursor shape", "category": "win_gui"},
    "GetCursor": {"lib": "user32", "purpose": "get handle to current cursor", "category": "win_gui"},
    "ShowCursor": {"lib": "user32", "purpose": "increment/decrement cursor display count", "category": "win_gui"},
    "SetCursorPos": {"lib": "user32", "purpose": "move cursor to screen coords", "category": "win_gui"},
    "GetCursorPos": {"lib": "user32", "purpose": "get cursor position in screen coords", "category": "win_gui"},
    "ClipCursor": {"lib": "user32", "purpose": "confine cursor to rectangle", "category": "win_gui"},
    "GetClipCursor": {"lib": "user32", "purpose": "query cursor confinement rectangle", "category": "win_gui"},
    "DestroyIcon": {"lib": "user32", "purpose": "destroy icon handle", "category": "win_gui"},
    "DestroyCursor": {"lib": "user32", "purpose": "destroy cursor handle", "category": "win_gui"},
    "CopyIcon": {"lib": "user32", "purpose": "duplicate an icon", "category": "win_gui"},
    "CreateIconIndirect": {"lib": "user32", "purpose": "create icon from ICONINFO", "category": "win_gui"},
    "GetIconInfo": {"lib": "user32", "purpose": "get info about icon or cursor", "category": "win_gui"},

    # ---- Menu ----
    "CreateMenu": {"lib": "user32", "purpose": "create empty top-level menu", "category": "win_gui"},
    "CreatePopupMenu": {"lib": "user32", "purpose": "create empty popup menu", "category": "win_gui"},
    "DestroyMenu": {"lib": "user32", "purpose": "destroy menu and subitems", "category": "win_gui"},
    "AppendMenuA": {"lib": "user32", "purpose": "append menu item (ANSI)", "category": "win_gui"},
    "AppendMenuW": {"lib": "user32", "purpose": "append menu item (Unicode)", "category": "win_gui"},
    "InsertMenuA": {"lib": "user32", "purpose": "insert menu item (ANSI)", "category": "win_gui"},
    "InsertMenuW": {"lib": "user32", "purpose": "insert menu item (Unicode)", "category": "win_gui"},
    "InsertMenuItemA": {"lib": "user32", "purpose": "insert menu item by struct (ANSI)", "category": "win_gui"},
    "InsertMenuItemW": {"lib": "user32", "purpose": "insert menu item by struct (Unicode)", "category": "win_gui"},
    "DeleteMenu": {"lib": "user32", "purpose": "delete menu item by position or ID", "category": "win_gui"},
    "RemoveMenu": {"lib": "user32", "purpose": "remove menu item (keep submenu)", "category": "win_gui"},
    "ModifyMenuA": {"lib": "user32", "purpose": "modify menu item (ANSI)", "category": "win_gui"},
    "ModifyMenuW": {"lib": "user32", "purpose": "modify menu item (Unicode)", "category": "win_gui"},
    "EnableMenuItem": {"lib": "user32", "purpose": "enable/disable/gray menu item", "category": "win_gui"},
    "CheckMenuItem": {"lib": "user32", "purpose": "add/remove menu item check mark", "category": "win_gui"},
    "CheckMenuRadioItem": {"lib": "user32", "purpose": "check radio-style menu item", "category": "win_gui"},
    "SetMenu": {"lib": "user32", "purpose": "assign menu to window", "category": "win_gui"},
    "GetMenu": {"lib": "user32", "purpose": "get menu assigned to window", "category": "win_gui"},
    "GetSubMenu": {"lib": "user32", "purpose": "get submenu handle at position", "category": "win_gui"},
    "GetMenuItemCount": {"lib": "user32", "purpose": "count menu items", "category": "win_gui"},
    "GetMenuItemID": {"lib": "user32", "purpose": "get command ID of menu item", "category": "win_gui"},
    "GetMenuItemInfoA": {"lib": "user32", "purpose": "get menu item info (ANSI)", "category": "win_gui"},
    "GetMenuItemInfoW": {"lib": "user32", "purpose": "get menu item info (Unicode)", "category": "win_gui"},
    "SetMenuItemInfoA": {"lib": "user32", "purpose": "set menu item info (ANSI)", "category": "win_gui"},
    "SetMenuItemInfoW": {"lib": "user32", "purpose": "set menu item info (Unicode)", "category": "win_gui"},
    "TrackPopupMenu": {"lib": "user32", "purpose": "show shortcut popup menu", "category": "win_gui"},
    "TrackPopupMenuEx": {"lib": "user32", "purpose": "show extended popup menu", "category": "win_gui"},
    "DrawMenuBar": {"lib": "user32", "purpose": "force menu bar redraw", "category": "win_gui"},
    "LoadMenuA": {"lib": "user32", "purpose": "load menu from resource (ANSI)", "category": "win_gui"},
    "LoadMenuW": {"lib": "user32", "purpose": "load menu from resource (Unicode)", "category": "win_gui"},

    # ---- Input / keyboard / mouse / focus ----
    "SetFocus": {"lib": "user32", "purpose": "set keyboard focus to window", "category": "win_input"},
    "GetFocus": {"lib": "user32", "purpose": "get window with keyboard focus", "category": "win_input"},
    "SetCapture": {"lib": "user32", "purpose": "capture mouse to window", "category": "win_input"},
    "ReleaseCapture": {"lib": "user32", "purpose": "release mouse capture", "category": "win_input"},
    "GetCapture": {"lib": "user32", "purpose": "get window with mouse capture", "category": "win_input"},
    "GetKeyState": {"lib": "user32", "purpose": "get virtual-key state (async-ish)", "category": "win_input"},
    "GetAsyncKeyState": {"lib": "user32", "purpose": "get asynchronous virtual-key state", "category": "win_input"},
    "GetKeyboardState": {"lib": "user32", "purpose": "get full keyboard state array", "category": "win_input"},
    "SetKeyboardState": {"lib": "user32", "purpose": "set full keyboard state array", "category": "win_input"},
    "MapVirtualKeyA": {"lib": "user32", "purpose": "translate virtual-key to scan/char (ANSI)", "category": "win_input"},
    "MapVirtualKeyW": {"lib": "user32", "purpose": "translate virtual-key to scan/char (Unicode)", "category": "win_input"},
    "MapVirtualKeyExA": {"lib": "user32", "purpose": "virtual-key translate with layout (ANSI)", "category": "win_input"},
    "MapVirtualKeyExW": {"lib": "user32", "purpose": "virtual-key translate with layout (Unicode)", "category": "win_input"},
    "ToAscii": {"lib": "user32", "purpose": "translate VK + state to ASCII", "category": "win_input"},
    "ToUnicode": {"lib": "user32", "purpose": "translate VK + state to Unicode", "category": "win_input"},
    "ToUnicodeEx": {"lib": "user32", "purpose": "extended VK to Unicode translation", "category": "win_input"},
    "VkKeyScanA": {"lib": "user32", "purpose": "translate char to virtual-key (ANSI)", "category": "win_input"},
    "VkKeyScanW": {"lib": "user32", "purpose": "translate char to virtual-key (Unicode)", "category": "win_input"},
    "SendInput": {"lib": "user32", "purpose": "synthesize keystrokes/mouse/hardware input", "category": "win_input"},
    "keybd_event": {"lib": "user32", "purpose": "synthesize keystroke (legacy)", "category": "win_input"},
    "mouse_event": {"lib": "user32", "purpose": "synthesize mouse event (legacy)", "category": "win_input"},
    "RegisterHotKey": {"lib": "user32", "purpose": "register system-wide hotkey", "category": "win_input"},
    "UnregisterHotKey": {"lib": "user32", "purpose": "unregister system-wide hotkey", "category": "win_input"},

    # ---- Timer / caret ----
    "SetTimer": {"lib": "user32", "purpose": "create timer with specified interval", "category": "win_gui"},
    "KillTimer": {"lib": "user32", "purpose": "destroy a timer", "category": "win_gui"},
    "CreateCaret": {"lib": "user32", "purpose": "create caret (text cursor)", "category": "win_gui"},
    "DestroyCaret": {"lib": "user32", "purpose": "destroy caret", "category": "win_gui"},
    "ShowCaret": {"lib": "user32", "purpose": "display caret", "category": "win_gui"},
    "HideCaret": {"lib": "user32", "purpose": "hide caret", "category": "win_gui"},
    "SetCaretPos": {"lib": "user32", "purpose": "move caret to coords", "category": "win_gui"},
    "GetCaretPos": {"lib": "user32", "purpose": "get caret coords", "category": "win_gui"},
    "GetCaretBlinkTime": {"lib": "user32", "purpose": "get caret blink interval", "category": "win_gui"},
    "SetCaretBlinkTime": {"lib": "user32", "purpose": "set caret blink interval", "category": "win_gui"},

    # ---- Clipboard ----
    "OpenClipboard": {"lib": "user32", "purpose": "open clipboard for access", "category": "win_clipboard"},
    "CloseClipboard": {"lib": "user32", "purpose": "close clipboard", "category": "win_clipboard"},
    "EmptyClipboard": {"lib": "user32", "purpose": "empty clipboard and free data", "category": "win_clipboard"},
    "SetClipboardData": {"lib": "user32", "purpose": "place data on clipboard", "category": "win_clipboard"},
    "GetClipboardData": {"lib": "user32", "purpose": "retrieve clipboard data by format", "category": "win_clipboard"},
    "IsClipboardFormatAvailable": {"lib": "user32", "purpose": "check clipboard format availability", "category": "win_clipboard"},
    "EnumClipboardFormats": {"lib": "user32", "purpose": "enumerate clipboard formats", "category": "win_clipboard"},
    "CountClipboardFormats": {"lib": "user32", "purpose": "count clipboard formats", "category": "win_clipboard"},
    "RegisterClipboardFormatA": {"lib": "user32", "purpose": "register custom clipboard format (ANSI)", "category": "win_clipboard"},
    "RegisterClipboardFormatW": {"lib": "user32", "purpose": "register custom clipboard format (Unicode)", "category": "win_clipboard"},
    "GetClipboardFormatNameA": {"lib": "user32", "purpose": "get clipboard format name (ANSI)", "category": "win_clipboard"},
    "GetClipboardFormatNameW": {"lib": "user32", "purpose": "get clipboard format name (Unicode)", "category": "win_clipboard"},
    "GetClipboardOwner": {"lib": "user32", "purpose": "get clipboard owner window", "category": "win_clipboard"},

    # ---- Hook / accessibility / event injection ----
    "SetWindowsHookExA": {"lib": "user32", "purpose": "install hook procedure (ANSI)", "category": "win_hook"},
    "SetWindowsHookExW": {"lib": "user32", "purpose": "install hook procedure (Unicode)", "category": "win_hook"},
    "UnhookWindowsHookEx": {"lib": "user32", "purpose": "uninstall hook procedure", "category": "win_hook"},
    "CallNextHookEx": {"lib": "user32", "purpose": "chain to next hook in chain", "category": "win_hook"},
    "SetWinEventHook": {"lib": "user32", "purpose": "install accessibility event hook", "category": "win_hook"},
    "UnhookWinEvent": {"lib": "user32", "purpose": "uninstall accessibility event hook", "category": "win_hook"},
    "NotifyWinEvent": {"lib": "user32", "purpose": "signal accessibility event", "category": "win_hook"},

    # ---- System metrics / info ----
    "GetSystemMetrics": {"lib": "user32", "purpose": "query system-wide metric value", "category": "win_gui"},
    "SystemParametersInfoA": {"lib": "user32", "purpose": "query/set system-wide parameter (ANSI)", "category": "win_gui"},
    "SystemParametersInfoW": {"lib": "user32", "purpose": "query/set system-wide parameter (Unicode)", "category": "win_gui"},
    "GetDoubleClickTime": {"lib": "user32", "purpose": "get double-click interval (ms)", "category": "win_gui"},
    "SetDoubleClickTime": {"lib": "user32", "purpose": "set double-click interval (ms)", "category": "win_gui"},
    "GetSysColor": {"lib": "user32", "purpose": "get system color by index", "category": "win_gdi"},
    "SetSysColors": {"lib": "user32", "purpose": "set system colors", "category": "win_gdi"},
    "GetSysColorBrush": {"lib": "user32", "purpose": "get brush for system color", "category": "win_gdi"},
    "GetMonitorInfoA": {"lib": "user32", "purpose": "get monitor info (ANSI)", "category": "win_gui"},
    "GetMonitorInfoW": {"lib": "user32", "purpose": "get monitor info (Unicode)", "category": "win_gui"},
    "MonitorFromWindow": {"lib": "user32", "purpose": "get monitor containing window", "category": "win_gui"},
    "MonitorFromPoint": {"lib": "user32", "purpose": "get monitor containing point", "category": "win_gui"},
    "MonitorFromRect": {"lib": "user32", "purpose": "get monitor containing rectangle", "category": "win_gui"},
    "EnumDisplayMonitors": {"lib": "user32", "purpose": "enumerate display monitors", "category": "win_gui"},
    "EnumDisplaySettingsA": {"lib": "user32", "purpose": "enumerate display modes (ANSI)", "category": "win_gui"},
    "EnumDisplaySettingsW": {"lib": "user32", "purpose": "enumerate display modes (Unicode)", "category": "win_gui"},
    "ChangeDisplaySettingsA": {"lib": "user32", "purpose": "change display settings (ANSI)", "category": "win_gui"},
    "ChangeDisplaySettingsW": {"lib": "user32", "purpose": "change display settings (Unicode)", "category": "win_gui"},
}


# ---------------------------------------------------------------------------
# advapi32.dll — Registry, services, token/privilege, legacy CryptoAPI,
#                event logging, access control.
# ---------------------------------------------------------------------------
_ADVAPI32_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # ---- Registry ----
    "RegOpenKeyA": {"lib": "advapi32", "purpose": "open registry key (ANSI, legacy)", "category": "win_registry"},
    "RegOpenKeyW": {"lib": "advapi32", "purpose": "open registry key (Unicode, legacy)", "category": "win_registry"},
    "RegOpenKeyExA": {"lib": "advapi32", "purpose": "open registry key (ANSI)", "category": "win_registry"},
    "RegOpenKeyExW": {"lib": "advapi32", "purpose": "open registry key (Unicode)", "category": "win_registry"},
    "RegCreateKeyA": {"lib": "advapi32", "purpose": "create/open registry key (ANSI, legacy)", "category": "win_registry"},
    "RegCreateKeyW": {"lib": "advapi32", "purpose": "create/open registry key (Unicode, legacy)", "category": "win_registry"},
    "RegCreateKeyExA": {"lib": "advapi32", "purpose": "create or open registry key (ANSI)", "category": "win_registry"},
    "RegCreateKeyExW": {"lib": "advapi32", "purpose": "create or open registry key (Unicode)", "category": "win_registry"},
    "RegCloseKey": {"lib": "advapi32", "purpose": "close registry key handle", "category": "win_registry"},
    "RegDeleteKeyA": {"lib": "advapi32", "purpose": "delete registry subkey (ANSI)", "category": "win_registry"},
    "RegDeleteKeyW": {"lib": "advapi32", "purpose": "delete registry subkey (Unicode)", "category": "win_registry"},
    "RegDeleteKeyExA": {"lib": "advapi32", "purpose": "delete registry subkey with WOW64 flag (ANSI)", "category": "win_registry"},
    "RegDeleteKeyExW": {"lib": "advapi32", "purpose": "delete registry subkey with WOW64 flag (Unicode)", "category": "win_registry"},
    "RegDeleteTreeA": {"lib": "advapi32", "purpose": "delete key subtree recursively (ANSI)", "category": "win_registry"},
    "RegDeleteTreeW": {"lib": "advapi32", "purpose": "delete key subtree recursively (Unicode)", "category": "win_registry"},
    "RegQueryValueA": {"lib": "advapi32", "purpose": "query default value (ANSI, legacy)", "category": "win_registry"},
    "RegQueryValueW": {"lib": "advapi32", "purpose": "query default value (Unicode, legacy)", "category": "win_registry"},
    "RegQueryValueExA": {"lib": "advapi32", "purpose": "query registry value data (ANSI)", "category": "win_registry"},
    "RegQueryValueExW": {"lib": "advapi32", "purpose": "query registry value data (Unicode)", "category": "win_registry"},
    "RegQueryInfoKeyA": {"lib": "advapi32", "purpose": "query key metadata (ANSI)", "category": "win_registry"},
    "RegQueryInfoKeyW": {"lib": "advapi32", "purpose": "query key metadata (Unicode)", "category": "win_registry"},
    "RegSetValueA": {"lib": "advapi32", "purpose": "set default value (ANSI, legacy)", "category": "win_registry"},
    "RegSetValueW": {"lib": "advapi32", "purpose": "set default value (Unicode, legacy)", "category": "win_registry"},
    "RegSetValueExA": {"lib": "advapi32", "purpose": "set registry value data (ANSI)", "category": "win_registry"},
    "RegSetValueExW": {"lib": "advapi32", "purpose": "set registry value data (Unicode)", "category": "win_registry"},
    "RegDeleteValueA": {"lib": "advapi32", "purpose": "delete registry value (ANSI)", "category": "win_registry"},
    "RegDeleteValueW": {"lib": "advapi32", "purpose": "delete registry value (Unicode)", "category": "win_registry"},
    "RegEnumKeyA": {"lib": "advapi32", "purpose": "enumerate subkey by index (ANSI)", "category": "win_registry"},
    "RegEnumKeyW": {"lib": "advapi32", "purpose": "enumerate subkey by index (Unicode)", "category": "win_registry"},
    "RegEnumKeyExA": {"lib": "advapi32", "purpose": "enumerate registry subkeys (ANSI)", "category": "win_registry"},
    "RegEnumKeyExW": {"lib": "advapi32", "purpose": "enumerate registry subkeys (Unicode)", "category": "win_registry"},
    "RegEnumValueA": {"lib": "advapi32", "purpose": "enumerate registry values (ANSI)", "category": "win_registry"},
    "RegEnumValueW": {"lib": "advapi32", "purpose": "enumerate registry values (Unicode)", "category": "win_registry"},
    "RegFlushKey": {"lib": "advapi32", "purpose": "force write key changes to disk", "category": "win_registry"},
    "RegSaveKeyA": {"lib": "advapi32", "purpose": "save key to hive file (ANSI)", "category": "win_registry"},
    "RegSaveKeyW": {"lib": "advapi32", "purpose": "save key to hive file (Unicode)", "category": "win_registry"},
    "RegLoadKeyA": {"lib": "advapi32", "purpose": "load hive file as subkey (ANSI)", "category": "win_registry"},
    "RegLoadKeyW": {"lib": "advapi32", "purpose": "load hive file as subkey (Unicode)", "category": "win_registry"},
    "RegUnLoadKeyA": {"lib": "advapi32", "purpose": "unload hive subkey (ANSI)", "category": "win_registry"},
    "RegUnLoadKeyW": {"lib": "advapi32", "purpose": "unload hive subkey (Unicode)", "category": "win_registry"},
    "RegConnectRegistryA": {"lib": "advapi32", "purpose": "connect to remote registry (ANSI)", "category": "win_registry"},
    "RegConnectRegistryW": {"lib": "advapi32", "purpose": "connect to remote registry (Unicode)", "category": "win_registry"},
    "RegNotifyChangeKeyValue": {"lib": "advapi32", "purpose": "notify on key value change", "category": "win_registry"},
    "RegGetValueA": {"lib": "advapi32", "purpose": "get value with type checking (ANSI)", "category": "win_registry"},
    "RegGetValueW": {"lib": "advapi32", "purpose": "get value with type checking (Unicode)", "category": "win_registry"},
    "RegCopyTreeA": {"lib": "advapi32", "purpose": "copy key subtree (ANSI)", "category": "win_registry"},
    "RegCopyTreeW": {"lib": "advapi32", "purpose": "copy key subtree (Unicode)", "category": "win_registry"},

    # ---- Token / privilege ----
    "OpenProcessToken": {"lib": "advapi32", "purpose": "open access token of a process", "category": "win_security"},
    "OpenThreadToken": {"lib": "advapi32", "purpose": "open access token of a thread", "category": "win_security"},
    "DuplicateToken": {"lib": "advapi32", "purpose": "duplicate access token", "category": "win_security"},
    "DuplicateTokenEx": {"lib": "advapi32", "purpose": "duplicate access token with type", "category": "win_security"},
    "GetTokenInformation": {"lib": "advapi32", "purpose": "query process token information", "category": "win_security"},
    "SetTokenInformation": {"lib": "advapi32", "purpose": "modify access token attributes", "category": "win_security"},
    "AdjustTokenPrivileges": {"lib": "advapi32", "purpose": "enable/disable token privileges", "category": "win_security"},
    "AdjustTokenGroups": {"lib": "advapi32", "purpose": "enable/disable token groups", "category": "win_security"},
    "LookupPrivilegeValueA": {"lib": "advapi32", "purpose": "look up privilege LUID (ANSI)", "category": "win_security"},
    "LookupPrivilegeValueW": {"lib": "advapi32", "purpose": "look up privilege LUID (Unicode)", "category": "win_security"},
    "LookupPrivilegeNameA": {"lib": "advapi32", "purpose": "look up privilege name (ANSI)", "category": "win_security"},
    "LookupPrivilegeNameW": {"lib": "advapi32", "purpose": "look up privilege name (Unicode)", "category": "win_security"},
    "LookupAccountNameA": {"lib": "advapi32", "purpose": "look up SID by account name (ANSI)", "category": "win_security"},
    "LookupAccountNameW": {"lib": "advapi32", "purpose": "look up SID by account name (Unicode)", "category": "win_security"},
    "LookupAccountSidA": {"lib": "advapi32", "purpose": "look up account name by SID (ANSI)", "category": "win_security"},
    "LookupAccountSidW": {"lib": "advapi32", "purpose": "look up account name by SID (Unicode)", "category": "win_security"},
    "ImpersonateLoggedOnUser": {"lib": "advapi32", "purpose": "impersonate logged-on user token", "category": "win_security"},
    "ImpersonateSelf": {"lib": "advapi32", "purpose": "impersonate self with effective token", "category": "win_security"},
    "RevertToSelf": {"lib": "advapi32", "purpose": "stop impersonation", "category": "win_security"},
    "LogonUserA": {"lib": "advapi32", "purpose": "authenticate user and get token (ANSI)", "category": "win_security"},
    "LogonUserW": {"lib": "advapi32", "purpose": "authenticate user and get token (Unicode)", "category": "win_security"},
    "CheckTokenMembership": {"lib": "advapi32", "purpose": "check if SID is in token", "category": "win_security"},
    "CreateRestrictedToken": {"lib": "advapi32", "purpose": "create restricted version of token", "category": "win_security"},
    "IsValidSid": {"lib": "advapi32", "purpose": "check if SID is structurally valid", "category": "win_security"},
    "GetLengthSid": {"lib": "advapi32", "purpose": "get SID byte length", "category": "win_security"},
    "CopySid": {"lib": "advapi32", "purpose": "copy SID to buffer", "category": "win_security"},
    "EqualSid": {"lib": "advapi32", "purpose": "compare two SIDs for equality", "category": "win_security"},
    "AllocateAndInitializeSid": {"lib": "advapi32", "purpose": "allocate and init SID", "category": "win_security"},
    "FreeSid": {"lib": "advapi32", "purpose": "free SID allocated by AllocateAndInitializeSid", "category": "win_security"},

    # ---- ACL / security descriptor ----
    "InitializeSecurityDescriptor": {"lib": "advapi32", "purpose": "initialize security descriptor", "category": "win_security"},
    "SetSecurityDescriptorDacl": {"lib": "advapi32", "purpose": "set DACL in security descriptor", "category": "win_security"},
    "GetSecurityDescriptorDacl": {"lib": "advapi32", "purpose": "get DACL from security descriptor", "category": "win_security"},
    "SetSecurityDescriptorOwner": {"lib": "advapi32", "purpose": "set owner in security descriptor", "category": "win_security"},
    "GetSecurityDescriptorOwner": {"lib": "advapi32", "purpose": "get owner from security descriptor", "category": "win_security"},
    "InitializeAcl": {"lib": "advapi32", "purpose": "initialize ACL structure", "category": "win_security"},
    "AddAccessAllowedAce": {"lib": "advapi32", "purpose": "add allow-ACE to ACL", "category": "win_security"},
    "AddAccessDeniedAce": {"lib": "advapi32", "purpose": "add deny-ACE to ACL", "category": "win_security"},
    "GetAce": {"lib": "advapi32", "purpose": "get ACE by index", "category": "win_security"},
    "GetFileSecurityA": {"lib": "advapi32", "purpose": "get file security descriptor (ANSI)", "category": "win_security"},
    "GetFileSecurityW": {"lib": "advapi32", "purpose": "get file security descriptor (Unicode)", "category": "win_security"},
    "SetFileSecurityA": {"lib": "advapi32", "purpose": "set file security descriptor (ANSI)", "category": "win_security"},
    "SetFileSecurityW": {"lib": "advapi32", "purpose": "set file security descriptor (Unicode)", "category": "win_security"},
    "AccessCheck": {"lib": "advapi32", "purpose": "perform access check against SD", "category": "win_security"},

    # ---- Service control ----
    "OpenSCManagerA": {"lib": "advapi32", "purpose": "open handle to SCM database (ANSI)", "category": "win_service"},
    "OpenSCManagerW": {"lib": "advapi32", "purpose": "open handle to SCM database (Unicode)", "category": "win_service"},
    "CreateServiceA": {"lib": "advapi32", "purpose": "install new service (ANSI)", "category": "win_service"},
    "CreateServiceW": {"lib": "advapi32", "purpose": "install new service (Unicode)", "category": "win_service"},
    "OpenServiceA": {"lib": "advapi32", "purpose": "open handle to existing service (ANSI)", "category": "win_service"},
    "OpenServiceW": {"lib": "advapi32", "purpose": "open handle to existing service (Unicode)", "category": "win_service"},
    "DeleteService": {"lib": "advapi32", "purpose": "mark service for deletion", "category": "win_service"},
    "StartServiceA": {"lib": "advapi32", "purpose": "start service (ANSI)", "category": "win_service"},
    "StartServiceW": {"lib": "advapi32", "purpose": "start service (Unicode)", "category": "win_service"},
    "ControlService": {"lib": "advapi32", "purpose": "send control code to service", "category": "win_service"},
    "ControlServiceExA": {"lib": "advapi32", "purpose": "extended service control (ANSI)", "category": "win_service"},
    "ControlServiceExW": {"lib": "advapi32", "purpose": "extended service control (Unicode)", "category": "win_service"},
    "QueryServiceStatus": {"lib": "advapi32", "purpose": "query service running state", "category": "win_service"},
    "QueryServiceStatusEx": {"lib": "advapi32", "purpose": "query extended service state", "category": "win_service"},
    "QueryServiceConfigA": {"lib": "advapi32", "purpose": "query service configuration (ANSI)", "category": "win_service"},
    "QueryServiceConfigW": {"lib": "advapi32", "purpose": "query service configuration (Unicode)", "category": "win_service"},
    "ChangeServiceConfigA": {"lib": "advapi32", "purpose": "change service config (ANSI)", "category": "win_service"},
    "ChangeServiceConfigW": {"lib": "advapi32", "purpose": "change service config (Unicode)", "category": "win_service"},
    "ChangeServiceConfig2A": {"lib": "advapi32", "purpose": "change service config extended (ANSI)", "category": "win_service"},
    "ChangeServiceConfig2W": {"lib": "advapi32", "purpose": "change service config extended (Unicode)", "category": "win_service"},
    "EnumServicesStatusA": {"lib": "advapi32", "purpose": "enumerate services in SCM (ANSI)", "category": "win_service"},
    "EnumServicesStatusW": {"lib": "advapi32", "purpose": "enumerate services in SCM (Unicode)", "category": "win_service"},
    "EnumServicesStatusExA": {"lib": "advapi32", "purpose": "enumerate services extended (ANSI)", "category": "win_service"},
    "EnumServicesStatusExW": {"lib": "advapi32", "purpose": "enumerate services extended (Unicode)", "category": "win_service"},
    "CloseServiceHandle": {"lib": "advapi32", "purpose": "close service or SCM handle", "category": "win_service"},
    "StartServiceCtrlDispatcherA": {"lib": "advapi32", "purpose": "connect service process to SCM (ANSI)", "category": "win_service"},
    "StartServiceCtrlDispatcherW": {"lib": "advapi32", "purpose": "connect service process to SCM (Unicode)", "category": "win_service"},
    "RegisterServiceCtrlHandlerA": {"lib": "advapi32", "purpose": "register service control handler (ANSI)", "category": "win_service"},
    "RegisterServiceCtrlHandlerW": {"lib": "advapi32", "purpose": "register service control handler (Unicode)", "category": "win_service"},
    "RegisterServiceCtrlHandlerExA": {"lib": "advapi32", "purpose": "extended service ctrl handler (ANSI)", "category": "win_service"},
    "RegisterServiceCtrlHandlerExW": {"lib": "advapi32", "purpose": "extended service ctrl handler (Unicode)", "category": "win_service"},
    "SetServiceStatus": {"lib": "advapi32", "purpose": "update service status to SCM", "category": "win_service"},

    # ---- Legacy CryptoAPI (wincrypt) ----
    "CryptAcquireContextA": {"lib": "advapi32", "purpose": "acquire handle to crypto provider (ANSI)", "category": "win_crypto"},
    "CryptAcquireContextW": {"lib": "advapi32", "purpose": "acquire handle to crypto provider (Unicode)", "category": "win_crypto"},
    "CryptReleaseContext": {"lib": "advapi32", "purpose": "release crypto provider handle", "category": "win_crypto"},
    "CryptGenRandom": {"lib": "advapi32", "purpose": "generate cryptographic random bytes", "category": "win_crypto"},
    "CryptCreateHash": {"lib": "advapi32", "purpose": "create hash object", "category": "win_crypto"},
    "CryptHashData": {"lib": "advapi32", "purpose": "add data to hash object", "category": "win_crypto"},
    "CryptHashSessionKey": {"lib": "advapi32", "purpose": "hash session key", "category": "win_crypto"},
    "CryptGetHashParam": {"lib": "advapi32", "purpose": "get hash object parameter", "category": "win_crypto"},
    "CryptSetHashParam": {"lib": "advapi32", "purpose": "set hash object parameter", "category": "win_crypto"},
    "CryptDestroyHash": {"lib": "advapi32", "purpose": "destroy hash object", "category": "win_crypto"},
    "CryptDeriveKey": {"lib": "advapi32", "purpose": "derive key from password (legacy)", "category": "win_crypto"},
    "CryptGenKey": {"lib": "advapi32", "purpose": "generate random key", "category": "win_crypto"},
    "CryptImportKey": {"lib": "advapi32", "purpose": "import key blob", "category": "win_crypto"},
    "CryptExportKey": {"lib": "advapi32", "purpose": "export key blob", "category": "win_crypto"},
    "CryptDuplicateKey": {"lib": "advapi32", "purpose": "duplicate crypto key", "category": "win_crypto"},
    "CryptDestroyKey": {"lib": "advapi32", "purpose": "destroy crypto key handle", "category": "win_crypto"},
    "CryptGetKeyParam": {"lib": "advapi32", "purpose": "get key parameter", "category": "win_crypto"},
    "CryptSetKeyParam": {"lib": "advapi32", "purpose": "set key parameter", "category": "win_crypto"},
    "CryptEncrypt": {"lib": "advapi32", "purpose": "encrypt data (legacy CryptoAPI)", "category": "win_crypto"},
    "CryptDecrypt": {"lib": "advapi32", "purpose": "decrypt data (legacy CryptoAPI)", "category": "win_crypto"},
    "CryptSignHashA": {"lib": "advapi32", "purpose": "sign hash (ANSI)", "category": "win_crypto"},
    "CryptSignHashW": {"lib": "advapi32", "purpose": "sign hash (Unicode)", "category": "win_crypto"},
    "CryptVerifySignatureA": {"lib": "advapi32", "purpose": "verify signed hash (ANSI)", "category": "win_crypto"},
    "CryptVerifySignatureW": {"lib": "advapi32", "purpose": "verify signed hash (Unicode)", "category": "win_crypto"},
    "CryptGetProvParam": {"lib": "advapi32", "purpose": "get CSP parameter", "category": "win_crypto"},
    "CryptSetProvParam": {"lib": "advapi32", "purpose": "set CSP parameter", "category": "win_crypto"},

    # ---- Event logging ----
    "OpenEventLogA": {"lib": "advapi32", "purpose": "open event log handle (ANSI)", "category": "win_eventlog"},
    "OpenEventLogW": {"lib": "advapi32", "purpose": "open event log handle (Unicode)", "category": "win_eventlog"},
    "CloseEventLog": {"lib": "advapi32", "purpose": "close event log handle", "category": "win_eventlog"},
    "ReadEventLogA": {"lib": "advapi32", "purpose": "read event log records (ANSI)", "category": "win_eventlog"},
    "ReadEventLogW": {"lib": "advapi32", "purpose": "read event log records (Unicode)", "category": "win_eventlog"},
    "ReportEventA": {"lib": "advapi32", "purpose": "write event log record (ANSI)", "category": "win_eventlog"},
    "ReportEventW": {"lib": "advapi32", "purpose": "write event log record (Unicode)", "category": "win_eventlog"},
    "ClearEventLogA": {"lib": "advapi32", "purpose": "clear event log (ANSI)", "category": "win_eventlog"},
    "ClearEventLogW": {"lib": "advapi32", "purpose": "clear event log (Unicode)", "category": "win_eventlog"},
    "RegisterEventSourceA": {"lib": "advapi32", "purpose": "register event source (ANSI)", "category": "win_eventlog"},
    "RegisterEventSourceW": {"lib": "advapi32", "purpose": "register event source (Unicode)", "category": "win_eventlog"},
    "DeregisterEventSource": {"lib": "advapi32", "purpose": "close event source handle", "category": "win_eventlog"},
    "GetNumberOfEventLogRecords": {"lib": "advapi32", "purpose": "count records in event log", "category": "win_eventlog"},
    "GetOldestEventLogRecord": {"lib": "advapi32", "purpose": "get oldest record number", "category": "win_eventlog"},
}


# ---------------------------------------------------------------------------
# gdi32.dll — Graphics Device Interface.
# DC, pen, brush, font, text, bitmap, region, path, palette, metafile.
# ---------------------------------------------------------------------------
_GDI32_SIGNATURES_DATA: dict[str, dict[str, str]] = {
    # ---- Device context ----
    "CreateDCA": {"lib": "gdi32", "purpose": "create DC for device (ANSI)", "category": "win_gdi"},
    "CreateDCW": {"lib": "gdi32", "purpose": "create DC for device (Unicode)", "category": "win_gdi"},
    "CreateICA": {"lib": "gdi32", "purpose": "create information context (ANSI)", "category": "win_gdi"},
    "CreateICW": {"lib": "gdi32", "purpose": "create information context (Unicode)", "category": "win_gdi"},
    "CreateCompatibleDC": {"lib": "gdi32", "purpose": "create memory DC compatible with device", "category": "win_gdi"},
    "DeleteDC": {"lib": "gdi32", "purpose": "delete device context", "category": "win_gdi"},
    "SaveDC": {"lib": "gdi32", "purpose": "save DC state to stack", "category": "win_gdi"},
    "RestoreDC": {"lib": "gdi32", "purpose": "restore DC state from stack", "category": "win_gdi"},
    "GetDeviceCaps": {"lib": "gdi32", "purpose": "query device capabilities", "category": "win_gdi"},
    "GetDCOrgEx": {"lib": "gdi32", "purpose": "get DC origin in screen coords", "category": "win_gdi"},
    "SetMapMode": {"lib": "gdi32", "purpose": "set mapping mode of DC", "category": "win_gdi"},
    "GetMapMode": {"lib": "gdi32", "purpose": "get current mapping mode", "category": "win_gdi"},
    "SetViewportExtEx": {"lib": "gdi32", "purpose": "set viewport extents", "category": "win_gdi"},
    "SetViewportOrgEx": {"lib": "gdi32", "purpose": "set viewport origin", "category": "win_gdi"},
    "SetWindowExtEx": {"lib": "gdi32", "purpose": "set window extents", "category": "win_gdi"},
    "SetWindowOrgEx": {"lib": "gdi32", "purpose": "set window origin", "category": "win_gdi"},
    "LPtoDP": {"lib": "gdi32", "purpose": "convert logical to device points", "category": "win_gdi"},
    "DPtoLP": {"lib": "gdi32", "purpose": "convert device to logical points", "category": "win_gdi"},

    # ---- GDI object management ----
    "SelectObject": {"lib": "gdi32", "purpose": "select GDI object into DC", "category": "win_gdi"},
    "DeleteObject": {"lib": "gdi32", "purpose": "delete GDI object", "category": "win_gdi"},
    "GetObjectA": {"lib": "gdi32", "purpose": "get GDI object info (ANSI)", "category": "win_gdi"},
    "GetObjectW": {"lib": "gdi32", "purpose": "get GDI object info (Unicode)", "category": "win_gdi"},
    "GetObjectType": {"lib": "gdi32", "purpose": "get GDI object type", "category": "win_gdi"},
    "GetStockObject": {"lib": "gdi32", "purpose": "get handle to stock GDI object", "category": "win_gdi"},

    # ---- Pen / brush ----
    "CreatePen": {"lib": "gdi32", "purpose": "create logical pen", "category": "win_gdi"},
    "CreatePenIndirect": {"lib": "gdi32", "purpose": "create pen from LOGPEN", "category": "win_gdi"},
    "ExtCreatePen": {"lib": "gdi32", "purpose": "create extended pen", "category": "win_gdi"},
    "CreateSolidBrush": {"lib": "gdi32", "purpose": "create solid-color brush", "category": "win_gdi"},
    "CreateHatchBrush": {"lib": "gdi32", "purpose": "create hatched brush", "category": "win_gdi"},
    "CreatePatternBrush": {"lib": "gdi32", "purpose": "create brush from bitmap pattern", "category": "win_gdi"},
    "CreateBrushIndirect": {"lib": "gdi32", "purpose": "create brush from LOGBRUSH", "category": "win_gdi"},
    "CreateDIBPatternBrushPt": {"lib": "gdi32", "purpose": "create brush from DIB", "category": "win_gdi"},

    # ---- Color / palette ----
    "SetTextColor": {"lib": "gdi32", "purpose": "set DC text color", "category": "win_gdi"},
    "GetTextColor": {"lib": "gdi32", "purpose": "get DC text color", "category": "win_gdi"},
    "SetBkColor": {"lib": "gdi32", "purpose": "set DC background color", "category": "win_gdi"},
    "GetBkColor": {"lib": "gdi32", "purpose": "get DC background color", "category": "win_gdi"},
    "SetBkMode": {"lib": "gdi32", "purpose": "set DC background mode (opaque/transparent)", "category": "win_gdi"},
    "GetBkMode": {"lib": "gdi32", "purpose": "get DC background mode", "category": "win_gdi"},
    "SetROP2": {"lib": "gdi32", "purpose": "set foreground raster op mode", "category": "win_gdi"},
    "GetROP2": {"lib": "gdi32", "purpose": "get foreground raster op mode", "category": "win_gdi"},
    "SetPixel": {"lib": "gdi32", "purpose": "set single pixel color", "category": "win_gdi"},
    "GetPixel": {"lib": "gdi32", "purpose": "get single pixel color", "category": "win_gdi"},
    "SetPixelV": {"lib": "gdi32", "purpose": "set pixel to nearest color (fast)", "category": "win_gdi"},
    "CreatePalette": {"lib": "gdi32", "purpose": "create logical palette", "category": "win_gdi"},
    "SelectPalette": {"lib": "gdi32", "purpose": "select palette into DC", "category": "win_gdi"},
    "RealizePalette": {"lib": "gdi32", "purpose": "map palette to system palette", "category": "win_gdi"},
    "GetNearestColor": {"lib": "gdi32", "purpose": "get nearest color DC can represent", "category": "win_gdi"},

    # ---- Drawing primitives ----
    "MoveToEx": {"lib": "gdi32", "purpose": "move current position", "category": "win_gdi"},
    "LineTo": {"lib": "gdi32", "purpose": "draw line from current to point", "category": "win_gdi"},
    "Polyline": {"lib": "gdi32", "purpose": "draw polyline (connected segments)", "category": "win_gdi"},
    "PolylineTo": {"lib": "gdi32", "purpose": "draw polyline and update position", "category": "win_gdi"},
    "Polygon": {"lib": "gdi32", "purpose": "draw filled polygon", "category": "win_gdi"},
    "PolyPolygon": {"lib": "gdi32", "purpose": "draw multiple polygons", "category": "win_gdi"},
    "Rectangle": {"lib": "gdi32", "purpose": "draw filled rectangle", "category": "win_gdi"},
    "RoundRect": {"lib": "gdi32", "purpose": "draw rounded rectangle", "category": "win_gdi"},
    "Ellipse": {"lib": "gdi32", "purpose": "draw filled ellipse", "category": "win_gdi"},
    "Arc": {"lib": "gdi32", "purpose": "draw elliptical arc", "category": "win_gdi"},
    "ArcTo": {"lib": "gdi32", "purpose": "draw arc and update position", "category": "win_gdi"},
    "Chord": {"lib": "gdi32", "purpose": "draw filled chord", "category": "win_gdi"},
    "Pie": {"lib": "gdi32", "purpose": "draw filled pie slice", "category": "win_gdi"},

    # ---- Text / font ----
    "TextOutA": {"lib": "gdi32", "purpose": "draw text at position (ANSI)", "category": "win_gdi"},
    "TextOutW": {"lib": "gdi32", "purpose": "draw text at position (Unicode)", "category": "win_gdi"},
    "ExtTextOutA": {"lib": "gdi32", "purpose": "draw text with clipping (ANSI)", "category": "win_gdi"},
    "ExtTextOutW": {"lib": "gdi32", "purpose": "draw text with clipping (Unicode)", "category": "win_gdi"},
    "GetTextExtentPoint32A": {"lib": "gdi32", "purpose": "measure text extent (ANSI)", "category": "win_gdi"},
    "GetTextExtentPoint32W": {"lib": "gdi32", "purpose": "measure text extent (Unicode)", "category": "win_gdi"},
    "GetTextMetricsA": {"lib": "gdi32", "purpose": "get font text metrics (ANSI)", "category": "win_gdi"},
    "GetTextMetricsW": {"lib": "gdi32", "purpose": "get font text metrics (Unicode)", "category": "win_gdi"},
    "SetTextAlign": {"lib": "gdi32", "purpose": "set text alignment flags", "category": "win_gdi"},
    "GetTextAlign": {"lib": "gdi32", "purpose": "get text alignment flags", "category": "win_gdi"},
    "SetTextJustification": {"lib": "gdi32", "purpose": "set text justification spacing", "category": "win_gdi"},
    "CreateFontA": {"lib": "gdi32", "purpose": "create logical font (ANSI)", "category": "win_gdi"},
    "CreateFontW": {"lib": "gdi32", "purpose": "create logical font (Unicode)", "category": "win_gdi"},
    "CreateFontIndirectA": {"lib": "gdi32", "purpose": "create font from LOGFONT (ANSI)", "category": "win_gdi"},
    "CreateFontIndirectW": {"lib": "gdi32", "purpose": "create font from LOGFONT (Unicode)", "category": "win_gdi"},
    "EnumFontFamiliesExA": {"lib": "gdi32", "purpose": "enumerate font families (ANSI)", "category": "win_gdi"},
    "EnumFontFamiliesExW": {"lib": "gdi32", "purpose": "enumerate font families (Unicode)", "category": "win_gdi"},
    "AddFontResourceA": {"lib": "gdi32", "purpose": "add font resource (ANSI)", "category": "win_gdi"},
    "AddFontResourceW": {"lib": "gdi32", "purpose": "add font resource (Unicode)", "category": "win_gdi"},
    "RemoveFontResourceA": {"lib": "gdi32", "purpose": "remove font resource (ANSI)", "category": "win_gdi"},
    "RemoveFontResourceW": {"lib": "gdi32", "purpose": "remove font resource (Unicode)", "category": "win_gdi"},

    # ---- Bitmap / DIB / blit ----
    "CreateBitmap": {"lib": "gdi32", "purpose": "create bitmap", "category": "win_gdi"},
    "CreateBitmapIndirect": {"lib": "gdi32", "purpose": "create bitmap from BITMAP struct", "category": "win_gdi"},
    "CreateCompatibleBitmap": {"lib": "gdi32", "purpose": "create bitmap compatible with DC", "category": "win_gdi"},
    "CreateDIBSection": {"lib": "gdi32", "purpose": "create device-independent bitmap section", "category": "win_gdi"},
    "CreateDIBitmap": {"lib": "gdi32", "purpose": "create DDB from DIB spec", "category": "win_gdi"},
    "GetDIBits": {"lib": "gdi32", "purpose": "copy bitmap bits to buffer (DIB)", "category": "win_gdi"},
    "SetDIBits": {"lib": "gdi32", "purpose": "set bitmap bits from DIB", "category": "win_gdi"},
    "SetDIBitsToDevice": {"lib": "gdi32", "purpose": "blit DIB to device", "category": "win_gdi"},
    "StretchDIBits": {"lib": "gdi32", "purpose": "blit+stretch DIB to device", "category": "win_gdi"},
    "BitBlt": {"lib": "gdi32", "purpose": "bit-block transfer between DCs", "category": "win_gdi"},
    "StretchBlt": {"lib": "gdi32", "purpose": "bit-block transfer with stretching", "category": "win_gdi"},
    "MaskBlt": {"lib": "gdi32", "purpose": "masked bit-block transfer", "category": "win_gdi"},
    "PlgBlt": {"lib": "gdi32", "purpose": "parallelogram bit-block transfer", "category": "win_gdi"},
    "TransparentBlt": {"lib": "gdi32", "purpose": "transparent bit-block transfer", "category": "win_gdi"},
    "AlphaBlend": {"lib": "gdi32", "purpose": "alpha-blended bit-block transfer", "category": "win_gdi"},
    "GradientFill": {"lib": "gdi32", "purpose": "gradient fill rectangle/triangle", "category": "win_gdi"},
    "PatBlt": {"lib": "gdi32", "purpose": "pattern blit using brush", "category": "win_gdi"},

    # ---- Region / clipping ----
    "CreateRectRgn": {"lib": "gdi32", "purpose": "create rectangular region", "category": "win_gdi"},
    "CreateRectRgnIndirect": {"lib": "gdi32", "purpose": "create rect region from RECT", "category": "win_gdi"},
    "CreateEllipticRgn": {"lib": "gdi32", "purpose": "create elliptic region", "category": "win_gdi"},
    "CreatePolygonRgn": {"lib": "gdi32", "purpose": "create polygon region", "category": "win_gdi"},
    "CreateRoundRectRgn": {"lib": "gdi32", "purpose": "create rounded-rect region", "category": "win_gdi"},
    "CombineRgn": {"lib": "gdi32", "purpose": "combine two regions", "category": "win_gdi"},
    "OffsetRgn": {"lib": "gdi32", "purpose": "offset region by delta", "category": "win_gdi"},
    "EqualRgn": {"lib": "gdi32", "purpose": "test regions for equality", "category": "win_gdi"},
    "PtInRegion": {"lib": "gdi32", "purpose": "test point in region", "category": "win_gdi"},
    "RectInRegion": {"lib": "gdi32", "purpose": "test rect intersects region", "category": "win_gdi"},
    "GetRgnBox": {"lib": "gdi32", "purpose": "get bounding rect of region", "category": "win_gdi"},
    "SelectClipRgn": {"lib": "gdi32", "purpose": "set DC clipping region", "category": "win_gdi"},
    "ExtSelectClipRgn": {"lib": "gdi32", "purpose": "extended DC clip region set", "category": "win_gdi"},
    "IntersectClipRect": {"lib": "gdi32", "purpose": "intersect clip region with rect", "category": "win_gdi"},
    "ExcludeClipRect": {"lib": "gdi32", "purpose": "exclude rect from clip region", "category": "win_gdi"},
    "OffsetClipRgn": {"lib": "gdi32", "purpose": "offset DC clip region", "category": "win_gdi"},
    "GetClipBox": {"lib": "gdi32", "purpose": "get tightest bounding rect of clip region", "category": "win_gdi"},

    # ---- Path ----
    "BeginPath": {"lib": "gdi32", "purpose": "open path bracket in DC", "category": "win_gdi"},
    "EndPath": {"lib": "gdi32", "purpose": "close path bracket in DC", "category": "win_gdi"},
    "StrokePath": {"lib": "gdi32", "purpose": "render current path with pen", "category": "win_gdi"},
    "FillPath": {"lib": "gdi32", "purpose": "fill current path with brush", "category": "win_gdi"},
    "StrokeAndFillPath": {"lib": "gdi32", "purpose": "stroke and fill current path", "category": "win_gdi"},
    "PathToRegion": {"lib": "gdi32", "purpose": "convert current path to region", "category": "win_gdi"},
    "SelectClipPath": {"lib": "gdi32", "purpose": "use current path as clip region", "category": "win_gdi"},

    # ---- Metafile ----
    "CreateEnhMetaFileA": {"lib": "gdi32", "purpose": "create enhanced metafile DC (ANSI)", "category": "win_gdi"},
    "CreateEnhMetaFileW": {"lib": "gdi32", "purpose": "create enhanced metafile DC (Unicode)", "category": "win_gdi"},
    "CloseEnhMetaFile": {"lib": "gdi32", "purpose": "close enhanced metafile DC", "category": "win_gdi"},
    "PlayEnhMetaFile": {"lib": "gdi32", "purpose": "play enhanced metafile", "category": "win_gdi"},
    "DeleteEnhMetaFile": {"lib": "gdi32", "purpose": "delete enhanced metafile handle", "category": "win_gdi"},
}


# ---------------------------------------------------------------------------
# Dispatcher hook — signature_db.py uc alt dict'i isme gore import eder.
# Ayni kalip pe_runtime.SIGNATURES ile ozdes (dict-of-dicts yapisi).
# Anahtar isimleri:
#   "user32_signatures"    <-> _USER32_SIGNATURES   (legacy'de muadil ufak parca
#                               _WIN32_USER32_GDI32_SIGNATURES icinde)
#   "advapi32_signatures"  <-> _ADVAPI32_SIGNATURES (legacy'de muadil ufak parca
#                               _WIN32_ADVAPI32_SIGNATURES icinde)
#   "gdi32_signatures"     <-> _GDI32_SIGNATURES    (legacy'de muadil ufak parca
#                               _WIN32_USER32_GDI32_SIGNATURES icinde)
# ---------------------------------------------------------------------------
SIGNATURES: dict[str, Any] = {
    "user32_signatures": _USER32_SIGNATURES_DATA,
    "advapi32_signatures": _ADVAPI32_SIGNATURES_DATA,
    "gdi32_signatures": _GDI32_SIGNATURES_DATA,
}


__all__ = ["SIGNATURES"]
