"""Markdown rapor uretici -- GitHub-uyumlu Markdown rapor.

Pipeline sonuclarini okunabilir Markdown formatinda uretir.
GitHub Issues/Wiki'de dogrudan render edilebilir.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from karadul import __version__
from karadul.core.result import PipelineResult
from karadul.core.workspace import Workspace

logger = logging.getLogger(__name__)


def _format_size(size: int) -> str:
    """Byte degerini okunabilir formata cevir."""
    if not isinstance(size, (int, float)) or size == 0:
        return "N/A"
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    elif size < 1024 * 1024 * 1024:
        return f"{size / (1024 * 1024):.1f} MB"
    else:
        return f"{size / (1024 * 1024 * 1024):.2f} GB"


def _safe_get(stats: dict, key: str, default: str = "N/A") -> str:
    """Dict'ten guvenli deger al, yoksa default dondur."""
    val = stats.get(key, default)
    if val is None:
        return default
    return str(val)


class MarkdownReporter:
    """GitHub-uyumlu Markdown rapor uretici."""

    def generate(self, result: PipelineResult, workspace: Workspace) -> Path:
        """Markdown rapor uret ve kaydet.

        Args:
            result: Pipeline calisma sonucu.
            workspace: Calisma dizini yoneticisi.

        Returns:
            Kaydedilen Markdown dosyasinin yolu.
        """
        content = self._build_markdown(result, workspace)
        return workspace.save_artifact("reports", "report.md", content)

    def _build_markdown(self, result: PipelineResult, workspace: Workspace) -> str:
        """Markdown icerigini olustur."""
        lines: list[str] = []

        lines.append(f"# Black Widow Analysis Report -- {result.target_name}")
        lines.append("")
        lines.append(f"> Generated by Black Widow (Karadul) v{__version__}")
        lines.append(f"> Date: {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append("")

        # Target Info
        lines.extend(self._section_target(result, workspace))

        # Pipeline Summary
        lines.extend(self._section_pipeline(result))

        # Static Analysis
        lines.extend(self._section_static(result))

        # Dynamic Analysis
        lines.extend(self._section_dynamic(result))

        # Deobfuscation
        lines.extend(self._section_deobfuscation(result))

        # Reconstruction
        lines.extend(self._section_reconstruction(result))

        # v1.2: Deep Algorithm Analysis
        lines.extend(self._section_deep_analysis(result, workspace))

        # Artifacts
        lines.extend(self._section_artifacts(result))

        # How to Run
        lines.extend(self._section_howtorun(result))

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by Black Widow v{__version__} (Karadul)*")
        lines.append("")

        return "\n".join(lines)

    def _section_target(self, result: PipelineResult, workspace: Workspace) -> list[str]:
        """Target Info bolumu."""
        lines = ["## Target Info", ""]
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        lines.append(f"| Name | {result.target_name} |")

        if "identify" in result.stages:
            stats = result.stages["identify"].stats
            lines.append(f"| Type | {_safe_get(stats, 'target_type')} |")
            lines.append(f"| Language | {_safe_get(stats, 'language')} |")
            size = stats.get("file_size", 0)
            lines.append(f"| Size | {_format_size(size) if isinstance(size, (int, float)) else 'N/A'} |")
            lines.append(f"| Bundler | {_safe_get(stats, 'bundler')} |")
        else:
            lines.append("| Type | N/A |")
            lines.append("| Language | N/A |")
            lines.append("| Size | N/A |")

        lines.append(f"| SHA-256 | `{result.target_hash or 'N/A'}` |")
        lines.append(f"| Workspace | `{workspace.path}` |")
        lines.append("")
        return lines

    def _section_pipeline(self, result: PipelineResult) -> list[str]:
        """Pipeline Summary bolumu."""
        lines = ["## Pipeline Summary", ""]
        status = "SUCCESS" if result.success else "PARTIAL / FAILED"
        lines.append(f"**Overall:** {status}  ")
        lines.append(f"**Total Duration:** {result.total_duration:.1f}s  ")
        lines.append("")

        lines.append("| # | Stage | Status | Duration | Details |")
        lines.append("|---|-------|--------|----------|---------|")

        for i, (name, sr) in enumerate(result.stages.items(), 1):
            icon = "PASS" if sr.success else "FAIL"
            details = ""
            if sr.errors:
                details = sr.errors[0][:60]
            elif sr.stats:
                # Bir kac onemli stat goster
                stat_parts = []
                for k, v in list(sr.stats.items())[:3]:
                    stat_parts.append(f"{k}={v}")
                details = ", ".join(stat_parts)

            lines.append(
                f"| {i} | {name} | {icon} | {sr.duration_seconds:.1f}s | {details} |"
            )

        lines.append("")
        return lines

    def _section_static(self, result: PipelineResult) -> list[str]:
        """Static Analysis bolumu."""
        if "static" not in result.stages:
            return []

        sr = result.stages["static"]
        stats = sr.stats
        lines = ["## Static Analysis", ""]

        if not sr.success:
            lines.append(f"*Static analysis failed: {sr.errors[0] if sr.errors else 'unknown'}*")
            lines.append("")
            return lines

        functions = stats.get('functions_found', stats.get('ghidra_function_count', stats.get('functions', 0)))
        strings = stats.get('strings_found', stats.get('ghidra_string_count', stats.get('string_count', stats.get('strings', 0))))
        lines.append(f"- **Functions found:** {functions}")
        lines.append(f"- **Strings found:** {strings}")
        lines.append(f"- **Imports found:** {_safe_get(stats, 'imports_found', '0')}")

        if "webpack_modules" in stats:
            lines.append(f"- **Webpack modules:** {stats['webpack_modules']}")

        lines.append("")
        return lines

    def _section_dynamic(self, result: PipelineResult) -> list[str]:
        """Dynamic Analysis bolumu."""
        if "dynamic" not in result.stages:
            return []

        sr = result.stages["dynamic"]
        stats = sr.stats
        lines = ["## Dynamic Analysis", ""]

        if not sr.success:
            lines.append(f"*Dynamic analysis failed: {sr.errors[0] if sr.errors else 'unknown'}*")
            lines.append("")
            return lines

        lines.append(f"- **File accesses:** {_safe_get(stats, 'file_accesses', '0')}")
        lines.append(f"- **API calls:** {_safe_get(stats, 'api_calls', '0')}")
        lines.append(f"- **Unique modules:** {_safe_get(stats, 'unique_modules', '0')}")
        lines.append(f"- **Crypto operations:** {_safe_get(stats, 'crypto_operations', '0')}")

        lines.append("")
        return lines

    def _section_deobfuscation(self, result: PipelineResult) -> list[str]:
        """Deobfuscation bolumu."""
        if "deobfuscate" not in result.stages:
            return []

        sr = result.stages["deobfuscate"]
        stats = sr.stats
        lines = ["## Deobfuscation", ""]

        if not sr.success:
            lines.append(f"*Deobfuscation failed: {sr.errors[0] if sr.errors else 'unknown'}*")
            lines.append("")
            return lines

        lines.append(f"- **Steps completed:** {_safe_get(stats, 'steps_completed', '0')}")

        if "chain" in stats:
            chain = stats["chain"]
            if isinstance(chain, list):
                lines.append(f"- **Chain:** {' -> '.join(chain)}")

        if "size_before" in stats and "size_after" in stats:
            before = stats["size_before"]
            after = stats["size_after"]
            if isinstance(before, (int, float)) and isinstance(after, (int, float)) and before > 0:
                ratio = (after / before) * 100
                lines.append(f"- **Size change:** {_format_size(int(before))} -> {_format_size(int(after))} ({ratio:.0f}%)")

        lines.append("")
        return lines

    def _section_reconstruction(self, result: PipelineResult) -> list[str]:
        """Reconstruction bolumu."""
        if "reconstruct" not in result.stages:
            return []

        sr = result.stages["reconstruct"]
        stats = sr.stats
        lines = ["## Reconstruction", ""]

        if not sr.success:
            lines.append(f"*Reconstruction failed: {sr.errors[0] if sr.errors else 'unknown'}*")
            lines.append("")
            return lines

        lines.append(f"- **Modules extracted:** {_safe_get(stats, 'modules_extracted', '0')}")
        lines.append(f"- **Variables renamed:** {_safe_get(stats, 'variables_renamed', '0')}")
        lines.append(f"- **Coverage:** {_safe_get(stats, 'coverage_percent', 'N/A')}%")
        lines.append(f"- **Runnable project:** {'Yes' if stats.get('runnable_project') else 'No'}")

        lines.append("")
        return lines

    def _section_deep_analysis(self, result: PipelineResult, workspace: Workspace) -> list[str]:
        """v1.2 Deep Algorithm Analysis section.

        Includes dispatch resolution stats, algorithm compositions,
        and call trace summary.
        """
        if "reconstruct" not in result.stages:
            return []

        stats = result.stages["reconstruct"].stats

        has_dispatch = "dispatch_sites" in stats
        has_compositions = "compositions" in stats
        has_traces = "trace_targets" in stats

        if not (has_dispatch or has_compositions or has_traces):
            return []

        lines: list[str] = ["## Deep Algorithm Analysis", ""]

        # -- 1. Dispatch Resolution Stats --
        if has_dispatch:
            total_sites = stats.get("dispatch_sites", 0)
            resolved = stats.get("dispatch_resolved", 0)
            rate_str = stats.get("dispatch_resolution_rate", "0%")

            lines.append("### Virtual Dispatch Resolution")
            lines.append("")
            lines.append("| Metric | Value |")
            lines.append("|--------|-------|")
            lines.append(f"| Total dispatch sites | {total_sites} |")
            lines.append(f"| Resolved | {resolved} |")
            lines.append(f"| Resolution rate | {rate_str} |")
            lines.append("")

        # -- 2. Algorithm Compositions --
        if has_compositions:
            n_comps = stats.get("compositions", 0)
            lines.append(f"### Algorithm Compositions ({n_comps} detected)")
            lines.append("")

            comp_data = workspace.load_json("reconstructed", "algorithm_compositions")
            if comp_data:
                comp_list = comp_data.get("compositions", [])
                for comp in comp_list:
                    comp_name = comp.get("name", "Unknown")
                    comp_type = comp.get("type", "pipeline")
                    confidence = comp.get("confidence", 0)
                    stages = comp.get("stages", [])

                    stage_names = [
                        s.get("label", s.get("name", "?")) for s in stages
                    ]
                    stage_str = " -> ".join(stage_names[:8])
                    if len(stage_names) > 8:
                        stage_str += f" ... +{len(stage_names) - 8}"

                    lines.append(
                        f"- **{comp_name}** ({comp_type}, confidence: {confidence:.0%})"
                    )
                    lines.append(f"  - Stages: {stage_str}")
                    lines.append("")
            else:
                lines.append(f"*{n_comps} compositions detected. See compositions.md for details.*")
                lines.append("")

        # -- 3. Call Trace Summary --
        if has_traces:
            n_targets = stats.get("trace_targets", 0)
            n_nodes = stats.get("trace_total_nodes", 0)
            lines.append(f"### Call Chain Traces ({n_targets} targets, {n_nodes} nodes)")
            lines.append("")

            # Load and extract first tree from call_traces.md
            trace_md_path = workspace.path / "reconstructed" / "call_traces.md"
            if trace_md_path.exists():
                try:
                    import re
                    trace_content = trace_md_path.read_text(errors="replace")
                    # Extract first code block (ASCII tree)
                    code_blocks = re.findall(
                        r"## \d+\. (.+?)\n.*?```\n(.*?)```",
                        trace_content,
                        re.DOTALL,
                    )
                    if code_blocks:
                        target_name, tree_text = code_blocks[0]
                        tree_text = tree_text.strip()
                        # Limit to 30 lines
                        tree_lines = tree_text.split("\n")
                        lines.append(f"**Top trace: {target_name}**")
                        lines.append("")
                        lines.append("```")
                        lines.extend(tree_lines[:30])
                        if len(tree_lines) > 30:
                            lines.append(f"... ({len(tree_lines) - 30} more lines)")
                        lines.append("```")
                        lines.append("")

                    if len(code_blocks) > 1:
                        lines.append(
                            f"*{len(code_blocks) - 1} more traces available in call_traces.md*"
                        )
                        lines.append("")
                except Exception:
                    logger.debug("Call trace code block parse basarisiz, fallback kullaniliyor", exc_info=True)
                    lines.append(
                        f"*{n_targets} targets traced. See call_traces.md for details.*"
                    )
                    lines.append("")
            else:
                lines.append(
                    f"*{n_targets} targets traced. See call_traces.md for details.*"
                )
                lines.append("")

        return lines

    def _section_artifacts(self, result: PipelineResult) -> list[str]:
        """Artifacts bolumu."""
        all_artifacts = result.get_all_artifacts()
        if not all_artifacts:
            return []

        lines = ["## Artifacts", ""]
        lines.append("| Name | Path |")
        lines.append("|------|------|")

        for name, path in all_artifacts.items():
            lines.append(f"| {name} | `{path}` |")

        lines.append("")
        return lines

    def _section_howtorun(self, result: PipelineResult) -> list[str]:
        """How to Run bolumu."""
        if "reconstruct" not in result.stages:
            return []

        sr = result.stages["reconstruct"]
        if not sr.success or not sr.stats.get("runnable_project"):
            return []

        lines = ["## How to Run", ""]
        lines.append("```bash")
        lines.append(f"cd {result.workspace_path}/reconstructed/")
        lines.append("npm install")
        lines.append("npm start")
        lines.append("```")
        lines.append("")
        return lines
